
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","pay_num","reward_type_low","reward_type_high","record_flag_low","record_flag_high","get_flag_low","get_flag_high","get_num",},
[1] = {1,150,"first_recharge_low","first_recharge_high","recharge_first_record_low","recharge_first_record_high","recharge_first_get_low","recharge_first_get_high",3,},

}
