
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","flag","reward","require",},
[1] = {1,9,"product3001",{item={id={3,},num={90,},},flag_reward={10101,},},{key={"dcard1",},minval={0,},maxval={0,},text={"recharge_activity_card_1.require.text[1]",},},},
[2] = {2,9,"product3002",{item={id={1200,},num={50,},},flag_reward={10102,},},{key={"dcard2",},minval={0,},maxval={0,},text={"recharge_activity_card_2.require.text[1]",},},},
[3] = {3,9,"product3003",{item={id={2502,},num={1,},},flag_reward={10103,},},{key={"dcard3",},minval={0,},maxval={0,},text={"recharge_activity_card_3.require.text[1]",},},},

}
