
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","question","choose_number","choose","choose_desc",},
[100] = {100,"quest_choose_100.question",2,{"quest_choose_100.choose[1]","quest_choose_100.choose[2]","quest_choose_100.choose[3]",},{"1036_2_1","1036_2_2","",},},
[101] = {101,"quest_choose_101.question",2,{"quest_choose_101.choose[1]","quest_choose_101.choose[2]","quest_choose_101.choose[3]",},{"1037_2_1","1037_2_2","",},},
[102] = {102,"quest_choose_102.question",3,{"quest_choose_102.choose[1]","quest_choose_102.choose[2]","quest_choose_102.choose[3]",},{"1026_2_1","1026_2_2","1026_2_3",},},
[103] = {103,"quest_choose_103.question",2,{"quest_choose_103.choose[1]","quest_choose_103.choose[2]","quest_choose_103.choose[3]",},{"1039_2_1","1039_2_2","",},},
[104] = {104,"quest_choose_104.question",3,{"quest_choose_104.choose[1]","quest_choose_104.choose[2]","quest_choose_104.choose[3]",},{"1040_2_1","1040_2_2","1040_2_3",},},
[105] = {105,"quest_choose_105.question",2,{"quest_choose_105.choose[1]","quest_choose_105.choose[2]","quest_choose_105.choose[3]",},{"1041_2_1","1041_2_2","",},},
[106] = {106,"quest_choose_106.question",2,{"quest_choose_106.choose[1]","quest_choose_106.choose[2]","quest_choose_106.choose[3]",},{"1158_2_1","1158_2_2","",},},
[107] = {107,"quest_choose_107.question",2,{"quest_choose_107.choose[1]","quest_choose_107.choose[2]","quest_choose_107.choose[3]",},{"1204_2_1","1204_2_2","",},},
[108] = {108,"quest_choose_108.question",2,{"quest_choose_108.choose[1]","quest_choose_108.choose[2]","quest_choose_108.choose[3]",},{"1138_2_1","1138_2_2","",},},
[109] = {109,"quest_choose_109.question",2,{"quest_choose_109.choose[1]","quest_choose_109.choose[2]","quest_choose_109.choose[3]",},{"1210_2_1","1210_2_2","",},},

}
