---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2019/1/18 18:08
---春节红包

local _M = {}
_M.__index = _M

local SpringFestivalModel = require 'Model/SpringFestivalModel'
local UIUtil = require 'UI/UIUtil'
local ItemModel = require 'Model/ItemModel'

function _M.OnInit(self)
    --覆盖/无动画/黑底
    self.ui.menu.ShowType = UIShowType.Cover
    self.ui.menu:SetCompAnime(self.ui.menu, UIAnimeType.NoAnime)
    self.ui.menu:SetFullBackground(UILayout.CreateUILayoutColor(UnityEngine.Color(0,0,0,0.5),UnityEngine.Color(0,0,0,0.5)))
end

local function InitCvs(self)
    --today
    local today = self.comps.cvs_today
    
    local gg_plan = today:FindChildByEditName('gg_plan',true)
    gg_plan.Text = tostring(self.today)..'/'..tostring(self.actData.maxmoney)
    gg_plan.Value= (self.today/self.actData.maxmoney)*100
    
    --yesterday
    local yesterday = self.comps.cvs_yesterday
    
    local ib_yuanbao = yesterday:FindChildByEditName('ib_yuanbao',true)
    local item1 = ItemModel.GetDetailByTemplateID(self.actData.money_template_id)
    UIUtil.SetImage(ib_yuanbao,'static/item/'..item1.static.atlas_id,false, UILayoutStyle.IMAGE_STYLE_BACK_4)
    local ib_fubi = yesterday:FindChildByEditName('ib_fubi',true)
    local item2 = ItemModel.GetDetailByTemplateID(self.actData.money_item_id)
    UIUtil.SetImage(ib_fubi,'static/item/'..item2.static.atlas_id,false, UILayoutStyle.IMAGE_STYLE_BACK_4)
    
    local lb_yuanbao = yesterday:FindChildByEditName('lb_yuanbao',true)
    lb_yuanbao.Text = self.yuanbao
    local lb_fubi= yesterday:FindChildByEditName('lb_fubi',true)
    lb_fubi.Text = self.fuqibi
    
    local gg_plan2 = yesterday:FindChildByEditName('gg_plan2',true)
    local yesInfo = SpringFestivalModel.GetSpringFestivalPacketsInfo(self.yuanbao)
    gg_plan2.Value= (self.yuanbao/yesInfo.maxmoney)*100
    
end

function _M.OnEnter(self,params)
    self.actInfo = params or SpringFestivalModel.GetActInfoByTag(string.lower(self.ui.tag))
    if not SpringFestivalModel.CheckIsOpening(self.actInfo.end_time) then
        self.ui:Close()
        return
    end
    
    SpringFestivalModel.SetOpeningTime(self.comps.lb_acttime,self.actInfo.start_time,self.actInfo.end_time)
    
    SpringFestivalModel.RequestSpringFestivalPacketsInfo(function (rsp)
        self.today = rsp.s2c_cumulative_count -- 当天累计
        self.fuqibi = rsp.s2c_item_count -- 昨日福气币
        self.yuanbao = rsp.s2c_currency_count -- 昨日元宝
        self.actData = SpringFestivalModel.GetSpringFestivalPacketsInfo(self.today)
        InitCvs(self)
    end)
end

function _M.OnExit(self)

end


return _M