---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2019/1/19 11:11
---迎财神

local _M = {}
_M.__index = _M

local SpringFestivalModel = require 'Model/SpringFestivalModel'
local UIUtil = require 'UI/UIUtil'
local ItemModel = require 'Model/ItemModel'
local Util = require 'Logic/Util'
local ActivityModel = require 'Model/ActivityModel'

_M.ExtraReward={
    NotCompleted = 1,
    WaitForGetReward = 2,
    Finished = 3,
}

function _M.OnInit(self)
    --覆盖/无动画/黑底
    self.ui.menu.ShowType = UIShowType.Cover
    self.ui.menu:SetCompAnime(self.ui.menu, UIAnimeType.NoAnime)
    self.ui.menu:SetFullBackground(UILayout.CreateUILayoutColor(UnityEngine.Color(0,0,0,0.5),UnityEngine.Color(0,0,0,0.5)))
end


local function PlayEffect(self,node,res,index)
    local transSet = TransformSet()
    transSet.Layer = Constants.Layer.UI
    transSet.LayerOrder = 5000
    transSet.Pos = Vector3(node.Width/2,-node.Height/2,0)
    transSet.DisableToUnload = true
    transSet.Parent = node.Transform
    transSet.Scale = Vector3(0.5,1.2,1)
    self.eff[index] = RenderSystem.Instance:LoadGameObject(res,transSet,nil)
end

local function ReleaseEffect(self)
    if self.eff then
        for i, v in ipairs(self.eff) do
            RenderSystem.Instance:Unload(self.eff[i])
        end
        self.eff = {}
    end
    if self.flyEff then
        for i, v in ipairs(self.flyEff) do
            RenderSystem.Instance:Unload(self.flyEff[i])
        end
        self.flyEff = {}
    end
end


local function ShowRecord(node,index)
    local lb_content = node:FindChildByEditName('lb_content',true)
    lb_content.UnityRichText = SpringFestivalModel.RewardRecord[index]
end
--初始化或者刷新获奖记录
local function InitRewardRecord(self)
    self.comps.cvs_reward.Visible = false
    if #SpringFestivalModel.RewardRecord == 0 then
        return
    end
    local function eachupdatecb(node,index)
        ShowRecord(node,index)
    end
    UIUtil.ConfigVScrollPan(self.comps.sp_list,self.comps.cvs_reward,#SpringFestivalModel.RewardRecord,eachupdatecb)
    UIUtil.MoveToScrollCell(self.comps.sp_list,#SpringFestivalModel.RewardRecord,nil)
end


local function InitRewardIcon(self,index)
    local time = self.time >= self.actData[index].require.minval[1] and 
            self.actData[index].require.minval[1]..'/'..self.actData[index].require.minval[1] or 
            self.time..'/'..self.actData[index].require.minval[1]
    self.lb_count[index].Text = Util.GetText('pvp_rewardcount',time)
    self.ib_get[index].Visible = self.RewardList[index].state == _M.ExtraReward.Finished
    
    --等待领奖
    if self.RewardList[index].state == _M.ExtraReward.WaitForGetReward then
        PlayEffect(self,self.cvs_item[index],'/res/effect/ui/ef_ui_chest.assetbundles',index)
    end
    
    self.cvs_item[index].TouchClick = function()
        if self.RewardList[index].state ~= _M.ExtraReward.WaitForGetReward then --如果不可领奖，显示物品框
            local drop ={}
            for i, v in ipairs(self.actData[index].item_show) do
                table.insert(drop,{id = self.actData[index].item_show[i],num = self.actData[index].item_show_num[i]})
            end
            GlobalHooks.UI.OpenUI('PreviewItem',0,drop)
        else--发送领奖协议
            SpringFestivalModel.RequestSpringFestivalCaishenInfo(self.actInfo.activity_id,self.actData[index].rewardtime,function (rsp)
                --获得物品弹框
                if next(rsp.s2c_data) then
                    local drop ={}
                    for i, v in ipairs(rsp.s2c_data) do
                        table.insert(drop,{id = rsp.s2c_data[i].templateid,num = rsp.s2c_data[i].num})
                    end
                    GlobalHooks.UI.OpenUI('GainItem',0,drop,3)
                end
                --变更领奖状态
                self.ib_get[index].Visible = true
                self.RewardList[index].state = _M.ExtraReward.Finished
                if self.eff[index] then
                    RenderSystem.Instance:Unload(self.eff[index])
                end
            end)
        end
    end
end

--供奉完，刷新进度条或者添加可领取特效
local function RefreshInfo(self)
    --刷新进度条&福气币
    self.comps.gg_plan.Value = (self.time/self.actData[#self.actData].require.minval[1])*100 >=100 and 100 or (self.time/self.actData[#self.actData].require.minval[1])*100
    self.comps.lb_fubinum.Text = ItemModel.CountItemByTemplateID(Constants.VirtualItems.GoodFortune)
    --刷新是否可领取宝箱
    for i, v in ipairs(self.RewardList) do
        if self.RewardList[i].state == _M.ExtraReward.WaitForGetReward and not self.eff[i] then
            PlayEffect(self,self.cvs_item[i],'/res/effect/ui/ef_ui_chest.assetbundles',i)
        end
    end
    --刷新次数
    for i = 1, 4 do
        local time = self.time >= self.actData[i].require.minval[1] and
                self.actData[i].require.minval[1]..'/'..self.actData[i].require.minval[1] or
                self.time..'/'..self.actData[i].require.minval[1]
        self.lb_count[i].Text = Util.GetText('pvp_rewardcount',time)
    end
end

local function ReleaseAllTimer(self)
    if self.efftime then
        for i, v in ipairs(self.efftime) do
            LuaTimer.Delete(self.efftime[i])
        end
        self.efftime ={}
    end
end

local function PlayFlyEffect(self,res,finish)
    local transSet = TransformSet()
    transSet.Layer = Constants.Layer.UI
    transSet.LayerOrder = 5000
    transSet.Pos = Vector3(0,0,200)
    transSet.DisableToUnload = true
    transSet.Parent = self.comps.cvs_eff.Transform

    self.flyEff =self.flyEff or {}
    local num = #self.flyEff + 1
    self.flyEff[num] = RenderSystem.Instance:LoadGameObject(res, transSet, function(aoe)
        local symbol = math.random(1,100) > 50 and 1 or -1
        local Xspeed = math.random()
        local Yspeed = math.random(50,100)/100
        local x = 0
        local y =0
        local t = 0
        self.efftime = self.efftime or {}
        local timenum = #self.efftime + 1
        self.efftime[timenum] = LuaTimer.Add(0,20,
            function()
                x = x + 5
                y = y + 15
                aoe.gameObject.transform.position =Vector3(math.sin(x*Mathf.Deg2Rad)*Xspeed*symbol,math.sin(y*Mathf.Deg2Rad)*Yspeed,0)
                if aoe.gameObject.transform.position.y <= -0.4 then
                    LuaTimer.Delete(self.efftime[timenum])
                    self.efftime[timenum] = 0
                    local num2 = #self.efftime + 1
                    self.efftime[num2] = LuaTimer.Add(0,20,
                        function ()
                            t = t + 0.05
                            if t >= 0.6 then
                                RenderSystem.Instance:Unload(aoe.gameObject)
                                return false
                            end
                            aoe.gameObject.transform.position = Vector3.Lerp(aoe.gameObject.transform.position,finish.Transform.position+Vector3(0.1,-0.1,0),t);
                            return true
                        end)
                    return false
                end
                return true
            end)
    end)
end


local function InitCountRewardComponent(self)
    for i = 1, #self.actData do
        local cvs_item = self.comps.cvs_itemlist:FindChildByEditName('cvs_item'..i,true)
        local lb_huoli = cvs_item:FindChildByEditName('lb_huoli',true)
        local ib_get = cvs_item:FindChildByEditName('ib_get'..i,true)
        table.insert(self.cvs_item,cvs_item)
        table.insert(self.lb_count,lb_huoli)
        table.insert(self.ib_get,ib_get)
        InitRewardIcon(self,i)
    end

    self.comps.gg_plan.Value = (self.time/self.actData[#self.actData].require.minval[1])*100 >=100 and 100 or (self.time/self.actData[#self.actData].require.minval[1])*100
    --供奉
    self.comps.btn_cost.TouchClick =function()
        if ItemModel.CountItemByTemplateID(Constants.VirtualItems.GoodFortune) < 300 then
            GameAlertManager.Instance:ShowNotify(Constants.SpringFestival.NotEnoughCoin)
        else
            ActivityModel.RequestGetTurnTableReward(self.actInfo.activity_id,function (rsp)
                self.time = rsp.s2c_times - 1
                table.sort(rsp.s2c_RewardList,function (a,b)
                    return a.index < b.index
                end)
                self.RewardList = rsp.s2c_RewardList
                --判断往哪个箱子飞
                local index = 4 
                for i, v in ipairs(self.RewardList) do
                    if v.state == _M.ExtraReward.NotCompleted then
                        index = i
                        break
                    end
                end
                RefreshInfo(self)
                for i = 1, #rsp.s2c_data do
                    PlayFlyEffect(self,"/res/effect/ui/ef_ui_xiuxing_click_02.assetbundles",self.cvs_item[index])
                end
                --刷新主界面的福气币
                EventManager.Fire('Event.SpringFestival.BuyItem',{})
            end)
        end
    end
end


function _M.OnEnter(self,params)
    
    self.actInfo = params or SpringFestivalModel.GetActInfoByTag(string.lower(self.ui.tag))
    if not SpringFestivalModel.CheckIsOpening(self.actInfo.end_time) then
        self.ui:Close()
        return
    end
    
    self.cvs_item={}
    self.lb_count={}
    self.ib_get={}
    self.eff={}
    
    function _M.OnUpdateRecord()
        InitRewardRecord(self)
    end
    EventManager.Subscribe("Event.SpringFestival.UpdateRecord",_M.OnUpdateRecord)
    
    self.actData = SpringFestivalModel.GetSpringActBySheetName(self.actInfo.sheet_name)
    SpringFestivalModel.SetOpeningTime(self.comps.lb_itemnum,self.actInfo.start_time,self.actInfo.end_time)
    SpringFestivalModel.SetHelpCvsVisibleOrInvisible(self.comps.btn_rule,self.comps.cvs_help)
    self.comps.lb_fubinum.Text = ItemModel.CountItemByTemplateID(Constants.VirtualItems.GoodFortune)

    ActivityModel.RequestGetTurnTableInfo(self.actInfo.activity_id,function (rsp)
        --rsp.s2c_times 下一次的次数
        --self.time 已经抽奖的次数
        self.time = rsp.s2c_times - 1
        --额外奖励领取状态
        table.sort(rsp.s2c_RewardList,function (a,b)
            return a.index < b.index
        end)
        self.RewardList = rsp.s2c_RewardList
        InitCountRewardComponent(self)
        InitRewardRecord(self)
    end)
end

function _M.OnExit(self)
    EventManager.Unsubscribe("Event.SpringFestival.UpdateRecord",_M.OnUpdateRecord)
    ReleaseEffect(self)
    ReleaseAllTimer(self)
end


return _M