
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","chapter_name","open_level","open_questid","chapter_number","chapter_id","chapter_small_pic","chapter_pic","story_introduction","role_introduction","quest_type","quest_desc","quest_id","quest_star","quest_series",},
[1] = {1,"three_life_book_1.chapter_name",1,1000,"three_life_book_1.chapter_number",1,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",1,2,{1,2,},{"three_life_book_1.quest_desc[1]","three_life_book_1.quest_desc[2]",},{1001,1010,},{2,2,},{"","",},},
[2] = {2,"three_life_book_2.chapter_name",2,1001,"three_life_book_2.chapter_number",2,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",3,4,{1,2,},{"three_life_book_2.quest_desc[1]","three_life_book_2.quest_desc[2]",},{1002,1011,},{1,1,},{"","",},},
[3] = {3,"three_life_book_3.chapter_name",3,1002,"three_life_book_3.chapter_number",3,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",5,6,{1,2,},{"three_life_book_3.quest_desc[1]","three_life_book_3.quest_desc[2]",},{1003,1012,},{1,1,},{"","",},},
[4] = {4,"three_life_book_4.chapter_name",4,1003,"three_life_book_4.chapter_number",5,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",1,2,{1,2,},{"three_life_book_4.quest_desc[1]","three_life_book_4.quest_desc[2]",},{1004,1013,},{1,1,},{"","",},},
[5] = {5,"three_life_book_5.chapter_name",5,1004,"three_life_book_5.chapter_number",4,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",3,4,{1,2,},{"three_life_book_5.quest_desc[1]","three_life_book_5.quest_desc[2]",},{1005,1014,},{1,1,},{"","",},},
[6] = {6,"three_life_book_6.chapter_name",6,1005,"three_life_book_6.chapter_number",6,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",5,6,{1,2,},{"three_life_book_6.quest_desc[1]","three_life_book_6.quest_desc[2]",},{1006,1015,},{3,3,},{"","",},},
[7] = {7,"three_life_book_7.chapter_name",7,1006,"three_life_book_7.chapter_number",7,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",3,4,{1,2,},{"three_life_book_7.quest_desc[1]","three_life_book_7.quest_desc[2]",},{1007,1016,},{1,1,},{"","",},},
[8] = {8,"three_life_book_8.chapter_name",8,1007,"three_life_book_8.chapter_number",8,"$dynamic/TL_sanshenglu/output/TL_sanshenglu.xml|TL_sanshenglu|cp_1","sslbg_1.png",5,6,{1,2,},{"three_life_book_8.quest_desc[1]","three_life_book_8.quest_desc[2]",},{1008,1017,},{1,1,},{"","",},},

}
