
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","text","channel_img","chat_level","chat_cd","hongbao","ishide",},
[1] = {1,"chat_setting_1.text","",0,0,0,0,},
[2] = {2,"chat_setting_2.text","",0,0,0,0,},
[3] = {3,"chat_setting_3.text","",0,0,0,0,},
[4] = {4,"chat_setting_4.text","",0,0,0,0,},
[5] = {5,"chat_setting_5.text","",0,0,0,0,},
[6] = {6,"chat_setting_6.text","",0,0,0,0,},
[7] = {7,"chat_setting_7.text","",0,0,0,0,},
[8] = {8,"chat_setting_8.text","",0,0,0,0,},

}
