
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","name","cost_id","cost_num","reward",},
[1] = {1,"普通结婚",1,5201314,{title_id=1401,},},
[2] = {2,"豪华结婚",3,1999,{title_id=1402,},},

}
