
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"relation_key","menu_type","menu_enumerate",},
["stranger"] = {"stranger",2,"1,3,4,5,6,8,26",},
["friend"] = {"friend",2,"2,3,4,5,6,8,25,26",},
["blacklist"] = {"blacklist",2,"3,4,6,9,26",},
["teamlead"] = {"teamlead",2,"1,3,4,6,10,11,18,26",},
["teammate"] = {"teammate",2,"1,3,4,6,26",},
["team_self"] = {"team_self",1,"12",},
["friendapply"] = {"friendapply",2,"3,4,5,6,26",},
["enemy"] = {"enemy",2,"3,4,6,26",},
["guild_chairman"] = {"guild_chairman",2,"1,3,4,5,13,15,17,26",},
["guild_vicechairman"] = {"guild_vicechairman",2,"1,3,4,5,14,15,17,26",},
["guild_elder"] = {"guild_elder",2,"1,3,4,5,14,15,17,26",},
["guild_guardian"] = {"guild_guardian",2,"1,3,4,5,15,17,26",},
["guild_member"] = {"guild_member",2,"1,3,4,5,25,26",},
["guild_self"] = {"guild_self",1,"16",},
["chat"] = {"chat",2,"1,3,4,5,6,8,20,26",},
["stranger_more"] = {"stranger_more",2,"1,4,5,6,8",},
["shimen_appoint"] = {"shimen_appoint",1,"21",},
["shimen_noappoint"] = {"shimen_noappoint",1,"3,22,23,24,26",},
["shimen_friend"] = {"shimen_friend",1,"3,26",},
["shimen_stranger"] = {"shimen_stranger",1,"1,3,26",},

}
