
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_name","activity_icon","activity_desc","function_id","config_cur","config_max",},
[1] = {1,"guild_activity_1.activity_name","#dynamic/TL_functions/output/TL_functions.xml|TL_functions|39","guild_activity_1.activity_desc","xianmeng","LoopQuestTime/1001","guild_quest_times",},
[2] = {2,"guild_activity_2.activity_name","#dynamic/TL_functions/output/TL_functions.xml|TL_functions|29","guild_activity_2.activity_desc","guildattack","LoopQuestTime/2000","guild_breakreward_times",},
[3] = {3,"guild_activity_3.activity_name","#dynamic/TL_functions/output/TL_functions.xml|TL_functions|35","guild_activity_3.activity_desc","mythicalbeasts","mythicalbeaststimes","mythicalbeasts_times",},
[4] = {4,"guild_activity_4.activity_name","#dynamic/TL_functions/output/TL_functions.xml|TL_functions|40","guild_activity_4.activity_desc","guildwanted","GuildWantedFinishTime","guild_wantedReceiveTimes",},
[5] = {5,"guild_activity_5.activity_name","#dynamic/TL_functions/output/TL_functions.xml|TL_functions|30","guild_activity_5.activity_desc","guildcarriage","guild_carriage","guild_carriage_times",},

}
