
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","position_id","position","limit_num","guild_rename","transfer_president","building_lvup","apply_gvg","notice","change_position","request_player","kick_player","impeach_president","recruit_notice","recruit_propaganda","apply_condition","allow_settarget","allow_sign","allow_kick","fort_sign","fort_order","fort_kick","relation_key","icon",},
[1] = {1,10,"guild_position_1.position",1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,"guild_chairman","",},
[2] = {2,20,"guild_position_2.position",2,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,"guild_vicechairman","",},
[3] = {3,30,"guild_position_3.position",4,0,0,0,0,1,1,1,1,1,0,1,1,0,0,0,0,0,0,"guild_elder","",},
[4] = {4,40,"guild_position_4.position",8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,"guild_guardian","",},
[5] = {5,50,"guild_position_5.position",999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"guild_member","",},

}
