
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","donate_type","cost_id","cost_num","capital_num","contribution_num",},
[1] = {1,1,1,10000,1000,100,},
[2] = {2,2,2,200,4000,400,},
[3] = {3,3,3,50,20000,1000,},

}
