
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","gatherid","mapid","effervescent","showtime","destroy_type",},
[1] = {1,20010023,600010,"ef_wf_ignition.assetbundles",1,1,},
[2] = {2,20010024,600010,"ef_wf_poisonoussmoke.assetbundles",1,2,},
[3] = {3,20010025,600010,"",0,3,},
[4] = {4,20010026,600010,"ef_wf_ignition.assetbundles",1,1,},
[5] = {5,20010027,600010,"ef_wf_poisonoussmoke.assetbundles",1,2,},
[6] = {6,20010028,600010,"",0,3,},

}
