
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","proname","pro","sex","desc","model_body","model_head","model_weapon","initItem","unit_template_id","modle",},
[1] = {1,"characterBase_1.proname",1,0,"characterBase_1.desc","play_222001","kong","weapon_tg_001","",220,{key={"Avatar_Body","Avatar_Head","",},value={"player_221000","player_121000","",},},},
[2] = {2,"characterBase_2.proname",1,1,"characterBase_2.desc","play_222001","kong","weapon_tg_001","",220,{key={"Avatar_Body","Avatar_Head","",},value={"player_222000","player_122000","",},},},
[3] = {3,"characterBase_3.proname",2,0,"characterBase_3.desc","play_222001","kong","weapon_tg_001","",220,{key={"Avatar_Body","Avatar_Head","",},value={"player_221000","player_121000","",},},},
[4] = {4,"characterBase_4.proname",2,1,"characterBase_4.desc","play_222001","kong","weapon_tg_001","",220,{key={"Avatar_Body","Avatar_Head","",},value={"player_222000","player_122000","",},},},
[5] = {5,"characterBase_5.proname",3,0,"characterBase_5.desc","play_231001","kong","weapon_kl_001","",230,{key={"Avatar_Body","Avatar_Head","",},value={"player_231000","player_131000","",},},},
[6] = {6,"characterBase_6.proname",3,1,"characterBase_6.desc","play_231001","kong","weapon_kl_001","",230,{key={"Avatar_Body","Avatar_Head","",},value={"player_232000","player_132000","",},},},
[7] = {7,"characterBase_7.proname",4,0,"characterBase_7.desc","play_242001","kong","weapon_qq_001","",240,{key={"Avatar_Body","Avatar_Head","",},value={"player_241000","player_141000","",},},},
[8] = {8,"characterBase_8.proname",4,1,"characterBase_8.desc","play_242001","kong","weapon_qq_001","",240,{key={"Avatar_Body","Avatar_Head","",},value={"player_242000","player_142000","",},},},

}
