
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","artifact_stage","speed","total","show",},
[1] = {1,0,100,3000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[2] = {2,1,100,3000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[3] = {3,2,100,3500,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[4] = {4,3,100,3500,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[5] = {5,4,100,4000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[6] = {6,5,100,4000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[7] = {7,6,100,4500,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[8] = {8,7,100,4500,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[9] = {9,8,100,5000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[10] = {10,9,100,5000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[11] = {11,10,100,5000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[12] = {12,11,100,5000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[13] = {13,12,100,5000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},
[14] = {14,13,100,5000,{type={"#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|49","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|50","#dynamic/TL_practicebreak/output/TL_practicebreak.xml|TL_practicebreak|51",},val={200,200,225,},},},

}
