
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","event_key","flag","cost",},
[1] = {1,"res_dungeon_exp_tickets",{id={2109,},},{count={1,},type={3,},num={500,},},},
[2] = {2,"res_dungeon_wing_tickets",{id={2110,},},{count={1,},type={3,},num={500,},},},
[3] = {3,"res_dungeon_mount_tickets",{id={2111,},},{count={1,},type={3,},num={500,},},},
[4] = {4,"res_dungeon_miracle_tickets",{id={2112,},},{count={1,},type={3,},num={500,},},},
[5] = {5,"god_island_tickets",{id={2113,},},{count={1,},type={3,},num={500,},},},
[6] = {6,"tower_reset",{id={2114,},},{count={1,},type={3,},num={500,},},},

}
