
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","order","boss_level","mapid","refresh_time","reward","pic_res","function_tag",},
[1] = {1,1,25,"长海","1",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang1",},
[2] = {2,2,50,"北荒","2",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang2",},
[3] = {3,3,60,"雪苑","3",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang3",},
[4] = {4,4,80,"十里桃林","4",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang4",},
[5] = {5,5,90,"东海","5",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang5",},
[6] = {6,6,100,"夏周废墟","6",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang6",},
[7] = {7,7,110,"太一神殿","7",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang7",},
[8] = {8,8,120,"青丘","8",{id={1,5234,5195,5194,2,5192,1200,1201,},},"#dynamic/TL_activity/output/TL_activity.xml|TL_activity|24","xl_fhdbk_fenghuang8",},

}
