
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","uitag_id","subuitag_id","button_show","icon","button_text","require",},
[1] = {1,"StoreMain","","item_goto_1.button_show","","",{key={"",},minval={0,},maxval={0,},text={"",},},},
[2] = {2,"SmithyStrengthen","","item_goto_2.button_show","","",{key={"",},minval={0,},maxval={0,},text={"",},},},
[3] = {3,"","","item_goto_3.button_show","","",{key={"",},minval={0,},maxval={0,},text={"",},},},
[4] = {4,"","","item_goto_4.button_show","","",{key={"",},minval={0,},maxval={0,},text={"",},},},
[5] = {5,"","","item_goto_5.button_show","","",{key={"",},minval={0,},maxval={0,},text={"",},},},
[6] = {6,"","","item_goto_6.button_show","","",{key={"",},minval={0,},maxval={0,},text={"",},},},
[7] = {7,"","","item_goto_7.button_show","","",{key={"",},minval={0,},maxval={0,},text={"",},},},

}
