
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"guild_lv","enter_cost","win_guild","lose_guild","reward","win_reward","lose_reward","part_reward",},
[1] = {1,20000,320000,160000,{id={1000,6,2,},},{basetype="guild_carriage",item={id={4,2,6,},num={10000,1000,480,},},},{basetype="guild_carriage",item={id={4,2,6,},num={5000,500,240,},},},{flag_reward={4003,},},},
[2] = {2,20000,480000,240000,{id={1000,6,2,},},{basetype="guild_carriage",item={id={4,2,6,},num={10000,1000,480,},},},{basetype="guild_carriage",item={id={4,2,6,},num={5000,500,240,},},},{flag_reward={4003,},},},
[3] = {3,20000,560000,240000,{id={1000,6,2,},},{basetype="guild_carriage",item={id={4,2,6,},num={10000,1000,480,},},},{basetype="guild_carriage",item={id={4,2,6,},num={5000,500,240,},},},{flag_reward={4003,},},},
[4] = {4,20000,720000,320000,{id={1000,6,2,},},{basetype="guild_carriage",item={id={4,2,6,},num={10000,1000,480,},},},{basetype="guild_carriage",item={id={4,2,6,},num={5000,500,240,},},},{flag_reward={4003,},},},
[5] = {5,20000,800000,400000,{id={1000,6,2,},},{basetype="guild_carriage",item={id={4,2,6,},num={10000,1000,480,},},},{basetype="guild_carriage",item={id={4,2,6,},num={5000,500,240,},},},{flag_reward={4003,},},},
[6] = {6,20000,880000,480000,{id={1000,6,2,},},{basetype="guild_carriage",item={id={4,2,6,},num={10000,1000,480,},},},{basetype="guild_carriage",item={id={4,2,6,},num={5000,500,240,},},},{flag_reward={4003,},},},
[7] = {7,20000,960000,560000,{id={1000,6,2,},},{basetype="guild_carriage",item={id={4,2,6,},num={10000,1000,480,},},},{basetype="guild_carriage",item={id={4,2,6,},num={5000,500,240,},},},{flag_reward={4003,},},},

}
