
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","type","lbtext","reward","show","show_model","pos_xy","zoom","rotate","show_pic","server_variate","server_variate_num","server_variate_text","require",},
[40001] = {40001,4,1,"garment_40001.lbtext",{reward_id="8401",flag_reward={8041,},},{item={3,3,1,1200,1500,},itemnum={1,1000,100000,50,40,},},"","0,0","100",0,"#dynamic/TL_business/output/TL_business.xml|TL_business|33","GarmentGetNum4001",500,"garment_40001.server_variate_text",{key={"pGarment",},minval={200,},maxval={0,},text={"garment_40001.require.text[1]",},},},
[40002] = {40002,4,1,"garment_40002.lbtext",{reward_id="8402",flag_reward={8041,},},{item={3305,3305,1,1400,1902,},itemnum={1,1,200000,50,1980,},},"/res/effect/ef_show_partner_liyuan.assetbundles","0,0","100",0,"","GarmentGetNum4002",300,"garment_40002.server_variate_text",{key={"pGarment",},minval={400,},maxval={0,},text={"garment_40002.require.text[1]",},},},
[40003] = {40003,4,1,"garment_40003.lbtext",{reward_id="8403",flag_reward={8041,},},{item={3,3,1,1700,1202,},itemnum={1,2000,300000,50,100,},},"","0,0","100",0,"#dynamic/TL_business/output/TL_business.xml|TL_business|33","GarmentGetNum4003",100,"garment_40003.server_variate_text",{key={"pGarment",},minval={600,},maxval={0,},text={"garment_40003.require.text[1]",},},},
[40004] = {40004,4,1,"garment_40004.lbtext",{reward_id="8404",flag_reward={8041,},},{item={3502,3502,3,1,7015,},itemnum={1,1,3000,1000000,10,},},"/res/effect/item/ef_item_god_03.assetbundles","0,50","250",180,"","GarmentGetNum4004",30,"garment_40004.server_variate_text",{key={"pGarment",},minval={800,},maxval={0,},text={"garment_40004.require.text[1]",},},},
[40005] = {40005,4,1,"garment_40005.lbtext",{reward_id="8405",flag_reward={8041,},},{item={3,3,1201,1202,0,},itemnum={1,5000,50,300,0,},},"","0,0","100",0,"#dynamic/TL_business/output/TL_business.xml|TL_business|33","GarmentGetNum4005",10,"garment_40005.server_variate_text",{key={"pGarment",},minval={1000,},maxval={0,},text={"garment_40005.require.text[1]",},},},
[40006] = {40006,4,1,"garment_40006.lbtext",{reward_id="8406",flag_reward={8041,},},{item={3503,3503,1,7016,0,},itemnum={1,1,1000000,10,0,},},"/res/effect/item/ef_item_god_04.assetbundles","0,50","250",180,"","GarmentGetNum4006",5,"garment_40006.server_variate_text",{key={"pGarment",},minval={1200,},maxval={0,},text={"garment_40006.require.text[1]",},},},

}
