
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","item_id","item_name","item_exp","item_effect","effect_type",},
[1] = {1,5037,"item_relationship_1.item_name",20,"",0,},
[2] = {2,5038,"item_relationship_2.item_name",199,"/res/effect/ui/EF_UI_Flowers01.assetbundles",1,},
[3] = {3,5039,"item_relationship_3.item_name",1999,"/res/effect/ui/EF_UI_Flowers02.assetbundles",2,},

}
