
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","order_name","scenes_type","order_position_left","order_position_right","map_id",},
[1] = {1,"guild_fort_order_1.order_name",1,"bdr11","bdr21",502000,},
[2] = {2,"guild_fort_order_2.order_name",1,"bdr12","bdr22",502000,},
[3] = {3,"guild_fort_order_3.order_name",1,"bdr13","bdr23",502000,},
[4] = {4,"guild_fort_order_4.order_name",1,"bdr14","bdr24",502000,},
[5] = {5,"guild_fort_order_5.order_name",1,"bdr15","bdr25",502000,},
[6] = {6,"guild_fort_order_6.order_name",1,"bdr16","bdr26",502000,},
[7] = {7,"guild_fort_order_7.order_name",2,"bdr1","bdr1",502001,},
[8] = {8,"guild_fort_order_8.order_name",2,"bdr2","bdr2",502001,},
[9] = {9,"guild_fort_order_9.order_name",2,"bdr5","bdr5",502001,},
[10] = {10,"guild_fort_order_10.order_name",2,"bdr4","bdr4",502001,},
[11] = {11,"guild_fort_order_11.order_name",2,"bdr3","bdr3",502001,},

}
