
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","fort_name","fort_type","fort_des","fort_cost","fort_giftbox","reward","emailreward","part_reward",},
[1] = {1,"guild_fort_reward_1.fort_name",1,"guild_fort_reward_1.fort_des",20000,5005,{id={2,200066,1800,0,0,},num={500,60,300,0,0,},item={id={1201,1202,1600,1601,1602,},num={10,20,20,20,30,},},},50001,{flag_reward={4004,},},},
[2] = {2,"guild_fort_reward_2.fort_name",2,"guild_fort_reward_2.fort_des",20000,5005,{id={2,200066,1800,0,0,},num={300,30,200,0,0,},item={id={1201,1202,1600,1601,1602,},num={5,10,10,10,10,},},},50002,{flag_reward={4004,},},},
[3] = {3,"guild_fort_reward_3.fort_name",2,"guild_fort_reward_3.fort_des",20000,5005,{id={2,200066,1800,0,0,},num={300,30,200,0,0,},item={id={1201,1202,1600,1601,1602,},num={5,10,10,10,10,},},},50003,{flag_reward={4004,},},},

}
