
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","mapid","npcid","planes","npcflag","inner","innerevent","innerevent_time","center","outer","outerevent","outerevent_time","point","pointevent","next_event","success","fail","auto_move",},
[1] = {1,220010,30069,1,"xl_genzongld1",1,"message.1",5,8,80,"message.2",10,{"xl_genzongld2","xl_genzongld3","xl_genzongld4",},{"client.Stalker/stalker_1","client.Stalker/stalker_1","client.Stalker/stalker_2",},"",{id={"",},},{id={"",},},0,},

}
