
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","suit_id","suit_num","suit_name","suit_attr","suit_buff",},
[1] = {1,1,2,"equip_suit_1.suit_name","","",},
[2] = {2,1,4,"equip_suit_2.suit_name","","",},
[3] = {3,1,6,"equip_suit_3.suit_name","","",},

}
