
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","name","item_type","sec_type","quality","item_turn","max_stacked","adscription_tab","effective_time","level_limit","using_desc","atlas_id","desc","price","can_mission","can_instore","can_compose","source","hint","can_decompose","can_trade","editor_item_template","quality_effect","sec_name",},
[1001] = {1001,"quest_item_1001.name",0,0,1,400,999,0,0,1,"quest_item_1001.using_desc","static/item/8.png","quest_item_1001.desc",0,1,0,0,"0",0,0,0,0,0,"",},
[1002] = {1002,"quest_item_1002.name",0,0,1,401,999,0,0,1,"quest_item_1002.using_desc","static/item/9.png","quest_item_1002.desc",0,1,0,0,"0",0,0,0,0,0,"",},
[1003] = {1003,"quest_item_1003.name",0,0,1,402,999,0,0,1,"quest_item_1003.using_desc","static/item/20.png","quest_item_1003.desc",0,1,0,0,"0",0,0,0,0,0,"",},
[1004] = {1004,"quest_item_1004.name",0,0,1,403,999,0,0,1,"quest_item_1004.using_desc","static/item/2.png","quest_item_1004.desc",0,1,0,0,"0",0,0,0,0,0,"",},
[1005] = {1005,"quest_item_1005.name",0,0,1,405,999,0,0,1,"quest_item_1005.using_desc","static/item/zsd3.png","quest_item_1005.desc",0,1,0,0,"0",0,0,0,0,0,"",},
[1006] = {1006,"quest_item_1006.name",0,0,1,406,999,0,0,1,"quest_item_1006.using_desc","static/item/2.png","quest_item_1006.desc",0,1,0,0,"0",0,0,0,0,0,"",},
[1007] = {1007,"quest_item_1007.name",0,0,1,407,999,0,0,1,"quest_item_1007.using_desc","static/item/2.png","quest_item_1007.desc",0,1,0,0,"0",0,0,0,0,0,"",},
[1008] = {1008,"quest_item_1008.name",0,0,1,408,999,0,0,1,"quest_item_1008.using_desc","static/item/zsd3.png","quest_item_1008.desc",0,1,0,0,"0",0,0,0,0,0,"",},

}
