
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","type","lbtext","order","show_pic","require","reward","show",},
[13001] = {13001,13001,0,"cost_13001.lbtext",1,"",{key={"fcsotCount13001",},minval={1000,},maxval={-1,},text={"cost_13001.require.text[1]",},},{item={id={7024,1,1200,2,},num={3,50000,40,200,},},},{item={7024,1,1200,2,},itemnum={3,50000,40,200,},},},
[13002] = {13002,13001,0,"cost_13002.lbtext",2,"",{key={"fcsotCount13001",},minval={3000,},maxval={-1,},text={"cost_13002.require.text[1]",},},{item={id={7025,1,1500,2,},num={3,100000,100,400,},},},{item={7025,1,1500,2,},itemnum={3,100000,100,400,},},},
[13003] = {13003,13001,0,"cost_13003.lbtext",3,"",{key={"fcsotCount13001",},minval={8000,},maxval={-1,},text={"cost_13003.require.text[1]",},},{item={id={7015,1,1202,2,},num={3,200000,120,1000,},},},{item={7015,1,1202,2,},itemnum={3,200000,120,1000,},},},
[13004] = {13004,13001,0,"cost_13004.lbtext",4,"",{key={"fcsotCount13001",},minval={15000,},maxval={-1,},text={"cost_13004.require.text[1]",},},{item={id={7027,1,1600,2,},num={50,300000,160,1500,},},},{item={7027,1,1600,2,},itemnum={50,300000,160,1500,},},},
[13005] = {13005,13001,0,"cost_13005.lbtext",5,"",{key={"fcsotCount13001",},minval={20000,},maxval={-1,},text={"cost_13005.require.text[1]",},},{item={id={5035,1,1201,2,},num={1,400000,200,2000,},},},{item={5035,1,1201,2,},itemnum={1,400000,200,2000,},},},
[13006] = {13006,13001,0,"cost_13006.lbtext",6,"",{key={"fcsotCount13001",},minval={40000,},maxval={-1,},text={"cost_13006.require.text[1]",},},{item={id={3500,1,1700,2,},num={1,500000,400,3000,},},},{item={3500,1,1700,2,},itemnum={1,500000,400,3000,},},},

}
