
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","type","lbtext","order","show_pic","require","reward","show",},
[14001] = {14001,14001,3,"daily_cost_14001.lbtext",1,"",{key={"ddailycostCount14001",},minval={200,},maxval={-1,},text={"daily_cost_14001.require.text[1]",},},{item={id={7024,2,1,6004,},num={1,100,20000,2,},},},{item={7024,2,1,6004,},itemnum={1,100,20000,2,},},},
[14002] = {14002,14001,3,"daily_cost_14002.lbtext",2,"",{key={"ddailycostCount14001",},minval={500,},maxval={-1,},text={"daily_cost_14002.require.text[1]",},},{item={id={7025,2,1,6004,},num={1,200,50000,5,},},},{item={7025,2,1,6004,},itemnum={1,200,50000,5,},},},
[14003] = {14003,14001,3,"daily_cost_14003.lbtext",3,"",{key={"ddailycostCount14001",},minval={1000,},maxval={-1,},text={"daily_cost_14003.require.text[1]",},},{item={id={7025,2,1,6004,},num={2,500,100000,10,},},},{item={7025,2,1,6004,},itemnum={2,500,100000,10,},},},
[14004] = {14004,14001,3,"daily_cost_14004.lbtext",4,"",{key={"ddailycostCount14001",},minval={2500,},maxval={-1,},text={"daily_cost_14004.require.text[1]",},},{item={id={7015,2,1,6004,},num={1,1000,150000,20,},},},{item={7015,2,1,6004,},itemnum={1,1000,150000,20,},},},
[14005] = {14005,14001,3,"daily_cost_14005.lbtext",5,"",{key={"ddailycostCount14001",},minval={5000,},maxval={-1,},text={"daily_cost_14005.require.text[1]",},},{item={id={7015,2,1,6004,},num={2,2000,200000,30,},},},{item={7015,2,1,6004,},itemnum={2,2000,200000,30,},},},
[14006] = {14006,14001,3,"daily_cost_14006.lbtext",6,"",{key={"ddailycostCount14001",},minval={10000,},maxval={-1,},text={"daily_cost_14006.require.text[1]",},},{item={id={7017,2,1,6004,},num={1,3000,250000,50,},},},{item={7017,2,1,6004,},itemnum={1,3000,250000,50,},},},

}
