
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","type","lbtext","order","show_pic","require","reward","show",},
[12001] = {12001,12001,3,"daily_pay_12001.lbtext",1,"",{key={"ddailypayCount12001",},minval={60,},maxval={-1,},text={"daily_pay_12001.require.text[1]",},},{item={id={7025,1200,1400,1500,},num={3,100,60,50,},},},{item={7025,1200,1400,1500,},itemnum={3,100,60,50,},},},
[12002] = {12002,12001,3,"daily_pay_12002.lbtext",2,"",{key={"ddailypayCount12001",},minval={300,},maxval={-1,},text={"daily_pay_12002.require.text[1]",},},{item={id={2,1201,1202,1600,},num={8000,20,200,40,},},},{item={2,1201,1202,1600,},itemnum={8000,20,200,40,},},},
[12003] = {12003,12001,3,"daily_pay_12003.lbtext",3,"",{key={"ddailypayCount12001",},minval={500,},maxval={-1,},text={"daily_pay_12003.require.text[1]",},},{item={id={2,1203,7027,1500,},num={40000,30,50,80,},},},{item={2,1203,7027,1500,},itemnum={40000,30,50,80,},},},
[12004] = {12004,12001,3,"daily_pay_12004.lbtext",4,"",{key={"ddailypayCount12001",},minval={600,},maxval={-1,},text={"daily_pay_12004.require.text[1]",},},{item={id={5033,1201,1400,1500,},num={1,50,200,130,},},},{item={5033,1201,1400,1500,},itemnum={1,50,200,130,},},},
[12005] = {12005,12001,3,"daily_pay_12005.lbtext",5,"",{key={"ddailypayCount12001",},minval={1000,},maxval={-1,},text={"daily_pay_12005.require.text[1]",},},{item={id={2,7027,7026,1700,},num={100000,100,50,100,},},},{item={2,7027,7026,1700,},itemnum={100000,100,50,100,},},},
[12006] = {12006,12001,3,"daily_pay_12006.lbtext",6,"",{key={"ddailypayCount12001",},minval={2000,},maxval={-1,},text={"daily_pay_12006.require.text[1]",},},{item={id={3500,1201,1203,1600,},num={1,100,60,240,},},},{item={3500,1201,1203,1600,},itemnum={1,100,60,240,},},},

}
