
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","ib_icon","cvs_item","lb_name","time",},
[1] = {1,"static/item/rw01.png","#dynamic/TL_tips/output/TL_tips.xml|TL_tips|8","itemshow_1.lb_name",2000,},
[2] = {2,"static/item/1900.png","#dynamic/TL_tips/output/TL_tips.xml|TL_tips|8","itemshow_2.lb_name",2000,},

}
