
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","max_times","flag","require","cost_id","reward",},
[1] = {1,3,"SFPraynum",{key={"dSFPraynum","costitem",},minval={0,1,},maxval={2,-1,},text={"pray_1.require.text[1]","pray_1.require.text[2]",},},1200,{type="common_reward",reward_id={3001,},},},

}
