
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","require","cost_id","reward","maxtime",},
[1] = {1,{key={"dPraynum","costitem",},minval={0,1,},maxval={2,-1,},text={"turntable_1.require.text[1]","turntable_1.require.text[2]",},},1200,{type="common_reward",reward_id={3001,},flag_reward={16001,},},3,},

}
