
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_go","Title","des","cancelBtn","okBtn","okBtnGoto",},
[1] = {1,"goshop1","goto_1.Title","goto_1.des","goto_1.cancelBtn","goto_1.okBtn","shop_100",},
[2] = {2,"goshop2","goto_2.Title","goto_2.des","goto_2.cancelBtn","goto_2.okBtn","shop_101",},

}
