
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","costgroup","cost","success","lb_title","lb_cost","lb_reward","ui_template","show",},
[20003] = {20003,{id={0,},num={0,},},{id={3,},num={10,},},{id={"reward.20003",},},"cost_20003.lb_title","cost_20003.lb_cost","cost_20003.lb_reward","xml/common/common_cost.gui.xml",{item={2,5016,7000,7001,},},},
[22027] = {22027,{id={0,},num={0,},},{id={7178,},num={1,},},{id={"group.20000",},},"cost_22027.lb_title","cost_22027.lb_cost","cost_22027.lb_reward","xml/common/common_cost2.gui.xml",{item={7187,7188,5037,7028,},},},
[22028] = {22028,{id={0,},num={0,},},{id={7178,},num={1,},},{id={"group.20001",},},"cost_22028.lb_title","cost_22028.lb_cost","cost_22028.lb_reward","xml/common/common_cost2.gui.xml",{item={7187,7188,5037,7028,},},},
[22029] = {22029,{id={0,},num={0,},},{id={7178,},num={1,},},{id={"group.20002",},},"cost_22029.lb_title","cost_22029.lb_cost","cost_22029.lb_reward","xml/common/common_cost2.gui.xml",{item={7187,7188,5037,7028,},},},
[22030] = {22030,{id={0,},num={0,},},{id={7178,},num={1,},},{id={"group.20003",},},"cost_22030.lb_title","cost_22030.lb_cost","cost_22030.lb_reward","xml/common/common_cost2.gui.xml",{item={7187,7188,5037,7028,},},},

}
