
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","destroy_limit","carriage_speeddown","carriage_hpdown","animal_propdown","animal_hpdown","buff_id",},
[1] = {1,50,10,100,0,0,2,},
[2] = {2,50,0,0,100,20,11,},

}
