
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","count","transverse","longitudinal","card","continue","next_event","success","fail",},
[1] = {1,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"",},},{id={"",},},},
[2] = {2,1,2,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","","",},{1,0,0,0,0,},"",{id={"",},},{id={"",},},},
[3] = {3,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22001",},},{id={"",},},},
[4] = {4,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22002",},},{id={"",},},},
[5] = {5,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22003",},},{id={"",},},},
[6] = {6,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22003",},},{id={"",},},},
[7] = {7,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22003",},},{id={"",},},},
[8] = {8,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22003",},},{id={"",},},},
[9] = {9,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22003",},},{id={"",},},},
[10] = {10,1,3,2,{"#dynamic/TL_card/output/TL_card.xml|TL_card|1","#dynamic/TL_card/output/TL_card.xml|TL_card|2","#dynamic/TL_card/output/TL_card.xml|TL_card|2","","",},{1,0,0,0,0,},"",{id={"reward.22003",},},{id={"",},},},

}
