
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","sheet_name","limit_time","open_time","goto_functions",},
[1] = {1,1,"",1,"onlinetip1","shop_103",},
[2] = {2,2,"",1,"onlinetip2","shop_103",},
[3] = {3,3,"",1,"onlinetip3","shop_103",},
[4] = {4,4,"",1,"onlinetip4","partner",},
[5] = {5,5,"",0,"onlinetip5","socialrelation",},

}
