---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/12/25 17:56
---双飞塔结算

local _M = {}
_M.__index = _M


local UIUtil = require 'UI/UIUtil'
local ItemModel = require 'Model/ItemModel'


function _M.OnInit(self)
    
end

--结算界面掉落列表
local function SetDropList(self,params,node,index)
    local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(params[index].TemplateID))
    local num =params[index].Qty
    local itshow=UIUtil.SetItemShowTo(node,itemdetail,num)
    itshow.EnableTouch = true
    itshow.TouchClick = function()
        SoundManager.Instance:PlaySoundByKey('button',false)
        UIUtil.ShowNormalItemDetail({x=node.X+290,y=node.Y+35,detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
    end
end

local function ShowDamage(self)
    self.comps.cvs_type1.Visible=false
    self.comps.cvs_type2.Visible=false
    local temp = TLBattleScene.Instance:GetScenePlayerDamageMap()
    temp = CSharpMap2Table(temp)
    local total=0
    local dps = 0
    for k, v in pairs(temp) do
        total = total + v
        local player = GameSceneMgr.Instance.BattleScene:GetBattleObject(k)
        if player then
            if player:Name() == DataMgr.Instance.UserData.Name then
                dps = v
                self.comps.cvs_type2.Visible=true
            end
        end
    end
    self.comps.lb_damage.Text = dps
    self.comps.lb_ratio1.Text =string.format("%.1f", dps/total*100)..'%'
end

function _M.OnEnter(self,params)
    
    self.comps.lb_passnum.Text = params.extramap.passlayer
    self.comps.cvs_dpitem.Visible=false

    ShowDamage(self)
    
    --如果有掉落，设置掉落列表
    if not params.noAward then
        self.comps.lb_none.Visible=false
        self.comps.cvs_itemlist.Visible =true
        local drop = params.itemList
        --设置掉落列表
        local function SetDrop(node,index)
            SetDropList(self,drop,node,index)
        end
        UIUtil.ConfigHScrollPan(self.comps.sp_drops,self.comps.cvs_dpitem,#drop,SetDrop)
    else
        self.comps.lb_none.Visible=true
        self.comps.cvs_itemlist.Visible =false
    end
end


function _M.OnExit(self)
    
end


return _M