
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","is_show","group","group_name","sub","sub_name","key","val","type","count",},
[1] = {1,1,1,"ranklist_1.group_name",1,"ranklist_1.sub_name",{"ranklist_1.key[1]","ranklist_1.key[2]","ranklist_1.key[3]","ranklist_1.key[4]","ranklist_1.key[5]",},{"rank","playername","playerjob","playerguild","plevelall",},"bigfirst",100,},
[2] = {2,0,1,"ranklist_2.group_name",5,"ranklist_2.sub_name",{"ranklist_2.key[1]","ranklist_2.key[2]","ranklist_2.key[3]","ranklist_2.key[4]","ranklist_2.key[5]",},{"rank","playername","playerjob","playerguild","plevelyizu",},"bigfirst",100,},
[3] = {3,1,1,"ranklist_3.group_name",2,"ranklist_3.sub_name",{"ranklist_3.key[1]","ranklist_3.key[2]","ranklist_3.key[3]","ranklist_3.key[4]","ranklist_3.key[5]",},{"rank","playername","playerjob","playerguild","pleveltiangong",},"bigfirst",100,},
[4] = {4,1,1,"ranklist_4.group_name",3,"ranklist_4.sub_name",{"ranklist_4.key[1]","ranklist_4.key[2]","ranklist_4.key[3]","ranklist_4.key[4]","ranklist_4.key[5]",},{"rank","playername","playerjob","playerguild","plevelkunlun",},"bigfirst",100,},
[5] = {5,1,1,"ranklist_5.group_name",4,"ranklist_5.sub_name",{"ranklist_5.key[1]","ranklist_5.key[2]","ranklist_5.key[3]","ranklist_5.key[4]","ranklist_5.key[5]",},{"rank","playername","playerjob","playerguild","plevelqingqiu",},"bigfirst",100,},
[6] = {6,1,2,"ranklist_6.group_name",1,"ranklist_6.sub_name",{"ranklist_6.key[1]","ranklist_6.key[2]","ranklist_6.key[3]","ranklist_6.key[4]","ranklist_6.key[5]",},{"rank","playername","playerjob","practice","pbattleall",},"bigfirst",100,},
[7] = {7,0,2,"ranklist_7.group_name",5,"ranklist_7.sub_name",{"ranklist_7.key[1]","ranklist_7.key[2]","ranklist_7.key[3]","ranklist_7.key[4]","ranklist_7.key[5]",},{"rank","playername","playerjob","practice","pbattleyizu",},"bigfirst",100,},
[8] = {8,1,2,"ranklist_8.group_name",2,"ranklist_8.sub_name",{"ranklist_8.key[1]","ranklist_8.key[2]","ranklist_8.key[3]","ranklist_8.key[4]","ranklist_8.key[5]",},{"rank","playername","playerjob","practice","pbattletiangong",},"bigfirst",100,},
[9] = {9,1,2,"ranklist_9.group_name",3,"ranklist_9.sub_name",{"ranklist_9.key[1]","ranklist_9.key[2]","ranklist_9.key[3]","ranklist_9.key[4]","ranklist_9.key[5]",},{"rank","playername","playerjob","practice","pbattlekunlun",},"bigfirst",100,},
[10] = {10,1,2,"ranklist_10.group_name",4,"ranklist_10.sub_name",{"ranklist_10.key[1]","ranklist_10.key[2]","ranklist_10.key[3]","ranklist_10.key[4]","ranklist_10.key[5]",},{"rank","playername","playerjob","practice","pbattleqingqiu",},"bigfirst",100,},
[11] = {11,1,3,"ranklist_11.group_name",1,"ranklist_11.sub_name",{"ranklist_11.key[1]","ranklist_11.key[2]","ranklist_11.key[3]","ranklist_11.key[4]","ranklist_11.key[5]",},{"rank","playername","playerjob","playerguild","backbattle",},"bigfirst",100,},
[12] = {12,1,3,"ranklist_12.group_name",2,"ranklist_12.sub_name",{"ranklist_12.key[1]","ranklist_12.key[2]","ranklist_12.key[3]","ranklist_12.key[4]","ranklist_12.key[5]",},{"rank","playername","playerjob","playerguild","godbattle",},"bigfirst",100,},
[13] = {13,1,3,"ranklist_13.group_name",3,"ranklist_13.sub_name",{"ranklist_13.key[1]","ranklist_13.key[2]","ranklist_13.key[3]","ranklist_13.key[4]","ranklist_13.key[5]",},{"rank","playername","playerjob","playerguild","petbattle",},"bigfirst",100,},
[14] = {14,1,3,"ranklist_14.group_name",4,"ranklist_14.sub_name",{"ranklist_14.key[1]","ranklist_14.key[2]","ranklist_14.key[3]","ranklist_14.key[4]","ranklist_14.key[5]",},{"rank","playername","playerjob","playerguild","mountbattle",},"bigfirst",100,},
[15] = {15,0,4,"ranklist_15.group_name",1,"ranklist_15.sub_name",{"ranklist_15.key[1]","ranklist_15.key[2]","ranklist_15.key[3]","ranklist_15.key[4]","ranklist_15.key[5]",},{"rank","playername","playerjob","playerguild","dresspoint",},"bigfirst",100,},
[16] = {16,1,5,"ranklist_16.group_name",1,"ranklist_16.sub_name",{"ranklist_16.key[1]","ranklist_16.key[2]","ranklist_16.key[3]","ranklist_16.key[4]","ranklist_16.key[5]",},{"rank","playername","playerjob","playerguild","finishfloor",},"bigfirst",50,},
[17] = {17,1,6,"ranklist_17.group_name",1,"ranklist_17.sub_name",{"ranklist_17.key[1]","ranklist_17.key[2]","ranklist_17.key[3]","ranklist_17.key[4]","ranklist_17.key[5]",},{"rank","playername","playerjob","playerguild","coin",},"bigfirst",50,},
[18] = {18,1,6,"ranklist_18.group_name",2,"ranklist_18.sub_name",{"ranklist_18.key[1]","ranklist_18.key[2]","ranklist_18.key[3]","ranklist_18.key[4]","ranklist_18.key[5]",},{"rank","playername","playerjob","playerguild","money",},"bigfirst",50,},
[19] = {19,1,7,"ranklist_19.group_name",1,"ranklist_19.sub_name",{"ranklist_19.key[1]","ranklist_19.key[2]","ranklist_19.key[3]","ranklist_19.key[4]","ranklist_19.key[5]",},{"rank","guildname","guildnum","guildlevel","guildbattle",},"bigfirst",50,},

}
