
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","artifact_stage","artifact_name","reward","group_id","body_model","head_model","requireid","quality","chat_icon","notice_id","first_notice_id",},
[1] = {1,1,"practice_1.artifact_name",{id={1200,2200,},num={1,1,},},1,"player01","kong","",1,"#static/TL_hud/output/TL_hud.xml|TL_hud|204",0,0,},
[2] = {2,2,"practice_2.artifact_name",{id={1200,2200,},num={1,1,},},2,"player01","kong","",1,"#static/TL_hud/output/TL_hud.xml|TL_hud|203",0,0,},
[3] = {3,3,"practice_3.artifact_name",{id={1200,2200,},num={1,1,},},3,"player01","kong","9000",2,"#static/TL_hud/output/TL_hud.xml|TL_hud|202",0,0,},
[4] = {4,4,"practice_4.artifact_name",{id={1200,2200,},num={1,1,},},4,"player01","kong","9001",2,"#static/TL_hud/output/TL_hud.xml|TL_hud|201",0,135,},
[5] = {5,5,"practice_5.artifact_name",{id={1200,2200,},num={1,1,},},5,"player01","kong","9002",3,"#static/TL_hud/output/TL_hud.xml|TL_hud|205",0,136,},
[6] = {6,6,"practice_6.artifact_name",{id={1200,2200,},num={1,1,},},6,"player01","kong","9003",3,"#static/TL_hud/output/TL_hud.xml|TL_hud|206",133,136,},
[7] = {7,7,"practice_7.artifact_name",{id={1200,2200,},num={1,1,},},7,"player01","kong","9004",4,"#static/TL_hud/output/TL_hud.xml|TL_hud|208",134,137,},
[8] = {8,8,"practice_8.artifact_name",{id={1200,2200,},num={1,1,},},8,"player01","kong","9005",4,"#static/TL_hud/output/TL_hud.xml|TL_hud|212",134,137,},
[9] = {9,9,"practice_9.artifact_name",{id={1200,2200,},num={1,1,},},9,"player01","kong","9006",4,"#static/TL_hud/output/TL_hud.xml|TL_hud|213",134,137,},

}
