
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","lv_max","skill_lv_max","talent_point",},
[1] = {1,20,1,5,},
[2] = {2,40,2,10,},
[3] = {3,60,3,15,},
[4] = {4,80,3,20,},
[5] = {5,100,3,25,},

}
