
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","talent_type","talent_name","reset_cost","talent_icon",},
[1] = {1,1,"skill_talent_type_1.talent_name","{2,100}","",},
[2] = {2,2,"skill_talent_type_2.talent_name","{2,100}","",},

}
