
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","win_score","red_flagid","blue_flagid","neutral_flagid","neutral_flag","kill_score","small_resource","big_resource","monster","red_item","blue_item","red_transfer","blue_transfer",},
[1] = {1,3000,25008,25007,25009,"neutral_flag",40,3,6,{id={25003,25004,25005,25006,},flag={"shengshou1","shengshou2","shengshou3","shengshou4",},},"item_pub.50000001","item_pub.50000002","r_transfer_point","b_transfer_point",},
[2] = {2,3000,25018,25017,25019,"neutral_flag",40,3,6,{id={25013,25014,25015,25016,},flag={"shengshou1","shengshou2","shengshou3","shengshou4",},},"item_pub.50000011","item_pub.50000012","r_transfer_point","b_transfer_point",},
[3] = {3,3000,25028,25027,25029,"neutral_flag",40,3,6,{id={25023,25024,25025,25026,},flag={"shengshou1","shengshou2","shengshou3","shengshou4",},},"item_pub.50000021","item_pub.50000022","r_transfer_point","b_transfer_point",},

}
