
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_id","air_flag","air_flag_time","win_score","battlefield_time","player_ready_event","kill_people_score","kill_people_event","people_dead_event","offline_event",},
[1] = {1,"pvp_duoqi",{"r_airwall1","b_airwall1","","",},15,1000,300,"client.pvp_teamhud",10,"message.183","","",},
[2] = {2,"pvp_qinglong",{"airwall1","airwall2","airwall3","airwall4",},15,9999,180,"client.pvp_singlehud",10,"message.183","","",},
[3] = {3,"pvp_longshen",{"","","","",},15,9999,180,"client.pvp_singlehud",10,"message.183","","",},

}
