
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","interbehavior",},
[1] = {1,{"menu_button_1.interbehavior[1]","menu_button_1.interbehavior[2]",},},
[2] = {2,{"menu_button_2.interbehavior[1]","menu_button_2.interbehavior[2]",},},
[3] = {3,{"menu_button_3.interbehavior[1]","menu_button_3.interbehavior[2]",},},
[4] = {4,{"menu_button_4.interbehavior[1]","menu_button_4.interbehavior[2]",},},
[5] = {5,{"menu_button_5.interbehavior[1]","menu_button_5.interbehavior[2]",},},
[6] = {6,{"menu_button_6.interbehavior[1]","menu_button_6.interbehavior[2]",},},
[7] = {7,{"menu_button_7.interbehavior[1]","menu_button_7.interbehavior[2]",},},
[8] = {8,{"menu_button_8.interbehavior[1]","menu_button_8.interbehavior[2]",},},
[9] = {9,{"menu_button_9.interbehavior[1]","menu_button_9.interbehavior[2]",},},
[10] = {10,{"menu_button_10.interbehavior[1]","menu_button_10.interbehavior[2]",},},
[11] = {11,{"menu_button_11.interbehavior[1]","menu_button_11.interbehavior[2]",},},
[12] = {12,{"menu_button_12.interbehavior[1]","menu_button_12.interbehavior[2]",},},
[13] = {13,{"menu_button_13.interbehavior[1]","menu_button_13.interbehavior[2]",},},
[14] = {14,{"menu_button_14.interbehavior[1]","menu_button_14.interbehavior[2]",},},
[15] = {15,{"menu_button_15.interbehavior[1]","menu_button_15.interbehavior[2]",},},
[16] = {16,{"menu_button_16.interbehavior[1]","menu_button_16.interbehavior[2]",},},
[17] = {17,{"menu_button_17.interbehavior[1]","menu_button_17.interbehavior[2]",},},
[18] = {18,{"menu_button_18.interbehavior[1]","menu_button_18.interbehavior[2]",},},
[19] = {19,{"menu_button_19.interbehavior[1]","menu_button_19.interbehavior[2]",},},
[20] = {20,{"menu_button_20.interbehavior[1]","menu_button_20.interbehavior[2]",},},
[21] = {21,{"menu_button_21.interbehavior[1]","menu_button_21.interbehavior[2]",},},
[22] = {22,{"menu_button_22.interbehavior[1]","menu_button_22.interbehavior[2]",},},
[23] = {23,{"menu_button_23.interbehavior[1]","menu_button_23.interbehavior[2]",},},
[24] = {24,{"menu_button_24.interbehavior[1]","menu_button_24.interbehavior[2]",},},
[25] = {25,{"menu_button_25.interbehavior[1]","menu_button_25.interbehavior[2]",},},
[26] = {26,{"menu_button_26.interbehavior[1]","menu_button_26.interbehavior[2]",},},

}
