
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","is_selling","store_type","name","show_price","show_cost","order","exp_vip","accumulative_count","reward","require","reset_time","limit_num","recharge_event",},
[4001] = {4001,0,3,"仙寶禮包","150","180",1,150,150,{item={id={7020,7026,7054,6004,},num={2,2,1,1,},},flag_reward={10411,},},{key={"mrecharge_month1",},minval={0,},maxval={9,},text={"daily_recharge_4001.require.text[1]",},},3,10,{"",},},
[4002] = {4002,0,3,"仙魄禮包","490","588",2,490,490,{item={id={7020,1400,7054,6004,},num={4,300,1,3,},},flag_reward={10412,},},{key={"mrecharge_month2",},minval={0,},maxval={9,},text={"daily_recharge_4002.require.text[1]",},},3,10,{"",},},
[4003] = {4003,0,3,"緣分禮包","490","666",3,490,490,{item={id={3,7020,7054,6004,},num={1000,2,1,3,},},flag_reward={10413,},},{key={"mrecharge_month3",},minval={0,},maxval={9,},text={"daily_recharge_4003.require.text[1]",},},3,10,{"",},},
[4004] = {4004,0,3,"仙侶禮包","1490","1990",4,1490,1490,{item={id={3,7020,7054,6004,},num={2990,6,2,10,},},flag_reward={10414,},},{key={"mrecharge_month4",},minval={0,},maxval={9,},text={"daily_recharge_4004.require.text[1]",},},3,10,{"",},},
[4005] = {4005,0,3,"仙寶禮包","150","180",1,150,150,{item={id={7020,7026,7054,6004,},num={2,2,1,1,},},flag_reward={10411,},},{key={"mrecharge_month1",},minval={0,},maxval={9,},text={"daily_recharge_4005.require.text[1]",},},3,10,{"",},},
[4006] = {4006,0,3,"仙魄禮包","490","588",2,490,490,{item={id={7020,1400,7054,6004,},num={4,300,1,3,},},flag_reward={10412,},},{key={"mrecharge_month2",},minval={0,},maxval={9,},text={"daily_recharge_4006.require.text[1]",},},3,10,{"",},},
[4007] = {4007,0,3,"緣分禮包","490","666",3,490,490,{item={id={3,7020,7054,6004,},num={1000,2,1,3,},},flag_reward={10413,},},{key={"mrecharge_month3",},minval={0,},maxval={9,},text={"daily_recharge_4007.require.text[1]",},},3,10,{"",},},
[4008] = {4008,0,3,"仙侶禮包","1490","1990",4,1490,1490,{item={id={3,7020,7054,6004,},num={2990,6,2,10,},},flag_reward={10414,},},{key={"mrecharge_month4",},minval={0,},maxval={9,},text={"daily_recharge_4008.require.text[1]",},},3,10,{"",},},
[4009] = {4009,0,3,"青銅奇寶","30","68",1,30,30,{item={id={7027,7058,7055,1,},num={5,10,1,100000,},},flag_reward={10415,},},{key={"drecharge_month5",},minval={0,},maxval={1,},text={"daily_recharge_4009.require.text[1]",},},1,2,{"",},},
[4010] = {4010,0,3,"白銀靈寶","490","800",2,490,490,{item={id={7020,7059,7024,7054,},num={5,30,10,5,},},flag_reward={10416,},},{key={"drecharge_month6",},minval={0,},maxval={1,},text={"daily_recharge_4010.require.text[1]",},},1,2,{"",},},
[4011] = {4011,0,3,"黃金仙寶","1490","2680",3,1490,1490,{item={id={7020,7060,7025,7054,},num={10,30,10,20,},},flag_reward={10417,},},{key={"drecharge_month7",},minval={0,},maxval={1,},text={"daily_recharge_4011.require.text[1]",},},1,2,{"",},},
[4012] = {4012,1,3,"青銅奇寶","30","68",1,30,30,{item={id={7028,6004,2500,1,},num={1,2,2,100000,},},flag_reward={10415,},},{key={"drecharge_month5",},minval={0,},maxval={1,},text={"daily_recharge_4012.require.text[1]",},},1,2,{"",},},
[4013] = {4013,1,3,"白銀靈寶","490","800",2,490,490,{item={id={7028,6004,2501,7054,},num={10,30,10,5,},},flag_reward={10416,},},{key={"drecharge_month6",},minval={0,},maxval={1,},text={"daily_recharge_4013.require.text[1]",},},1,2,{"",},},
[4014] = {4014,1,3,"黃金仙寶","1490","2680",3,1490,1490,{item={id={7029,6004,2502,7054,},num={20,50,20,20,},},flag_reward={10417,},},{key={"drecharge_month7",},minval={0,},maxval={1,},text={"daily_recharge_4014.require.text[1]",},},1,2,{"",},},
[4015] = {4015,0,3,"青銅奇寶","30","128",1,30,30,{item={id={3,7027,7055,1,},num={60,2,1,100000,},},flag_reward={10415,},},{key={"drecharge_month5",},minval={0,},maxval={1,},text={"daily_recharge_4015.require.text[1]",},},1,2,{"",},},
[4016] = {4016,0,3,"白銀靈寶","490","1480",2,490,490,{item={id={3,7027,7024,7054,},num={1000,10,5,5,},},flag_reward={10416,},},{key={"drecharge_month6",},minval={0,},maxval={1,},text={"daily_recharge_4016.require.text[1]",},},1,2,{"",},},
[4017] = {4017,0,3,"黃金仙寶","1490","3880",3,1490,1490,{item={id={3,7091,7093,7089,},num={3000,1,1,1,},},flag_reward={10417,},},{key={"drecharge_month7",},minval={0,},maxval={1,},text={"daily_recharge_4017.require.text[1]",},},1,2,{"",},},
[4018] = {4018,0,3,"青銅奇寶","30","128",1,30,30,{item={id={7058,7027,2500,6004,},num={10,2,1,2,},},flag_reward={10415,},},{key={"drecharge_month5",},minval={0,},maxval={1,},text={"daily_recharge_4018.require.text[1]",},},1,2,{"",},},
[4019] = {4019,0,3,"白銀靈寶","490","1480",2,490,490,{item={id={7059,7027,2501,6004,},num={20,50,10,10,},},flag_reward={10416,},},{key={"drecharge_month6",},minval={0,},maxval={1,},text={"daily_recharge_4019.require.text[1]",},},1,2,{"",},},
[4020] = {4020,0,3,"黃金仙寶","1490","3880",3,1490,1490,{item={id={7054,7095,7097,7094,},num={10,4,4,4,},},flag_reward={10417,},},{key={"drecharge_month7",},minval={0,},maxval={1,},text={"daily_recharge_4020.require.text[1]",},},1,2,{"",},},

}
