
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","is_selling","store_type","name","pic_res","show_price","show_give","show_get","order","exp_vip","accumulative_count","counts","last_time","flag","reward","require","bonusreward","bonustimes","reset_time","limit_num","recharge_event",},
[50001] = {50001,1,6,"百年靈桃樹種","#dynamic/TL_planting/output/TL_planting.xml|TL_planting|9","NTD150","150","150",1,150,150,3,7,"planting50001",{item={id={3,},num={150,},},flag_reward={15701,},},{key={"fRecharge_Planting1",},minval={0,},maxval={0,},text={"planting_recharge_50001.require.text[1]",},},{item={id={0,},num={0,},},},0,0,1,{"",},},
[50002] = {50002,1,6,"千年仙桃樹種","#dynamic/TL_planting/output/TL_planting.xml|TL_planting|15","NTD300","300","300",2,150,150,3,7,"planting50002",{item={id={3,},num={300,},},flag_reward={15702,},},{key={"fRecharge_Planting2",},minval={0,},maxval={0,},text={"planting_recharge_50002.require.text[1]",},},{item={id={0,},num={0,},},},0,0,1,{"",},},
[50003] = {50003,1,6,"萬年蟠桃樹種","#dynamic/TL_planting/output/TL_planting.xml|TL_planting|8","NTD1490","1500","1500",3,1490,1490,3,7,"planting50003",{item={id={3,},num={1500,},},flag_reward={15703,},},{key={"fRecharge_Planting3",},minval={0,},maxval={0,},text={"planting_recharge_50003.require.text[1]",},},{item={id={0,},num={0,},},},0,0,1,{"",},},

}
