
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","difficulty","infloor","floor","floor_order","event","startpoint","success_event",},
[1] = {1,1,1,1,1,{"monster_pub.60101",},{"start1","start1_2",},{"client_drama.map/map500040_1",},},
[2] = {2,1,2,2,1,{"monster_pub.60102",},{"start2","start2_2",},{"client_drama.map/map500040_2",},},
[3] = {3,1,3,3,1,{"monster_pub.60103",},{"start3","start3_2",},{"client_drama.map/map500040_3",},},
[4] = {4,1,4,4,1,{"monster_pub.60104",},{"start1","start1_2",},{"client_drama.map/map500040_1",},},
[5] = {5,1,5,5,1,{"monster_pub.60105",},{"start2","start2_2",},{"client_drama.map/map500040_2",},},
[6] = {6,1,6,6,1,{"monster_pub.60106",},{"start3","start3_2",},{"client_drama.map/map500040_3",},},
[7] = {7,1,7,7,1,{"monster_pub.60107",},{"start1","start1_2",},{"client_drama.map/map500040_1",},},
[8] = {8,1,8,8,1,{"monster_pub.60108",},{"start2","start2_2",},{"client_drama.map/map500040_2",},},
[9] = {9,1,9,9,1,{"monster_pub.60109",},{"start3","start3_2",},{"client_drama.map/map500040_3",},},
[10] = {10,1,10,10,1,{"monster_pub.60110",},{"start1","start1_2",},{"client_drama.map/map500040_1",},},
[11] = {11,2,1,11,1,{"monster_pub.60111",},{"start2","start2_2",},{"client_drama.map/map500040_2",},},
[12] = {12,2,2,12,1,{"monster_pub.60112",},{"start3","start3_2",},{"client_drama.map/map500040_3",},},
[13] = {13,2,3,13,1,{"monster_pub.60113",},{"start1","start1_2",},{"client_drama.map/map500040_1",},},

}
