
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","is_selling","store_type","flag","showmodel","pos_xy","zoom","rotate","reward","require","show_price","show_fight","show",},
[9001] = {9001,1,4,9001,{"/res/effect/item/ef_item_god_02.assetbundles","/res/unit/mount_hippocampus.assetbundles",},{"0,0","0,0",},{"100","100",},{0,0,},{item={id={3,3,1,1200,},num={1,1000,100000,50,},},flag_reward={10901,},},{key={"frecharge_first",},minval={0,},maxval={0,},text={"first_recharge_9001.require.text[1]",},},6888,99999,{item={3,3,1,1200,},itemnum={1,1000,100000,50,},},},

}
