
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","is_selling","store_type","name","pic_res","show_model","pos_xy","zoom","rotate","show_price","show_cost","exp_vip","accumulative_count","reward","bonusreward","bonustimes","require","recharge_event",},
[5001] = {5001,1,5,"成长基金","","/res/unit/partner_yehua.assetbundles","0,0","150",330,"490","5",490,490,{item={id={0,},num={0,},},flag_reward={10910,10501,},},{item={id={0,},num={0,},},},0,{key={"frecharge_fund",},minval={0,},maxval={0,},text={"fund_recharge_5001.require.text[1]",},},{"fund_recharge",},},
[5002] = {5002,1,5,"成长基金","","/res/unit/partner_yehua.assetbundles","0,0","150",330,"500","5",500,500,{item={id={3,},num={100,},},flag_reward={10910,10501,},},{item={id={0,},num={0,},},},0,{key={"frecharge_fund",},minval={0,},maxval={0,},text={"fund_recharge_5002.require.text[1]",},},{"fund_recharge",},},
[5003] = {5003,1,5,"成长基金","","/res/unit/partner_yehua.assetbundles","0,0","150",330,"98","5",980,98,{item={id={0,},num={0,},},flag_reward={10910,10501,},},{item={id={0,},num={0,},},},0,{key={"frecharge_fund",},minval={0,},maxval={0,},text={"fund_recharge_5003.require.text[1]",},},{"fund_recharge",},},

}
