
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"key","type","arg",},
["fund_recharge"] = {"fund_recharge",1,{"FundGetNum","","",},},
["guild_gift1"] = {"guild_gift1",2,{"5002","","",},},
["guild_gift2"] = {"guild_gift2",2,{"5003","","",},},
["guild_gift3"] = {"guild_gift3",2,{"5004","","",},},
["guild_gift4"] = {"guild_gift4",2,{"5005","","",},},

}
