
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","filter",},
[1] = {1,{type={"item_type","quality",},min={3,2,},max={3,3,},},},
[2] = {2,{type={"item_type","quality",},min={3,3,},max={3,4,},},},
[3] = {3,{type={"item_type","quality",},min={3,2,},max={3,4,},},},
[4] = {4,{type={"item_type","quality",},min={3,2,},max={3,3,},},},
[5] = {5,{type={"item_type","quality",},min={3,2,},max={3,3,},},},
[6] = {6,{type={"item_type","quality",},min={3,2,},max={3,3,},},},
[7] = {7,{type={"item_type","quality",},min={3,2,},max={3,3,},},},
[8] = {8,{type={"item_type","quality",},min={3,2,},max={3,3,},},},

}
