
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","mapid","lv","fight","guardrange","guardrangelimit",},
[1] = {1,95559,{min=10,max=20,},{min=0,max=0,},0,50,},
[2] = {2,100010,{min=0,max=0,},{min=20000,max=200000,},20,50,},
[3] = {3,100020,{min=0,max=999,},{min=20000,max=200000,},20,50,},

}
