
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","item_type","sec_type","is_show","is_redpoint",},
[1] = {1,3,1,1,1,},
[2] = {2,3,2,1,1,},
[3] = {3,3,3,1,1,},
[4] = {4,3,4,1,1,},
[5] = {5,3,5,1,1,},

}
