
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","require","list","award","level","name","msg","elements",},
[1] = {1,{key="pLevel",minval=1,maxval=-1,text="Sheet1_1.require.text",},{1,2,},{flag="fQuest_Finish/newbie01",drop=0,key={"gold","hp","exp",},val={10,1000,1000,},},1,"Sheet1_1.name","Sheet1_1.msg",{{from="yuhua.f0",to="yuhua.t0",},{from="yuhua22.f1",to="yuhua23.t1",},},},
[2] = {2,{key="fQuest_Finish/newbie01",minval=1,maxval=1,text="Sheet1_2.require.text",},{3,4,},{flag="Quest",drop=1111,key={"a","b","c",},val={1,2,3,},},10,"Sheet1_2.name","Sheet1_2.msg",{{from="yuhua.f10",to="yuhua.t10",},{from="yuhua22.f11",to="yuhua23.t11",},},},
[3] = {3,{key="Finish/newbie01",minval=2,maxval=3,text="Sheet1_3.require.text",},{5,6,},{flag="Quest",drop=3333,key={"1","2","3",},val={1,2,3,},},0,"Sheet1_3.name","Sheet1_3.msg",{{from="yuhua.f20",to="yuhua.t20",},{from="yuhua22.f21",to="yuhua23.t21",},},},
[4] = {4,{key="fQuest_Finish/newbie01",minval=1,maxval=1,text="Sheet1_4.require.text",},{7,8,},{flag="Quest",drop=1111,key={"","","",},val={0,0,0,},},10,"Sheet1_4.name","Sheet1_4.msg",{{from="yuhua.f30",to="yuhua.t30",},{from="yuhua22.f31",to="yuhua23.t31",},},},

}
