
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_go","Title","des","cancelBtn","okBtn","okBtnGoto",},
[1] = {1,"not_enough_gold","goto_1.Title","goto_1.des","goto_1.cancelBtn","goto_1.okBtn","recharge",},
[2] = {2,"not_enough_silver","goto_2.Title","goto_2.des","goto_2.cancelBtn","goto_2.okBtn","silver_get",},
[3] = {3,"res_dungeon_exp_tickets","goto_3.Title","goto_3.des","goto_3.cancelBtn","goto_3.okBtn","res_dungeon_exp_tickets",},
[4] = {4,"res_dungeon_wing_tickets","goto_4.Title","goto_4.des","goto_4.cancelBtn","goto_4.okBtn","res_dungeon_wing_tickets",},
[5] = {5,"res_dungeon_mount_tickets","goto_5.Title","goto_5.des","goto_5.cancelBtn","goto_5.okBtn","res_dungeon_mount_tickets",},
[6] = {6,"res_dungeon_miracle_tickets","goto_6.Title","goto_6.des","goto_6.cancelBtn","goto_6.okBtn","res_dungeon_miracle_tickets",},
[7] = {7,"god_island_tickets","goto_7.Title","goto_7.des","goto_7.cancelBtn","goto_7.okBtn","god_island_tickets",},
[8] = {8,"tower_reset","goto_8.Title","goto_8.des","goto_8.cancelBtn","goto_8.okBtn","tower_reset",},
[9] = {9,"social_buygift","goto_9.Title","goto_9.des","goto_9.cancelBtn","goto_9.okBtn","shop_100",},
[10] = {10,"not_enough_copper","goto_10.Title","goto_10.des","goto_10.cancelBtn","goto_10.okBtn","copper_get",},
[11] = {11,"social_buygift_1","goto_11.Title","goto_11.des","goto_11.cancelBtn","goto_11.okBtn","shop_100_5037",},
[12] = {12,"social_buygift_2","goto_12.Title","goto_12.des","goto_12.cancelBtn","goto_12.okBtn","shop_100_5038",},
[13] = {13,"social_buygift_3","goto_13.Title","goto_13.des","goto_13.cancelBtn","goto_13.okBtn","shop_100_5039",},

}
