---预览物品UI
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/10/23 14:41
---params=物品列表,数量  eg: 
---Lua表结构(会做去零处理)
---local drop1={
---	id={1200,0,4013,3},
---	num={20,0,50,40},
---}
---List结构
---local drop2={
---	{id=1200,num=30},
---	{id=4013,num=20},
---	{id=3,num=50},
---}
local _M = {}
_M.__index = _M

local ItemModel = require 'Model/ItemModel'
local UIUtil = require 'UI/UIUtil'
local Util = require 'Logic/Util'


function _M.OnInit(self)
    self.menu.ShowType = UIShowType.Cover
    self.ui.menu:SetCompAnime(self.ui.menu, UIAnimeType.NoAnime)
end


--移除物品id为0的数据，并重新组合
local function RemoveZeroItem(item)
    local temp={}
    for i, v in ipairs(item.id) do
        if item.id[i] ~=0 then
            table.insert(temp,{id=v,num=item.num[i]})
        end
    end
    return temp
end


--设置获得物品
local function SetPreview(self,node,index)
    --重新计算位置
   if #self.iteminfo <=3 then
        node.Transform.localPosition=Vector2((self.ui.comps.cvs_detail.Width/(#self.iteminfo+1))*index-node.Width/2,node.Transform.localPosition.y)
    end
    local cvs_item=node:FindChildByEditName('cvs_item', true)
    local lb_name=node:FindChildByEditName('lb_name',true)
    local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(self.iteminfo[index].id))
    lb_name.Text=Util.GetText(itemdetail.static.name)
    local quality = itemdetail.static.quality
    local icon=itemdetail.static.atlas_id
    local number=tonumber(self.iteminfo[index].num)
    local itshow=UIUtil.SetItemShowTo(cvs_item,icon,quality,number)
    itshow.EnableTouch = true
    itshow.TouchClick = function()
        local detail = UIUtil.ShowNormalItemDetail({x=node.X+210,y=node.Y+370,detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
    end
end


function _M.OnEnter(self,params)
    --黑屏
    self.ui.menu:SetFullBackground(UILayout.CreateUILayoutColor(UnityEngine.Color(0,0,0,0.5),UnityEngine.Color(0,0,0,0.5)))
    self.ui.comps.cvs_reward.Visible=false

    if #params ==0 then
        self.iteminfo=RemoveZeroItem(params)
    else
        self.iteminfo=params
    end
    
    UIUtil.ConfigHScrollPan(self.ui.comps.sp_reward,self.ui.comps.cvs_reward, #self.iteminfo, function(node, index)
        SetPreview(self,node,index)
    end)
    self.ui.comps.cvs_info.TouchClick=function(sender)
        self.ui:Close()
    end
    self.ui.comps.cvs_back.TouchClick=function(sender)
        self.ui:Close()
    end
end


function _M.OnExit(self)

end


return _M