
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","item_id","item_name","item_tips","item_array","item_type","item_effect","item_level","icon",},
[1] = {1,6004,"item_medicine_1.item_name","item_medicine_1.item_tips",105,2,2500,1,"#static/medicinal_icon/output/medicinal_icon.xml|medicinal_icon|16",},
[2] = {2,6005,"item_medicine_2.item_name","item_medicine_2.item_tips",106,2,4000,1,"#static/medicinal_icon/output/medicinal_icon.xml|medicinal_icon|17",},
[3] = {3,7122,"item_medicine_3.item_name","item_medicine_3.item_tips",110,2,4000,1,"#static/medicinal_icon/output/medicinal_icon.xml|medicinal_icon|20",},
[4] = {4,7123,"item_medicine_4.item_name","item_medicine_4.item_tips",109,2,3000,1,"#static/medicinal_icon/output/medicinal_icon.xml|medicinal_icon|21",},
[5] = {5,7124,"item_medicine_5.item_name","item_medicine_5.item_tips",108,2,2000,1,"#static/medicinal_icon/output/medicinal_icon.xml|medicinal_icon|22",},
[6] = {6,7188,"item_medicine_6.item_name","item_medicine_6.item_tips",107,2,4000,1,"#static/medicinal_icon/output/medicinal_icon.xml|medicinal_icon|23",},

}
