
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","rank_min","rank_max","rank_name","reward_mail_id","show","showmodel","pos_xy","zoom","rotate",},
[1] = {1,17001,1,1,"fightrank_1.rank_name",60001,{item={5042,20054,5052,7001,},itemnum={1,1,1,3,},},{"/res/unit/mount_skate.assetbundles","",},{"38,76","",},{"50","",},{60,0,},},
[2] = {2,17001,2,3,"fightrank_2.rank_name",60002,{item={5052,7001,7060,2,},itemnum={1,2,10,2000,},},{"/res/unit/mount_skate.assetbundles","",},{"38,76","",},{"50","",},{45,0,},},
[3] = {3,17001,4,10,"fightrank_3.rank_name",60003,{item={5051,7001,7059,2,},itemnum={1,1,20,1500,},},{"/res/unit/mount_skate.assetbundles","",},{"38,76","",},{"50","",},{45,0,},},
[4] = {4,17001,11,20,"fightrank_4.rank_name",60004,{item={5051,7001,7059,2,},itemnum={1,1,10,1000,},},{"/res/unit/mount_skate.assetbundles","",},{"38,76","",},{"50","",},{45,0,},},

}
