
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","avatar_type","sheet_id","sheet_name","secsheet_id","secsheet_name",},
[1] = {1,1,1,"avatar_menu_1.sheet_name",1,"avatar_menu_1.secsheet_name",},
[2] = {2,2,1,"avatar_menu_2.sheet_name",2,"avatar_menu_2.secsheet_name",},
[4] = {4,4,1,"avatar_menu_4.sheet_name",3,"avatar_menu_4.secsheet_name",},
[5] = {5,5,3,"avatar_menu_5.sheet_name",1,"avatar_menu_5.secsheet_name",},
[6] = {6,6,4,"avatar_menu_6.sheet_name",1,"avatar_menu_6.secsheet_name",},
[8] = {8,0,5,"avatar_menu_8.sheet_name",1,"avatar_menu_8.secsheet_name",},

}
