
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","type_id","type_name","item_type","sec_type","condition","max_num",},
[1] = {1,101,"trade_bank_1.type_name",2,1,{id={1,2,3,4,},},-1,},
[2] = {2,102,"trade_bank_2.type_name",2,2,{id={1,2,3,4,},},-1,},
[3] = {3,103,"trade_bank_3.type_name",2,3,{id={1,2,3,4,},},-1,},
[4] = {4,104,"trade_bank_4.type_name",2,4,{id={1,2,3,4,},},-1,},
[5] = {5,105,"trade_bank_5.type_name",2,5,{id={1,2,3,4,},},-1,},
[6] = {6,106,"trade_bank_6.type_name",2,6,{id={1,2,3,4,},},-1,},
[7] = {7,107,"trade_bank_7.type_name",2,7,{id={1,2,3,4,},},-1,},
[8] = {8,108,"trade_bank_8.type_name",2,8,{id={1,2,3,4,},},-1,},
[9] = {9,1,"trade_bank_9.type_name",0,0,{id={0,0,0,0,},},-1,},
[10] = {10,2,"trade_bank_10.type_name",4,0,{id={0,0,0,0,},},-1,},

}
