
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","magnification","weight","res","notice",},
[1] = {1,1,7500,"",0,},
[2] = {2,2,1400,"/res/effect/ui/ef_ui_crit_02.assetbundles",0,},
[3] = {3,5,1100,"/res/effect/ui/ef_ui_crit_05.assetbundles",0,},

}
