
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","store_type","sheet_id","sheet_name",},
[1] = {1,100,1001,"store_menu_1.sheet_name",},
[2] = {2,100,1002,"store_menu_2.sheet_name",},
[3] = {3,100,1003,"store_menu_3.sheet_name",},
[4] = {4,200,2001,"store_menu_4.sheet_name",},
[5] = {5,300,3001,"store_menu_5.sheet_name",},
[6] = {6,400,3001,"store_menu_6.sheet_name",},

}
