
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","difficulty","infloor","floor","require","floor_name","boss_icon","power","notice","preview","first_reward","reward",},
[1] = {1,1,1,1,{key={"",},minval={0,},maxval={0,},text={"cptower_1.require.text[1]",},},"cptower_1.floor_name","",15000,0,{id={5191,5192,1200,1,},},{id={1200,7054,130017,1202,},num={10,1,1,10,},},{type="common_reward",reward_id={2010,},flag_id={2068,},},},
[2] = {2,1,2,2,{key={"",},minval={0,},maxval={0,},text={"cptower_2.require.text[1]",},},"cptower_2.floor_name","",20000,0,{id={5191,5192,1200,1,},},{id={1200,7054,130018,1202,},num={20,2,1,20,},},{type="common_reward",reward_id={2020,},flag_id={2068,},},},
[3] = {3,1,3,3,{key={"",},minval={0,},maxval={0,},text={"cptower_3.require.text[1]",},},"cptower_3.floor_name","",40000,0,{id={5191,5192,1200,1,},},{id={1200,7054,130027,1202,},num={30,3,1,30,},},{type="common_reward",reward_id={2030,},flag_id={2068,},},},
[4] = {4,1,4,4,{key={"",},minval={0,},maxval={0,},text={"cptower_4.require.text[1]",},},"cptower_4.floor_name","",50000,0,{id={5191,5192,1200,1,},},{id={1200,7054,130028,1202,},num={40,4,1,40,},},{type="common_reward",reward_id={2040,},flag_id={2068,},},},
[5] = {5,1,5,5,{key={"",},minval={0,},maxval={0,},text={"cptower_5.require.text[1]",},},"cptower_5.floor_name","",65000,116,{id={5191,5192,1200,1,},},{id={1200,7054,130037,1202,},num={50,5,1,50,},},{type="common_reward",reward_id={2050,},flag_id={2068,},},},
[6] = {6,1,6,6,{key={"",},minval={0,},maxval={0,},text={"cptower_6.require.text[1]",},},"cptower_6.floor_name","",100000,116,{id={5191,5192,1200,1,},},{id={1200,7054,130038,1202,},num={100,6,1,60,},},{type="common_reward",reward_id={2060,},flag_id={2068,},},},
[7] = {7,1,7,7,{key={"",},minval={0,},maxval={0,},text={"cptower_7.require.text[1]",},},"cptower_7.floor_name","",170000,116,{id={5191,5192,1200,1,},},{id={1200,7054,130047,1202,},num={200,7,1,70,},},{type="common_reward",reward_id={2070,},flag_id={2068,},},},
[8] = {8,1,8,8,{key={"",},minval={0,},maxval={0,},text={"cptower_8.require.text[1]",},},"cptower_8.floor_name","",280000,116,{id={5191,5192,1200,1,},},{id={1200,7054,130048,1202,},num={300,8,1,80,},},{type="common_reward",reward_id={2080,},flag_id={2068,},},},
[9] = {9,1,9,9,{key={"",},minval={0,},maxval={0,},text={"cptower_9.require.text[1]",},},"cptower_9.floor_name","",360000,116,{id={5191,5192,1200,1,},},{id={1200,7054,130057,1202,},num={400,9,1,90,},},{type="common_reward",reward_id={2090,},flag_id={2068,},},},
[10] = {10,1,10,10,{key={"",},minval={0,},maxval={0,},text={"cptower_10.require.text[1]",},},"cptower_10.floor_name","",480000,116,{id={5191,5192,1200,1,},},{id={1200,7054,130058,1202,},num={500,10,1,100,},},{type="common_reward",reward_id={2100,},flag_id={2068,},},},
[11] = {11,2,1,11,{key={"",},minval={0,},maxval={0,},text={"cptower_11.require.text[1]",},},"cptower_11.floor_name","",600000,117,{id={5183,5192,1200,1,},},{id={1200,7054,130057,1202,},num={600,11,1,110,},},{type="common_reward",reward_id={2110,},flag_id={2068,},},},
[12] = {12,2,2,12,{key={"",},minval={0,},maxval={0,},text={"cptower_12.require.text[1]",},},"cptower_12.floor_name","",720000,117,{id={5183,5192,1200,1,},},{id={1200,7054,130068,1202,},num={700,12,1,120,},},{type="common_reward",reward_id={2120,},flag_id={2068,},},},
[13] = {13,2,3,13,{key={"",},minval={0,},maxval={0,},text={"cptower_13.require.text[1]",},},"cptower_13.floor_name","",840000,117,{id={5183,5192,1200,1,},},{id={1200,7054,130067,1202,},num={800,13,1,130,},},{type="common_reward",reward_id={2130,},flag_id={2068,},},},

}
