
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"key","name","order","function_id",},
["skill"] = {"skill","advancetips_skill.name",1,"skill",},
["strengthen"] = {"strengthen","advancetips_strengthen.name",2,"strengthen",},
["gemstone"] = {"gemstone","advancetips_gemstone.name",3,"gemstone",},
["partner"] = {"partner","advancetips_partner.name",4,"partner",},
["wing"] = {"wing","advancetips_wing.name",5,"wing",},
["miraclemain"] = {"miraclemain","advancetips_miraclemain.name",6,"miraclemain",},
["mount"] = {"mount","advancetips_mount.name",7,"mountveins",},
["guildcollege"] = {"guildcollege","advancetips_guildcollege.name",8,"guildcollege_noxl",},

}
