
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","item_type","sec_type","function_id","hud_cvs","advancetips_id",},
[1] = {1,0,1,{"strengthen","compose","skill","guildcollege",},{"cvs_forge","cvs_forge","cvs_skill","cvs_guild",},{2,0,1,8,},},
[2] = {2,0,6,{"guildcollege","","","",},{"cvs_guild","","","",},{8,0,0,0,},},
[3] = {3,1,1,{"strengthen","","","",},{"cvs_forge","","","",},{2,0,0,0,},},
[4] = {4,1,3,{"partner","","","",},{"cvs_partner","","","",},{4,0,0,0,},},
[5] = {5,1,4,{"mountveins","","","",},{"cvs_mount","","","",},{7,0,0,0,},},
[6] = {6,1,5,{"wing","","","",},{"cvs_wings","","","",},{5,0,0,0,},},
[7] = {7,1,6,{"miraclemain","","","",},{"cvs_miracle","","","",},{6,0,0,0,},},
[8] = {8,1,13,{"miraclemain","","","",},{"cvs_miracle","","","",},{6,0,0,0,},},
[9] = {9,1,14,{"partner","","","",},{"cvs_partner","","","",},{4,0,0,0,},},
[10] = {10,1,15,{"partner","compose","","",},{"cvs_partner","cvs_forge","","",},{4,0,0,0,},},
[11] = {11,3,1,{"gemstone","compose","","",},{"cvs_forge","cvs_forge","","",},{3,0,0,0,},},
[12] = {12,3,2,{"gemstone","compose","","",},{"cvs_forge","cvs_forge","","",},{3,0,0,0,},},
[13] = {13,3,3,{"gemstone","compose","","",},{"cvs_forge","cvs_forge","","",},{3,0,0,0,},},
[14] = {14,3,4,{"gemstone","compose","","",},{"cvs_forge","cvs_forge","","",},{3,0,0,0,},},

}
