
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","monster_type","item_type","pile_num","pile_max",},
[1] = {1,1,0,1000,5,},
[2] = {2,2,0,2000,10,},
[3] = {3,3,0,3000,15,},

}
