
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_type","sort","open_lv","icon_res","function_id","function_background","function_tag","desc1","desc2",},
[1] = {1,1,2,10,"#static/TL_hud/output/TL_hud.xml|TL_hud|117","strengthen","SmithyMain","SmithyStrengthen","power_book_1.desc1","power_book_1.desc2",},
[2] = {2,2,3,23,"#static/TL_hud/output/TL_hud.xml|TL_hud|130","gemstone","SmithyMain","SmithyGemstone","power_book_2.desc1","power_book_2.desc2",},
[3] = {3,3,5,50,"#static/TL_hud/output/TL_hud.xml|TL_hud|131","identify","SmithyMain","SmithyIdentify","power_book_3.desc1","power_book_3.desc2",},
[4] = {4,4,6,11,"#static/TL_hud/output/TL_hud.xml|TL_hud|126","mountveins","MountFrame","MountInfo","power_book_4.desc1","power_book_4.desc2",},
[5] = {5,5,7,43,"#static/TL_hud/output/TL_hud.xml|TL_hud|116","wing","WingFrame","","power_book_5.desc1","power_book_5.desc2",},
[6] = {6,6,8,19,"#static/TL_hud/output/TL_hud.xml|TL_hud|122","partner","PartnerFrame","PartnerMain","power_book_6.desc1","power_book_6.desc2",},
[7] = {7,7,9,42,"#static/TL_hud/output/TL_hud.xml|TL_hud|121","miraclemain","MiracleFrame","MiracleFrame","power_book_7.desc1","power_book_7.desc2",},
[8] = {8,8,1,5,"#static/TL_hud/output/TL_hud.xml|TL_hud|115","skill","SkillMain","","power_book_8.desc1","power_book_8.desc2",},
[9] = {9,9,4,47,"#static/TL_hud/output/TL_hud.xml|TL_hud|276","fate","FateMain","","power_book_9.desc1","power_book_9.desc2",},
[10] = {10,10,10,61,"#static/TL_hud/output/TL_hud.xml|TL_hud|290","meridians","MeridiansMain","","power_book_10.desc1","power_book_10.desc2",},

}
