
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","ui_id","name","type","param","tips","open_type","icon_id","comp","item",},
[1] = {1,0,"open_lv_1.name",0,0,"open_lv_1.tips",0,0,"","",},
[2] = {2,0,"open_lv_2.name",1,15,"open_lv_2.tips",2,0,"","{1200,10};{2106,99}",},
[3] = {3,0,"open_lv_3.name",1,5,"open_lv_3.tips",2,0,"","{1200,10};{2106,99}",},
[4] = {4,0,"open_lv_4.name",0,0,"open_lv_4.tips",0,0,"","",},
[5] = {5,0,"open_lv_5.name",0,0,"open_lv_5.tips",0,0,"","",},
[6] = {6,0,"open_lv_6.name",0,0,"open_lv_6.tips",0,0,"","",},

}
