
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","store_id","store_name",},
[1] = {1,1,"store_name_1.store_name",},
[2] = {2,2,"store_name_2.store_name",},
[3] = {3,3,"store_name_3.store_name",},
[4] = {4,4,"store_name_4.store_name",},
[5] = {5,5,"store_name_5.store_name",},
[6] = {6,6,"store_name_6.store_name",},
[7] = {7,7,"store_name_7.store_name",},

}
