
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","needpoint","point_show","item_show","item_show_num","reward","exchangelimit","showmodel","pos_xy","zoom","rotate","text",},
[1] = {1,10,"static/item/gemg06.png",1600,100,{type="common_reward",reward_id={0,},item={id={1600,},num={100,},},title_id=0,},1,{"/res/unit/mount_hippocampus.assetbundles",},{"22,42",},{"100",},{-45,},"oeexcharge_1.text",},
[2] = {2,20,"static/item/gemg06.png",1500,30,{type="common_reward",reward_id={0,},item={id={1500,},num={30,},},title_id=0,},1,{"/res/unit/mount_hippocampus.assetbundles",},{"22,42",},{"100",},{-45,},"oeexcharge_2.text",},
[3] = {3,30,"static/item/gemg06.png",7027,20,{type="common_reward",reward_id={0,},item={id={7027,},num={20,},},title_id=0,},1,{"/res/unit/mount_hippocampus.assetbundles",},{"22,42",},{"100",},{-45,},"oeexcharge_3.text",},
[4] = {4,45,"static/item/gemg06.png",5051,1,{type="common_reward",reward_id={0,},item={id={5051,},num={1,},},title_id=0,},1,{"/res/unit/mount_hippocampus.assetbundles",},{"22,42",},{"100",},{-45,},"oeexcharge_4.text",},
[5] = {5,60,"static/item/gemg06.png",5041,1,{type="common_reward",reward_id={0,},item={id={5041,},num={1,},},title_id=0,},1,{"/res/unit/mount_hippocampus.assetbundles",},{"22,42",},{"100",},{-45,},"oeexcharge_5.text",},

}
