
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","wanted_id","name","quality","questid","weight","require","teamnum","monster","scale","rotate","award",},
[1] = {1,1,"guild_wantedcontrol_1.name",1,301000,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_1.require.text[1]",},},"3",{id="26042",},10000,1,{key={5105,5120,5137,},val={1,1,1,},},},
[2] = {2,2,"guild_wantedcontrol_2.name",2,301000,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_2.require.text[1]",},},"2",{id="26043",},10000,1,{key={5106,5121,5138,},val={1,1,1,},},},
[3] = {3,3,"guild_wantedcontrol_3.name",3,301000,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_3.require.text[1]",},},"1",{id="26010",},10000,1,{key={5107,5122,5139,},val={1,1,1,},},},
[4] = {4,4,"guild_wantedcontrol_4.name",4,301000,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_4.require.text[1]",},},"3",{id="26011",},10000,1,{key={5108,5123,5140,},val={1,1,1,},},},
[5] = {5,5,"guild_wantedcontrol_5.name",5,301000,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_5.require.text[1]",},},"4",{id="26012",},10000,1,{key={5109,5124,5141,},val={1,1,1,},},},
[6] = {6,6,"guild_wantedcontrol_6.name",1,301001,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_6.require.text[1]",},},"3",{id="26050",},10000,1,{key={5110,5125,5142,},val={1,1,1,},},},
[7] = {7,7,"guild_wantedcontrol_7.name",2,301001,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_7.require.text[1]",},},"4",{id="26051",},10000,1,{key={5105,5126,5143,},val={1,1,1,},},},
[8] = {8,8,"guild_wantedcontrol_8.name",3,301001,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_8.require.text[1]",},},"3",{id="26052",},10000,1,{key={5106,5127,5144,},val={1,1,1,},},},
[9] = {9,9,"guild_wantedcontrol_9.name",4,301001,100,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_9.require.text[1]",},},"2",{id="26042",},10000,1,{key={5107,5128,5145,},val={1,1,1,},},},
[10] = {10,10,"guild_wantedcontrol_10.name",5,301001,10,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_10.require.text[1]",},},"3",{id="26043",},10000,1,{key={5108,5129,5146,},val={1,1,1,},},},
[11] = {11,11,"guild_wantedcontrol_11.name",1,301002,10,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_11.require.text[1]",},},"2",{id="26010",},10000,1,{key={5109,5120,5147,},val={1,1,1,},},},
[12] = {12,12,"guild_wantedcontrol_12.name",2,301002,10,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_12.require.text[1]",},},"3",{id="26011",},10000,1,{key={5110,5121,5148,},val={1,1,1,},},},
[13] = {13,13,"guild_wantedcontrol_13.name",3,301002,10,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_13.require.text[1]",},},"4",{id="26012",},10000,1,{key={5105,5122,5149,},val={1,1,1,},},},
[14] = {14,14,"guild_wantedcontrol_14.name",4,301002,10,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_14.require.text[1]",},},"2",{id="26050",},10000,1,{key={5106,5123,5150,},val={1,1,1,},},},
[15] = {15,15,"guild_wantedcontrol_15.name",5,301002,10,{key={"pLevel",},minval={1,},maxval={-1,},text={"guild_wantedcontrol_15.require.text[1]",},},"2",{id="26051",},10000,1,{key={5107,5124,5150,},val={1,1,1,},},},

}
