
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","partner_id","partner_name","partner_card","debris_item","debris_num","qualification","default_skill","passive_skill_id","editor_id","voice","story","reborn_time","reborn_item","reborn_num","avatar_res","pos_xy","zoom","item_goto",},
[1] = {1,1001,"partner_list_1.partner_name",3300,3500,50,14,301,1,95562,"","partner_list_1.story",120000,3,100,"/res/unit/npc_blacksmith.assetbundles","0,0","100","3,4,5",},
[2] = {2,1002,"partner_list_2.partner_name",3301,3501,50,13,401002,2,41002,"","partner_list_2.story",120000,3,100,"/res/unit/npc_blacksmith.assetbundles","0,0","100","3,4,5",},
[3] = {3,1003,"partner_list_3.partner_name",3302,3502,50,12,401003,3,41003,"","partner_list_3.story",120000,3,100,"/res/unit/npc_blacksmith.assetbundles","0,0","100","3,6,7",},
[4] = {4,1004,"partner_list_4.partner_name",3303,3503,50,11,401004,4,41004,"","partner_list_4.story",120000,3,100,"/res/unit/npc_blacksmith.assetbundles","0,0","100","4,5,7",},

}
