
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","qualification","proportion","art_word",},
[1] = {1,11,1000,"#static/TL_static/output/TL_static.xml|TL_static|128",},
[2] = {2,12,1000,"#static/TL_static/output/TL_static.xml|TL_static|126",},
[3] = {3,13,1000,"#static/TL_static/output/TL_static.xml|TL_static|140",},
[4] = {4,14,1000,"#static/TL_static/output/TL_static.xml|TL_static|133",},

}
