
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_id","activity_name","player_lv","play_num","activity_icon","group_id","cost",},
[1] = {1,"shimen","reward_back_1.activity_name",32,20,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|37",1,{id={3,},num={2,},},},
[2] = {2,"island","reward_back_2.activity_name",35,3,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|5",2,{id={3,},num={30,},},},
[3] = {3,"dungeondaily_exp","reward_back_3.activity_name",42,1,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|33",3,{id={3,},num={60,},},},
[4] = {4,"dungeondaily_wing","reward_back_4.activity_name",48,1,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|28",4,{id={3,},num={50,},},},
[5] = {5,"dungeondaily_mount","reward_back_5.activity_name",35,1,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|42",5,{id={3,},num={50,},},},
[6] = {6,"dungeondaily_miraclemain","reward_back_6.activity_name",62,1,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|34",6,{id={3,},num={50,},},},

}
