
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","mapid","monsterid","last_time","item_event","npcflag","appear_point","outer","outerevent","finish_flag","success","fail","point","auto_move",},
[1] = {1,500080,21081,1200,{"","","","","","",},"carriage_1","transporter_star",8,"message.10","carriagefinish_1",{id={"reward.21081","message.52",},},{id={"reward.21085","message.53",},},{"point_1","point_2","point_3","point_4","point_5","point_6","point_7","","","","",},1,},
[2] = {2,500080,21082,1200,{"","","","","","",},"carriage_2","transporter_star",8,"message.10","carriagefinish_2",{id={"reward.21082","message.52",},},{id={"reward.21086","message.53",},},{"point_8","point_9","point_10","point_11","point_12","point_13","point_14","point_15","","","",},1,},
[3] = {3,500080,21083,1200,{"","","","","","",},"carriage_3","transporter_star",8,"message.10","carriagefinish_3",{id={"reward.21083","message.52",},},{id={"reward.21087","message.53",},},{"point_16","point_17","point_18","point_19","point_20","point_21","point_22","point_23","point_24","point_25","point_26",},1,},
[4] = {4,500080,21084,1200,{"","","","","","",},"carriage_4","transporter_star",8,"message.10","carriagefinish_3",{id={"reward.21084","message.52",},},{id={"reward.21088","message.53",},},{"point_16","point_17","point_18","point_19","point_20","point_21","point_22","point_23","point_24","point_25","point_26",},1,},

}
