
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","group_id","illusory_name","level","explain","time","flag","res","unlock_res",},
[1] = {1,1,"taixuillusory_1.illusory_name",40,"taixuillusory_1.explain",5,"dungeondaily_equip1","#dynamic/TL_taixu/output/TL_taixu.xml|TL_taixu|7","#dynamic/TL_taixu/output/TL_taixu.xml|TL_taixu|7",},
[2] = {2,2,"taixuillusory_2.illusory_name",100,"taixuillusory_2.explain",5,"dungeondaily_equip2","#dynamic/TL_taixu/output/TL_taixu.xml|TL_taixu|6","#dynamic/TL_taixu/output/TL_taixu.xml|TL_taixu|9",},
[3] = {3,3,"taixuillusory_3.illusory_name",160,"taixuillusory_3.explain",5,"dungeondaily_equip3","#dynamic/TL_taixu/output/TL_taixu.xml|TL_taixu|8","#dynamic/TL_taixu/output/TL_taixu.xml|TL_taixu|8",},

}
