
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Response


local _M = {MessageID = 0x00000000,Name = 'DeepMMO.Protocol.Response'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00000000] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.s2c_code)
	output:PutUTF(data.s2c_msg)
end


function _M.Read(input,data)
		
	data.s2c_code = input:GetS32()
	data.s2c_msg = input:GetUTF()
end


