
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientGetZoneInfoSnapResponse


local _M = {MessageID = 0x00034009,Name = 'DeepMMO.Protocol.Client.ClientGetZoneInfoSnapResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00034009] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientGetZoneInfoSnapResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutUTF(data.s2c_curZoneUUID)
	output:PutList(data.s2c_snaps, output.PutOBJ,'DeepMMO.Data.ZoneInfoSnap')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_curZoneUUID = input:GetUTF()
	data.s2c_snaps = input:GetList(input.GetOBJ,'DeepMMO.Data.ZoneInfoSnap')
end


