
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientEnterZoneNotify


local _M = {MessageID = 0x00034003,Name = 'DeepMMO.Protocol.Client.ClientEnterZoneNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00034003] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientEnterZoneNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutUTF(data.s2c_ZoneUUID)
	output:PutS32(data.s2c_MapTemplateID)
	output:PutS32(data.s2c_ZoneTemplateID)
	output:PutS32(data.s2c_RoleUnitTemplateID)
	output:PutUTF(data.s2c_RoleDisplayName)
	output:PutOBJ(data.s2c_RoleData,'DeepCore.IO.ISerializable')
	output:PutS32(data.s2c_SceneLineIndex)
	output:PutUTF(data.s2c_GuildUUID)
	output:PutS32(data.s2c_ZoneUpdateIntervalMS)
	output:PutMap(data.s2c_Ext, output.PutUTF, output.PutUTF,'string', 'string')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.s2c_ZoneUUID = input:GetUTF()
	data.s2c_MapTemplateID = input:GetS32()
	data.s2c_ZoneTemplateID = input:GetS32()
	data.s2c_RoleUnitTemplateID = input:GetS32()
	data.s2c_RoleDisplayName = input:GetUTF()
	data.s2c_RoleData = input:GetOBJ('DeepCore.IO.ISerializable')
	data.s2c_SceneLineIndex = input:GetS32()
	data.s2c_GuildUUID = input:GetUTF()
	data.s2c_ZoneUpdateIntervalMS = input:GetS32()
	data.s2c_Ext = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
end


