
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.TestResponse


local _M = {MessageID = 0x00FF0001,Name = 'DeepMMO.Protocol.TestResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00FF0001] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.TestResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutUTF(data.c2s_account)
	output:PutUTF(data.c2s_session_token)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.c2s_account = input:GetUTF()
	data.c2s_session_token = input:GetUTF()
end


