
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Data.ClientRoleData


local _M = {MessageID = 0x00022002,Name = 'DeepMMO.Data.ClientRoleData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00022002] = _M
Protocol.Serializer.StringDefined['DeepMMO.Data.ClientRoleData'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.uuid)
	output:PutUTF(data.digitID)
	output:PutUTF(data.name)
	output:PutUTF(data.account_uuid)
	output:PutS32(data.role_template_id)
	output:PutS32(data.unit_template_id)
	output:PutUTF(data.local_code)
	output:PutS32(data.level)
	output:PutDateTime(data.create_time)
	output:PutDateTime(data.last_login_time)
	output:PutUTF(data.server_name)
	output:PutEnum8(data.privilege)
	output:PutUTF(data.last_area_name)
	output:PutUTF(data.last_area_node)
	output:PutUTF(data.last_zone_uuid)
	output:PutS32(data.last_map_template_id)
	output:PutOBJ(data.last_zone_pos,'DeepMMO.Data.ZonePosition')
end


function _M.Read(input,data)
		
	data.uuid = input:GetUTF()
	data.digitID = input:GetUTF()
	data.name = input:GetUTF()
	data.account_uuid = input:GetUTF()
	data.role_template_id = input:GetS32()
	data.unit_template_id = input:GetS32()
	data.local_code = input:GetUTF()
	data.level = input:GetS32()
	data.create_time = input:GetDateTime()
	data.last_login_time = input:GetDateTime()
	data.server_name = input:GetUTF()
	data.privilege = input:GetEnum8()
	data.last_area_name = input:GetUTF()
	data.last_area_node = input:GetUTF()
	data.last_zone_uuid = input:GetUTF()
	data.last_map_template_id = input:GetS32()
	data.last_zone_pos = input:GetOBJ('DeepMMO.Data.ZonePosition')
end


