
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientReconnectServerRequest


local _M = {MessageID = 0x00032003,Name = 'DeepMMO.Protocol.Client.ClientReconnectServerRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00032003] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientReconnectServerRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.c2s_account)
	output:PutUTF(data.c2s_token)
	output:PutS32(data.c2s_logicServerID)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_account = input:GetUTF()
	data.c2s_token = input:GetUTF()
	data.c2s_logicServerID = input:GetS32()
end


