
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Request


local _M = {MessageID = 0x00000000,Name = 'DeepMMO.Protocol.Request'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00000000] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'] = _M

function _M.Write(output,data)
		
	
end


function _M.Read(input,data)
		
	
end


