
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientEnterServerRequest


local _M = {MessageID = 0x00032001,Name = 'DeepMMO.Protocol.Client.ClientEnterServerRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00032001] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientEnterServerRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.c2s_account)
	output:PutUTF(data.c2s_gate_token)
	output:PutUTF(data.c2s_login_token)
	output:PutUTF(data.c2s_session_token)
	output:PutDateTime(data.c2s_time)
	output:PutOBJ(data.c2s_clientInfo,'DeepMMO.Data.ClientInfo')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_account = input:GetUTF()
	data.c2s_gate_token = input:GetUTF()
	data.c2s_login_token = input:GetUTF()
	data.c2s_session_token = input:GetUTF()
	data.c2s_time = input:GetDateTime()
	data.c2s_clientInfo = input:GetOBJ('DeepMMO.Data.ClientInfo')
end


