
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Data.RoleSnap


local _M = {MessageID = 0x00022003,Name = 'DeepMMO.Data.RoleSnap'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00022003] = _M
Protocol.Serializer.StringDefined['DeepMMO.Data.RoleSnap'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.uuid)
	output:PutUTF(data.digitID)
	output:PutUTF(data.name)
	output:PutUTF(data.session_name)
	output:PutUTF(data.account_uuid)
	output:PutS32(data.role_template_id)
	output:PutS32(data.unit_template_id)
	output:PutUTF(data.server_id)
	output:PutS32(data.level)
	output:PutS32(data.vip_level)
	output:PutDateTime(data.create_time)
	output:PutDateTime(data.last_login_time)
	output:PutS32(data.onlineState)
	output:PutEnum8(data.privilege)
end


function _M.Read(input,data)
		
	data.uuid = input:GetUTF()
	data.digitID = input:GetUTF()
	data.name = input:GetUTF()
	data.session_name = input:GetUTF()
	data.account_uuid = input:GetUTF()
	data.role_template_id = input:GetS32()
	data.unit_template_id = input:GetS32()
	data.server_id = input:GetUTF()
	data.level = input:GetS32()
	data.vip_level = input:GetS32()
	data.create_time = input:GetDateTime()
	data.last_login_time = input:GetDateTime()
	data.onlineState = input:GetS32()
	data.privilege = input:GetEnum8()
end


