
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientLeaveZoneNotify


local _M = {MessageID = 0x00034004,Name = 'DeepMMO.Protocol.Client.ClientLeaveZoneNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00034004] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientLeaveZoneNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutUTF(data.s2c_ZoneUUID)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.s2c_ZoneUUID = input:GetUTF()
end


