
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Data.RoleState


local _M = {MessageID = 0x00022005,Name = 'DeepMMO.Data.RoleState'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00022005] = _M
Protocol.Serializer.StringDefined['DeepMMO.Data.RoleState'] = _M

function _M.Write(output,data)
		
	
end


function _M.Read(input,data)
		
	
end


