
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientGetRolesResponse


local _M = {MessageID = 0x00033008,Name = 'DeepMMO.Protocol.Client.ClientGetRolesResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00033008] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientGetRolesResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	if data:IsSuccess()==true then
	output:PutList(data.s2c_roles, output.PutOBJ,'DeepMMO.Data.RoleSnap')
	end
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	if data:IsSuccess()==true then
	data.s2c_roles = input:GetList(input.GetOBJ,'DeepMMO.Data.RoleSnap')
	end
end


