
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.PlayerDynamicNotify


local _M = {MessageID = 0x00035003,Name = 'DeepMMO.Protocol.Client.PlayerDynamicNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00035003] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.PlayerDynamicNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutList(data.s2c_data, output.PutOBJ,'DeepMMO.Data.PropertyStruct')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.s2c_data = input:GetList(input.GetOBJ,'DeepMMO.Data.PropertyStruct')
end


