
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.TestRequest


local _M = {MessageID = 0x00FF0000,Name = 'DeepMMO.Protocol.TestRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00FF0000] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.TestRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.c2s_account)
	output:PutUTF(data.c2s_gate_token)
	output:PutUTF(data.c2s_serverName)
	output:PutDateTime(data.c2s_time)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_account = input:GetUTF()
	data.c2s_gate_token = input:GetUTF()
	data.c2s_serverName = input:GetUTF()
	data.c2s_time = input:GetDateTime()
end


