
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Data.RoleIDSnap


local _M = {MessageID = 0x00000001,Name = 'DeepMMO.Data.RoleIDSnap'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00000001] = _M
Protocol.Serializer.StringDefined['DeepMMO.Data.RoleIDSnap'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.roleUUID)
	output:PutUTF(data.serverID)
	output:PutS32(data.lv)
	output:PutU8(data.pro)
	output:PutU8(data.gender)
	output:PutUTF(data.name)
end


function _M.Read(input,data)
		
	data.roleUUID = input:GetUTF()
	data.serverID = input:GetUTF()
	data.lv = input:GetS32()
	data.pro = input:GetU8()
	data.gender = input:GetU8()
	data.name = input:GetUTF()
end


