
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientCreateRoleRequest


local _M = {MessageID = 0x00033003,Name = 'DeepMMO.Protocol.Client.ClientCreateRoleRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00033003] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientCreateRoleRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.c2s_name)
	output:PutS32(data.c2s_template_id)
	output:PutOBJ(data.c2s_extension_data,'DeepCore.IO.ISerializable')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_name = input:GetUTF()
	data.c2s_template_id = input:GetS32()
	data.c2s_extension_data = input:GetOBJ('DeepCore.IO.ISerializable')
end


