
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- DeepMMO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- DeepMMO.Protocol.Client.ClientPing


local _M = {MessageID = 0x00035001,Name = 'DeepMMO.Protocol.Client.ClientPing'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00035001] = _M
Protocol.Serializer.StringDefined['DeepMMO.Protocol.Client.ClientPing'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutDateTime(data.time)
	output:PutBytes(data.rawdata)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.time = input:GetDateTime()
	data.rawdata = input:GetBytes()
end


