
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- ThreeLives.Client.Protocol.Data.RolePhotoData


local _M = {MessageID = 0x00079602,Name = 'ThreeLives.Client.Protocol.Data.RolePhotoData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00079602] = _M
Protocol.Serializer.StringDefined['ThreeLives.Client.Protocol.Data.RolePhotoData'] = _M

function _M.Write(output,data)
		
	output:PutMap(data.data, output.PutUTF, output.PutOBJ,'string', 'ThreeLives.Client.Protocol.Data.PhotoInfo')
	output:PutMap(data.socialData, output.PutUTF, output.PutUTF,'string', 'string')
end


function _M.Read(input,data)
		
	data.data = input:GetMap(input.GetUTF, input.GetOBJ,'string', 'ThreeLives.Client.Protocol.Data.PhotoInfo')
	data.socialData = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
end


