
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientPartnerStatusChangeResponse


local _M = {MessageID = 0x0009901A,Name = 'TLProtocol.Protocol.Client.ClientPartnerStatusChangeResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009901A] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientPartnerStatusChangeResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutS32(data.s2c_partnerID)
	output:PutU8(data.s2c_status)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_partnerID = input:GetS32()
	data.s2c_status = input:GetU8()
end


