
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Data.TLClientGuildSnap


local _M = {MessageID = 0x00087014,Name = 'TLProtocol.Protocol.Data.TLClientGuildSnap'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00087014] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Data.TLClientGuildSnap'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.id)
	output:PutUTF(data.name)
	output:PutS32(data.level)
	output:PutS64(data.fightPower)
	output:PutS32(data.memberNum)
	output:PutS32(data.maxMemberNum)
	output:PutUTF(data.presidentId)
	output:PutS32(data.fort)
	output:PutS32(data.giftLv)
	output:PutDateTime(data.ExpiredUtc)
end


function _M.Read(input,data)
		
	data.id = input:GetUTF()
	data.name = input:GetUTF()
	data.level = input:GetS32()
	data.fightPower = input:GetS64()
	data.memberNum = input:GetS32()
	data.maxMemberNum = input:GetS32()
	data.presidentId = input:GetUTF()
	data.fort = input:GetS32()
	data.giftLv = input:GetS32()
	data.ExpiredUtc = input:GetDateTime()
end


