
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.TLClientRefreshGuildWantedReponse


local _M = {MessageID = 0x00040035,Name = 'TLProtocol.Protocol.Client.TLClientRefreshGuildWantedReponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00040035] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.TLClientRefreshGuildWantedReponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutList(data.s2c_data, output.PutOBJ,'TLProtocol.Data.GuildWantedInfoData')
	output:PutS32(data.s2c_RefreshTime)
	output:PutDateTime(data.s2c_RefreshDateTime)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_data = input:GetList(input.GetOBJ,'TLProtocol.Data.GuildWantedInfoData')
	data.s2c_RefreshTime = input:GetS32()
	data.s2c_RefreshDateTime = input:GetDateTime()
end


