
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientSendInvitationRequest


local _M = {MessageID = 0x00050027,Name = 'TLProtocol.Protocol.Client.ClientSendInvitationRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00050027] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientSendInvitationRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutS32(data.slotIndex)
	output:PutMap(data.friendIds, output.PutUTF, output.PutUTF,'string', 'string')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.slotIndex = input:GetS32()
	data.friendIds = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
end


