
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TLMonsterDropData


local _M = {MessageID = 0x00068602,Name = 'TLProtocol.Data.TLMonsterDropData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00068602] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TLMonsterDropData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.posX)
	output:PutS32(data.posY)
	output:PutList(data.dropItemList, output.PutOBJ,'TLProtocol.Data.TLDropItemSnapData')
	output:PutS32(data.exp)
	output:PutS32(data.monsterId)
end


function _M.Read(input,data)
		
	data.posX = input:GetS32()
	data.posY = input:GetS32()
	data.dropItemList = input:GetList(input.GetOBJ,'TLProtocol.Data.TLDropItemSnapData')
	data.exp = input:GetS32()
	data.monsterId = input:GetS32()
end


