
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetPartnerListResponse


local _M = {MessageID = 0x0009900C,Name = 'TLProtocol.Protocol.Client.ClientGetPartnerListResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009900C] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetPartnerListResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutList(data.s2c_list, output.PutOBJ,'TLProtocol.Data.ClientPartnerSnap')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_list = input:GetList(input.GetOBJ,'TLProtocol.Data.ClientPartnerSnap')
end


