
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetRechargeInfoResponse


local _M = {MessageID = 0x0009E002,Name = 'TLProtocol.Protocol.Client.ClientGetRechargeInfoResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009E002] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetRechargeInfoResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutMap(data.s2c_data, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.RechargeProductSnap')
	output:PutS32(data.vip_level)
	output:PutS32(data.vip_exp)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_data = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.RechargeProductSnap')
	data.vip_level = input:GetS32()
	data.vip_exp = input:GetS32()
end


