
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetAllBActityInfosResponse.ActivityData


local _M = {MessageID = 0x00000003,Name = 'TLProtocol.Protocol.Client.ClientGetAllBActityInfosResponse.ActivityData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00000003] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetAllBActityInfosResponse.ActivityData'] = _M

function _M.Write(output,data)
		
	output:PutMap(data.data, output.PutS32, output.PutOBJ,'int', 'ThreeLives.Client.Protocol.Data.TLBActivitySnapData')
end


function _M.Read(input,data)
		
	data.data = input:GetMap(input.GetS32, input.GetOBJ,'int', 'ThreeLives.Client.Protocol.Data.TLBActivitySnapData')
end


