
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.StoreSnapData


local _M = {MessageID = 0x0006A601,Name = 'TLProtocol.Data.StoreSnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0006A601] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.StoreSnapData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.templateID)
	output:PutS32(data.boughtNum)
	output:PutS32(data.vipTimes)
end


function _M.Read(input,data)
		
	data.templateID = input:GetS32()
	data.boughtNum = input:GetS32()
	data.vipTimes = input:GetS32()
end


