
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TeamChange


local _M = {MessageID = 0x00084004,Name = 'TLProtocol.Data.TeamChange'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00084004] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TeamChange'] = _M

function _M.Write(output,data)
		
	output:PutU8(data.SourceType)
	output:PutUTF(data.UUID)
	output:PutOBJ(data.Data,'TLProtocol.Data.TeamData')
	output:PutOBJ(data.Member,'TLProtocol.Data.TeamMember')
	output:PutOBJ(data.Setting,'TLProtocol.Data.TeamSetting')
end


function _M.Read(input,data)
		
	data.SourceType = input:GetU8()
	data.UUID = input:GetUTF()
	data.Data = input:GetOBJ('TLProtocol.Data.TeamData')
	data.Member = input:GetOBJ('TLProtocol.Data.TeamMember')
	data.Setting = input:GetOBJ('TLProtocol.Data.TeamSetting')
end


