
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetRechargeOrderResponse


local _M = {MessageID = 0x0009E004,Name = 'TLProtocol.Protocol.Client.ClientGetRechargeOrderResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009E004] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetRechargeOrderResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutUTF(data.s2c_order_id)
	output:PutUTF(data.s2c_notify_url)
	output:PutMap(data.s2c_ext_data, output.PutUTF, output.PutUTF,'string', 'string')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_order_id = input:GetUTF()
	data.s2c_notify_url = input:GetUTF()
	data.s2c_ext_data = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
end


