
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.ReservationSnapData


local _M = {MessageID = 0x0005050E,Name = 'TLProtocol.Data.ReservationSnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0005050E] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.ReservationSnapData'] = _M

function _M.Write(output,data)
		
	output:PutDateTime(data.date)
	output:PutMap(data.info, output.PutS32, output.PutUTF,'int', 'string')
end


function _M.Read(input,data)
		
	data.date = input:GetDateTime()
	data.info = input:GetMap(input.GetS32, input.GetUTF,'int', 'string')
end


