
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientSyncServerTimeResponse


local _M = {MessageID = 0x00096011,Name = 'TLProtocol.Protocol.Client.ClientSyncServerTimeResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00096011] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientSyncServerTimeResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutS64(data.s2c_clientTicks)
	output:PutS64(data.s2c_serverTicks)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_clientTicks = input:GetS64()
	data.s2c_serverTicks = input:GetS64()
end


