
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.TLClientGetMeridiansInfoReponse


local _M = {MessageID = 0x0004032B,Name = 'TLProtocol.Protocol.Client.TLClientGetMeridiansInfoReponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0004032B] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.TLClientGetMeridiansInfoReponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutList(data.s2c_activited, output.PutS32,'int')
	output:PutList(data.s2c_unlocked, output.PutS32,'int')
	output:PutList(data.s2c_cost, output.PutS32,'int')
	output:PutUTF(data.s2c_overflowexp)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_activited = input:GetList(input.GetS32,'int')
	data.s2c_unlocked = input:GetList(input.GetS32,'int')
	data.s2c_cost = input:GetList(input.GetS32,'int')
	data.s2c_overflowexp = input:GetUTF()
end


