
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientStoreBuyItemRequest


local _M = {MessageID = 0x0006A003,Name = 'TLProtocol.Protocol.Client.ClientStoreBuyItemRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0006A003] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientStoreBuyItemRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutS32(data.c2s_store_type)
	output:PutS32(data.c2s_item_id)
	output:PutS32(data.c2s_num)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_store_type = input:GetS32()
	data.c2s_item_id = input:GetS32()
	data.c2s_num = input:GetS32()
end


