
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TaiXuData


local _M = {MessageID = 0x0004012C,Name = 'TLProtocol.Data.TaiXuData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0004012C] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TaiXuData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.groupid)
	output:PutS32(data.curTimes)
	output:PutS32(data.MaxTimes)
end


function _M.Read(input,data)
		
	data.groupid = input:GetS32()
	data.curTimes = input:GetS32()
	data.MaxTimes = input:GetS32()
end


