
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetGuildAttackListResponse


local _M = {MessageID = 0x00098036,Name = 'TLProtocol.Protocol.Client.ClientGetGuildAttackListResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00098036] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetGuildAttackListResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.GuildResponse'].Write(output, data)
	output:PutBool(data.s2c_isFull)
	output:PutList(data.s2c_guildList, output.PutOBJ,'TLProtocol.Protocol.Data.GuildBaseSnapData')
	output:PutUTF(data.s2c_attackGuild)
	output:PutUTF(data.s2c_attackedGuild)
	output:PutMap(data.s2c_attackGuilds, output.PutUTF, output.PutOBJ,'string', 'TLProtocol.Protocol.Data.GuildAtackInfo')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.GuildResponse'].Read(input, data)
	data.s2c_isFull = input:GetBool()
	data.s2c_guildList = input:GetList(input.GetOBJ,'TLProtocol.Protocol.Data.GuildBaseSnapData')
	data.s2c_attackGuild = input:GetUTF()
	data.s2c_attackedGuild = input:GetUTF()
	data.s2c_attackGuilds = input:GetMap(input.GetUTF, input.GetOBJ,'string', 'TLProtocol.Protocol.Data.GuildAtackInfo')
end


