
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGuildChangeNotify


local _M = {MessageID = 0x0009803C,Name = 'TLProtocol.Protocol.Client.ClientGuildChangeNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009803C] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGuildChangeNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutUTF(data.s2c_guildId)
	output:PutUTF(data.s2c_guildName)
	output:PutBool(data.s2c_isKick)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.s2c_guildId = input:GetUTF()
	data.s2c_guildName = input:GetUTF()
	data.s2c_isKick = input:GetBool()
end


