
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.TLClientGetDTPassedInfoReponse


local _M = {MessageID = 0x00040022,Name = 'TLProtocol.Protocol.Client.TLClientGetDTPassedInfoReponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00040022] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.TLClientGetDTPassedInfoReponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutList(data.s2c_data, output.PutBool,'bool')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_data = input:GetList(input.GetBool,'bool')
end


