
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TLRoleSnapExt


local _M = {MessageID = 0x00062007,Name = 'TLProtocol.Data.TLRoleSnapExt'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00062007] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TLRoleSnapExt'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.uuid)
	output:PutS32(data.PKValue)
	output:PutS32(data.MountId)
	output:PutS32(data.VeinId)
	output:PutS32(data.WingLv)
	output:PutMap(data.SuitEquipMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutOBJ(data.PropSnap,'TLProtocol.Data.TLUnitPropSnap')
	output:PutMap(data.ArtifactMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutList(data.ArtifactSkillList, output.PutOBJ,'TLBattle.Common.Plugins.GameSkill')
	output:PutOBJ(data.GodSkillData,'TLBattle.Common.Plugins.GodData')
	output:PutMap(data.GoldMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutMap(data.EquipMap, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.EntityItemData')
	output:PutMap(data.GemMap, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.GridGemData')
	output:PutMap(data.RefineMap, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.GridRefineData')
	output:PutMap(data.SkillMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutDateTime(data.ExpiredUtc)
end


function _M.Read(input,data)
		
	data.uuid = input:GetUTF()
	data.PKValue = input:GetS32()
	data.MountId = input:GetS32()
	data.VeinId = input:GetS32()
	data.WingLv = input:GetS32()
	data.SuitEquipMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.PropSnap = input:GetOBJ('TLProtocol.Data.TLUnitPropSnap')
	data.ArtifactMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.ArtifactSkillList = input:GetList(input.GetOBJ,'TLBattle.Common.Plugins.GameSkill')
	data.GodSkillData = input:GetOBJ('TLBattle.Common.Plugins.GodData')
	data.GoldMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.EquipMap = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.EntityItemData')
	data.GemMap = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.GridGemData')
	data.RefineMap = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.GridRefineData')
	data.SkillMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.ExpiredUtc = input:GetDateTime()
end


