
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientSetModifyDataRequest


local _M = {MessageID = 0x00096008,Name = 'TLProtocol.Protocol.Client.ClientSetModifyDataRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00096008] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientSetModifyDataRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.c2s_key)
	output:PutUTF(data.c2s_value)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_key = input:GetUTF()
	data.c2s_value = input:GetUTF()
end


