
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TLClientRoleData


local _M = {MessageID = 0x00062001,Name = 'TLProtocol.Data.TLClientRoleData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00062001] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TLClientRoleData'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Data.ClientRoleData'].Write(output, data)
	output:PutS64(data.exp)
	output:PutS64(data.needExp)
	output:PutS64(data.overflowExp)
	output:PutList(data.quests, output.PutOBJ,'TLProtocol.Data.QuestDataSnap')
	output:PutOBJ(data.gameOptionsData,'TLProtocol.Data.TLGameOptionsData')
	output:PutMap(data.ClientModifyData, output.PutUTF, output.PutUTF,'string', 'string')
	output:PutEnum8(data.proType)
	output:PutEnum8(data.gender)
	output:PutUTF(data.guildId)
	output:PutUTF(data.guildName)
	output:PutS64(data.FightPower)
	output:PutMap(data.funcOpen, output.PutUTF, output.PutU8,'string', 'byte')
	output:PutS32(data.PKValue)
	output:PutS32(data.practiceLv)
	output:PutS32(data.TargerSystemLv)
	output:PutS32(data.MasterId)
	output:PutS32(data.VipLv)
	output:PutS32(data.VipCurExp)
	output:PutS32(data.TitleID)
	output:PutUTF(data.TitleNameExt)
	output:PutUTF(data.spouseId)
	output:PutUTF(data.spouseName)
	output:PutS32(data.MedicinePoolCurCount)
	output:PutS32(data.AccumulativeCount)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Data.ClientRoleData'].Read(input, data)
	data.exp = input:GetS64()
	data.needExp = input:GetS64()
	data.overflowExp = input:GetS64()
	data.quests = input:GetList(input.GetOBJ,'TLProtocol.Data.QuestDataSnap')
	data.gameOptionsData = input:GetOBJ('TLProtocol.Data.TLGameOptionsData')
	data.ClientModifyData = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
	data.proType = input:GetEnum8()
	data.gender = input:GetEnum8()
	data.guildId = input:GetUTF()
	data.guildName = input:GetUTF()
	data.FightPower = input:GetS64()
	data.funcOpen = input:GetMap(input.GetUTF, input.GetU8,'string', 'byte')
	data.PKValue = input:GetS32()
	data.practiceLv = input:GetS32()
	data.TargerSystemLv = input:GetS32()
	data.MasterId = input:GetS32()
	data.VipLv = input:GetS32()
	data.VipCurExp = input:GetS32()
	data.TitleID = input:GetS32()
	data.TitleNameExt = input:GetUTF()
	data.spouseId = input:GetUTF()
	data.spouseName = input:GetUTF()
	data.MedicinePoolCurCount = input:GetS32()
	data.AccumulativeCount = input:GetS32()
end


