
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetStoreBoughtInfoResponse


local _M = {MessageID = 0x0006A002,Name = 'TLProtocol.Protocol.Client.ClientGetStoreBoughtInfoResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0006A002] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetStoreBoughtInfoResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutList(data.salelist, output.PutS32,'int')
	output:PutMap(data.s2c_data, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.StoreSnapData')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.salelist = input:GetList(input.GetS32,'int')
	data.s2c_data = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.StoreSnapData')
end


