
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGuildInfoChangeNotify


local _M = {MessageID = 0x0009803D,Name = 'TLProtocol.Protocol.Client.ClientGuildInfoChangeNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009803D] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGuildInfoChangeNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutS32(data.s2c_type)
	output:PutS32(data.s2c_level)
	output:PutMap(data.s2c_buildList, output.PutS32, output.PutS32,'int', 'int')
	output:PutS32(data.s2c_monsterRank)
	output:PutS32(data.s2c_donateCount)
	output:PutS32(data.s2c_position)
	output:PutMap(data.s2c_talentList, output.PutS32, output.PutS32,'int', 'int')
	output:PutDateTime(data.s2c_synTime)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.s2c_type = input:GetS32()
	data.s2c_level = input:GetS32()
	data.s2c_buildList = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.s2c_monsterRank = input:GetS32()
	data.s2c_donateCount = input:GetS32()
	data.s2c_position = input:GetS32()
	data.s2c_talentList = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.s2c_synTime = input:GetDateTime()
end


