
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.QuestDataSnap


local _M = {MessageID = 0x00066001,Name = 'TLProtocol.Data.QuestDataSnap'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00066001] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.QuestDataSnap'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.id)
	output:PutList(data.ProgressList, output.PutOBJ,'TLProtocol.Data.TLProgressData')
	output:PutS32(data.state)
	output:PutS32(data.curLoopNum)
	output:PutS32(data.MaxLoopNum)
	output:PutS32(data.mainType)
	output:PutS32(data.subType)
	output:PutDateTime(data.TimeLife)
	output:PutBool(data.isForceAccept)
	output:PutUTF(data.QuestName)
	output:PutBool(data.NeedInitListener)
end


function _M.Read(input,data)
		
	data.id = input:GetS32()
	data.ProgressList = input:GetList(input.GetOBJ,'TLProtocol.Data.TLProgressData')
	data.state = input:GetS32()
	data.curLoopNum = input:GetS32()
	data.MaxLoopNum = input:GetS32()
	data.mainType = input:GetS32()
	data.subType = input:GetS32()
	data.TimeLife = input:GetDateTime()
	data.isForceAccept = input:GetBool()
	data.QuestName = input:GetUTF()
	data.NeedInitListener = input:GetBool()
end


