
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Data.GuildMonsterSnapData


local _M = {MessageID = 0x0008700D,Name = 'TLProtocol.Protocol.Data.GuildMonsterSnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0008700D] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Data.GuildMonsterSnapData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.monsterRank)
	output:PutS32(data.monsterLevel)
	output:PutS32(data.monsterExp)
	output:PutList(data.logList, output.PutOBJ,'TLProtocol.Protocol.Data.GuildLogSnapData')
end


function _M.Read(input,data)
		
	data.monsterRank = input:GetS32()
	data.monsterLevel = input:GetS32()
	data.monsterExp = input:GetS32()
	data.logList = input:GetList(input.GetOBJ,'TLProtocol.Protocol.Data.GuildLogSnapData')
end


