
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.PlayerSnapData


local _M = {MessageID = 0x0005050B,Name = 'TLProtocol.Data.PlayerSnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0005050B] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.PlayerSnapData'] = _M

function _M.Write(output,data)
		
	output:PutList(data.playerList, output.PutOBJ,'TLProtocol.Data.PlayerInfoSnapData')
	output:PutS32(data.friendCount)
	output:PutS32(data.friendMax)
end


function _M.Read(input,data)
		
	data.playerList = input:GetList(input.GetOBJ,'TLProtocol.Data.PlayerInfoSnapData')
	data.friendCount = input:GetS32()
	data.friendMax = input:GetS32()
end


