
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TLAvatarDataSnap


local _M = {MessageID = 0x00067601,Name = 'TLProtocol.Data.TLAvatarDataSnap'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00067601] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TLAvatarDataSnap'] = _M

function _M.Write(output,data)
		
	output:PutMap(data.avatarMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutList(data.requireList, output.PutUTF,'string')
end


function _M.Read(input,data)
		
	data.avatarMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.requireList = input:GetList(input.GetUTF,'string')
end


