
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.MasterIdData


local _M = {MessageID = 0x000400C9,Name = 'TLProtocol.Data.MasterIdData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x000400C9] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.MasterIdData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.index)
	output:PutS32(data.masterid)
	output:PutUTF(data.playeruuid)
end


function _M.Read(input,data)
		
	data.index = input:GetS32()
	data.masterid = input:GetS32()
	data.playeruuid = input:GetUTF()
end


