
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TLClientRoleSnapExt


local _M = {MessageID = 0x00062008,Name = 'TLProtocol.Data.TLClientRoleSnapExt'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00062008] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TLClientRoleSnapExt'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.ID)
	output:PutS32(data.PKValue)
	output:PutS32(data.MountId)
	output:PutS32(data.VeinId)
	output:PutS32(data.WingLv)
	output:PutOBJ(data.PropSnap,'TLProtocol.Data.TLUnitPropSnap')
	output:PutMap(data.ArtifactMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutMap(data.GoldMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutMap(data.EquipMap, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.BagSlotData')
	output:PutMap(data.GemMap, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.GridGemData')
	output:PutMap(data.RefineMap, output.PutS32, output.PutOBJ,'int', 'TLProtocol.Data.GridRefineData')
	output:PutMap(data.SuitEquipMap, output.PutS32, output.PutS32,'int', 'int')
	output:PutDateTime(data.ExpiredUtc)
	output:PutS32(data.CPTowerLayer)
end


function _M.Read(input,data)
		
	data.ID = input:GetUTF()
	data.PKValue = input:GetS32()
	data.MountId = input:GetS32()
	data.VeinId = input:GetS32()
	data.WingLv = input:GetS32()
	data.PropSnap = input:GetOBJ('TLProtocol.Data.TLUnitPropSnap')
	data.ArtifactMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.GoldMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.EquipMap = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.BagSlotData')
	data.GemMap = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.GridGemData')
	data.RefineMap = input:GetMap(input.GetS32, input.GetOBJ,'int', 'TLProtocol.Data.GridRefineData')
	data.SuitEquipMap = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.ExpiredUtc = input:GetDateTime()
	data.CPTowerLayer = input:GetS32()
end


