
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientMatchStateNotify


local _M = {MessageID = 0x00095014,Name = 'TLProtocol.Protocol.Client.ClientMatchStateNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00095014] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientMatchStateNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutBool(data.s2c_matching)
	output:PutDateTime(data.s2c_startUtc)
	output:PutUTF(data.s2c_channel)
	output:PutUTF(data.s2c_desc)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.s2c_matching = input:GetBool()
	data.s2c_startUtc = input:GetDateTime()
	data.s2c_channel = input:GetUTF()
	data.s2c_desc = input:GetUTF()
end


