
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetPlantingInfoResponse


local _M = {MessageID = 0x0009D024,Name = 'TLProtocol.Protocol.Client.ClientGetPlantingInfoResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009D024] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetPlantingInfoResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutList(data.s2c_list, output.PutOBJ,'ThreeLives.Client.Protocol.Data.TLPlantingProductInfo')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_list = input:GetList(input.GetOBJ,'ThreeLives.Client.Protocol.Data.TLPlantingProductInfo')
end


