
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TurnTableGotReward


local _M = {MessageID = 0x000402BE,Name = 'TLProtocol.Data.TurnTableGotReward'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x000402BE] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TurnTableGotReward'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.index)
	output:PutS32(data.state)
end


function _M.Read(input,data)
		
	data.index = input:GetS32()
	data.state = input:GetS32()
end


