
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.PlayerInfoSnapData


local _M = {MessageID = 0x0005050A,Name = 'TLProtocol.Data.PlayerInfoSnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0005050A] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.PlayerInfoSnapData'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['TLProtocol.Data.SocialBaseSnapData'].Write(output, data)
	output:PutBool(data.applied)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['TLProtocol.Data.SocialBaseSnapData'].Read(input, data)
	data.applied = input:GetBool()
end


