
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.GridGemData


local _M = {MessageID = 0x00089003,Name = 'TLProtocol.Data.GridGemData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00089003] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.GridGemData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.EquipPos)
	output:PutList(data.Slots, output.PutOBJ,'TLProtocol.Data.GridGemSlotData')
end


function _M.Read(input,data)
		
	data.EquipPos = input:GetS32()
	data.Slots = input:GetList(input.GetOBJ,'TLProtocol.Data.GridGemSlotData')
end


