
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Data.GuildAtackInfo


local _M = {MessageID = 0x00000007,Name = 'TLProtocol.Protocol.Data.GuildAtackInfo'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00000007] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Data.GuildAtackInfo'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.attackCount)
	output:PutMap(data.attackType, output.PutS32, output.PutS32,'int', 'int')
	output:PutDateTime(data.lastAttackTime)
end


function _M.Read(input,data)
		
	data.attackCount = input:GetS32()
	data.attackType = input:GetMap(input.GetS32, input.GetS32,'int', 'int')
	data.lastAttackTime = input:GetDateTime()
end


