
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientChangePostionRequest


local _M = {MessageID = 0x00098017,Name = 'TLProtocol.Protocol.Client.ClientChangePostionRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00098017] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientChangePostionRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.c2s_tarRoleId)
	output:PutS32(data.c2s_tarPosition)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_tarRoleId = input:GetUTF()
	data.c2s_tarPosition = input:GetS32()
end


