
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetSalesRecordResponse


local _M = {MessageID = 0x000A0010,Name = 'TLProtocol.Protocol.Client.ClientGetSalesRecordResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x000A0010] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetSalesRecordResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.AuctionResponse'].Write(output, data)
	output:PutMap(data.s2c_recordList, output.PutUTF, output.PutOBJ,'string', 'TLProtocol.Protocol.Data.AuctionSaleRecordSnap')
	output:PutU64(data.s2c_goldMax)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.AuctionResponse'].Read(input, data)
	data.s2c_recordList = input:GetMap(input.GetUTF, input.GetOBJ,'string', 'TLProtocol.Protocol.Data.AuctionSaleRecordSnap')
	data.s2c_goldMax = input:GetU64()
end


