
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGuildCarriageStateResponse


local _M = {MessageID = 0x00098044,Name = 'TLProtocol.Protocol.Client.ClientGuildCarriageStateResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00098044] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGuildCarriageStateResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.GuildResponse'].Write(output, data)
	output:PutBool(data.s2c_joined)
	output:PutUTF(data.s2c_enemyGuildName)
	output:PutS32(data.s2c_guildLv)
	output:PutS64(data.s2c_currentFund)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.GuildResponse'].Read(input, data)
	data.s2c_joined = input:GetBool()
	data.s2c_enemyGuildName = input:GetUTF()
	data.s2c_guildLv = input:GetS32()
	data.s2c_currentFund = input:GetS64()
end


