
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientMessageContentNotify


local _M = {MessageID = 0x00097004,Name = 'TLProtocol.Protocol.Client.ClientMessageContentNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00097004] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientMessageContentNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutS32(data.s2c_type)
	output:PutUTF(data.s2c_data)
	output:PutArray(data.s2c_show_channel, output.PutS16,'short')
	output:PutArray(data.s2c_args, output.PutUTF,'string')
	output:PutMap(data.s2c_customArgs, output.PutUTF, output.PutUTF,'string', 'string')
	output:PutS32(data.s2c_noticeid)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.s2c_type = input:GetS32()
	data.s2c_data = input:GetUTF()
	data.s2c_show_channel = input:GetArray(input.GetS16,'short')
	data.s2c_args = input:GetArray(input.GetUTF,'string')
	data.s2c_customArgs = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
	data.s2c_noticeid = input:GetS32()
end


