
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientFunctionPlayedNotify


local _M = {MessageID = 0x0009C101,Name = 'TLProtocol.Protocol.Client.ClientFunctionPlayedNotify'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009C101] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientFunctionPlayedNotify'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Write(output, data)
	output:PutUTF(data.c2s_key)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Notify'].Read(input, data)
	data.c2s_key = input:GetUTF()
end


