
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.SocialBaseSnapData


local _M = {MessageID = 0x00050501,Name = 'TLProtocol.Data.SocialBaseSnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00050501] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.SocialBaseSnapData'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.roleId)
	output:PutUTF(data.roleName)
	output:PutS32(data.pro)
	output:PutS32(data.level)
	output:PutS32(data.gender)
	output:PutS32(data.practiceLv)
	output:PutS64(data.fightPower)
	output:PutUTF(data.guildId)
	output:PutUTF(data.guildName)
end


function _M.Read(input,data)
		
	data.roleId = input:GetUTF()
	data.roleName = input:GetUTF()
	data.pro = input:GetS32()
	data.level = input:GetS32()
	data.gender = input:GetS32()
	data.practiceLv = input:GetS32()
	data.fightPower = input:GetS64()
	data.guildId = input:GetUTF()
	data.guildName = input:GetUTF()
end


