
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.EnemySnapData


local _M = {MessageID = 0x00050509,Name = 'TLProtocol.Data.EnemySnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00050509] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.EnemySnapData'] = _M

function _M.Write(output,data)
		
	output:PutList(data.enemyList, output.PutOBJ,'TLProtocol.Data.EnemyInfoSnapData')
	output:PutS32(data.enemyCount)
	output:PutS32(data.enemyMax)
	output:PutS32(data.deepCount)
	output:PutS32(data.deepMax)
end


function _M.Read(input,data)
		
	data.enemyList = input:GetList(input.GetOBJ,'TLProtocol.Data.EnemyInfoSnapData')
	data.enemyCount = input:GetS32()
	data.enemyMax = input:GetS32()
	data.deepCount = input:GetS32()
	data.deepMax = input:GetS32()
end


