
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.GridRefineData


local _M = {MessageID = 0x00089001,Name = 'TLProtocol.Data.GridRefineData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00089001] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.GridRefineData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.EquipPos)
	output:PutS32(data.Rank)
	output:PutS32(data.Lv)
	output:PutS32(data.BaseAttrPlus)
	output:PutList(data.Properties, output.PutOBJ,'TLProtocol.Data.ItemPropertyData')
end


function _M.Read(input,data)
		
	data.EquipPos = input:GetS32()
	data.Rank = input:GetS32()
	data.Lv = input:GetS32()
	data.BaseAttrPlus = input:GetS32()
	data.Properties = input:GetList(input.GetOBJ,'TLProtocol.Data.ItemPropertyData')
end


