
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientHoldingWeddingRequest


local _M = {MessageID = 0x00050025,Name = 'TLProtocol.Protocol.Client.ClientHoldingWeddingRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00050025] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientHoldingWeddingRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.spouseId)
	output:PutS32(data.weddingType)
	output:PutDateTime(data.date)
	output:PutS32(data.time)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.spouseId = input:GetUTF()
	data.weddingType = input:GetS32()
	data.date = input:GetDateTime()
	data.time = input:GetS32()
end


