
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.ConsignationInfoData


local _M = {MessageID = 0x00040065,Name = 'TLProtocol.Data.ConsignationInfoData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00040065] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.ConsignationInfoData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.state)
	output:PutS32(data.wantedid)
	output:PutS32(data.cdtime)
	output:PutS32(data.index)
end


function _M.Read(input,data)
		
	data.state = input:GetS32()
	data.wantedid = input:GetS32()
	data.cdtime = input:GetS32()
	data.index = input:GetS32()
end


