
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientRelationUpResponse


local _M = {MessageID = 0x00050020,Name = 'TLProtocol.Protocol.Client.ClientRelationUpResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00050020] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientRelationUpResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutS32(data.relationLv)
	output:PutS32(data.relationExp)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.relationLv = input:GetS32()
	data.relationExp = input:GetS32()
end


