
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientIdentifyPreviewInfoResponse.IdentifyPreviewKeyProperty


local _M = {MessageID = 0x0003701A,Name = 'TLProtocol.Protocol.Client.ClientIdentifyPreviewInfoResponse.IdentifyPreviewKeyProperty'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0003701A] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientIdentifyPreviewInfoResponse.IdentifyPreviewKeyProperty'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.ID)
	output:PutList(data.Properties, output.PutOBJ,'TLProtocol.Data.ItemPropertyData')
end


function _M.Read(input,data)
		
	data.ID = input:GetUTF()
	data.Properties = input:GetList(input.GetOBJ,'TLProtocol.Data.ItemPropertyData')
end


