
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientEnterDungeonRequest


local _M = {MessageID = 0x00096014,Name = 'TLProtocol.Protocol.Client.ClientEnterDungeonRequest'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00096014] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientEnterDungeonRequest'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Write(output, data)
	output:PutUTF(data.c2s_FuncId)
	output:PutS32(data.c2s_MapId)
	output:PutMap(data.c2s_ext, output.PutUTF, output.PutUTF,'string', 'string')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Request'].Read(input, data)
	data.c2s_FuncId = input:GetUTF()
	data.c2s_MapId = input:GetS32()
	data.c2s_ext = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
end


