
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Client.ClientGetLvLimitInfoResponse


local _M = {MessageID = 0x0009602B,Name = 'TLProtocol.Protocol.Client.ClientGetLvLimitInfoResponse'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0009602B] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Client.ClientGetLvLimitInfoResponse'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Write(output, data)
	output:PutS32(data.s2c_left_mins)
	output:PutS64(data.s2c_overflow_exp)
	output:PutS32(data.s2c_cur_lv_limit)
	output:PutS32(data.s2c_next_lv_limit)
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Protocol.Response'].Read(input, data)
	data.s2c_left_mins = input:GetS32()
	data.s2c_overflow_exp = input:GetS64()
	data.s2c_cur_lv_limit = input:GetS32()
	data.s2c_next_lv_limit = input:GetS32()
end


