
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Data.GuildGiftSnapData


local _M = {MessageID = 0x0008700B,Name = 'TLProtocol.Protocol.Data.GuildGiftSnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x0008700B] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Data.GuildGiftSnapData'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.giftLv)
	output:PutS32(data.giftLvExp)
	output:PutS32(data.giftOpenExp)
	output:PutS32(data.nextGiftId)
	output:PutList(data.giftList, output.PutOBJ,'TLProtocol.Protocol.Data.GuildGiftItemSnapData')
end


function _M.Read(input,data)
		
	data.giftLv = input:GetS32()
	data.giftLvExp = input:GetS32()
	data.giftOpenExp = input:GetS32()
	data.nextGiftId = input:GetS32()
	data.giftList = input:GetList(input.GetOBJ,'TLProtocol.Protocol.Data.GuildGiftItemSnapData')
end


