
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.EntityItemData


local _M = {MessageID = 0x00023003,Name = 'TLProtocol.Data.EntityItemData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00023003] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.EntityItemData'] = _M

function _M.Write(output,data)
		
	output:PutOBJ(data.SnapData,'TLProtocol.Data.ItemSnapData')
	output:PutOBJ(data.Properties,'TLProtocol.Data.ItemPropertiesData')
	output:PutBool(data.CanTrade)
end


function _M.Read(input,data)
		
	data.SnapData = input:GetOBJ('TLProtocol.Data.ItemSnapData')
	data.Properties = input:GetOBJ('TLProtocol.Data.ItemPropertiesData')
	data.CanTrade = input:GetBool()
end


