
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.AchievementDataSnap


local _M = {MessageID = 0x000401F4,Name = 'TLProtocol.Data.AchievementDataSnap'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x000401F4] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.AchievementDataSnap'] = _M

function _M.Write(output,data)
		
	output:PutS32(data.id)
	output:PutList(data.progressList, output.PutOBJ,'TLProtocol.Data.TLProgressData')
	output:PutS32(data.state)
	output:PutS32(data.type)
	output:PutS32(data.rank)
	output:PutDateTime(data.finishTime)
end


function _M.Read(input,data)
		
	data.id = input:GetS32()
	data.progressList = input:GetList(input.GetOBJ,'TLProtocol.Data.TLProgressData')
	data.state = input:GetS32()
	data.type = input:GetS32()
	data.rank = input:GetS32()
	data.finishTime = input:GetDateTime()
end


