
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Protocol.Data.GuildApplySnapData


local _M = {MessageID = 0x00087006,Name = 'TLProtocol.Protocol.Data.GuildApplySnapData'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00087006] = _M
Protocol.Serializer.StringDefined['TLProtocol.Protocol.Data.GuildApplySnapData'] = _M

function _M.Write(output,data)
		
	output:PutUTF(data.msgId)
	output:PutUTF(data.roleId)
	output:PutUTF(data.name)
	output:PutS32(data.level)
	output:PutS32(data.gender)
	output:PutS32(data.pro)
	output:PutS64(data.power)
	output:PutBool(data.online)
end


function _M.Read(input,data)
		
	data.msgId = input:GetUTF()
	data.roleId = input:GetUTF()
	data.name = input:GetUTF()
	data.level = input:GetS32()
	data.gender = input:GetS32()
	data.pro = input:GetS32()
	data.power = input:GetS64()
	data.online = input:GetBool()
end


