
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件

-- ThreeLives.Client.Protocol, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
-- TLProtocol.Data.TLRoleSnap


local _M = {MessageID = 0x00062004,Name = 'TLProtocol.Data.TLRoleSnap'}
_M.__index = _M
function _M.IsSuccess(self)
	return self.s2c_code == 200
end
Protocol.Serializer[0x00062004] = _M
Protocol.Serializer.StringDefined['TLProtocol.Data.TLRoleSnap'] = _M

function _M.Write(output,data)
	Protocol.Serializer.StringDefined['DeepMMO.Data.RoleSnap'].Write(output, data)
	output:PutS64(data.FightPower)
	output:PutU8(data.UnitPro)
	output:PutU8(data.Gender)
	output:PutS32(data.PracticeLv)
	output:PutUTF(data.GuildId)
	output:PutUTF(data.GuildName)
	output:PutDateTime(data.LastOfflineTime)
	output:PutUTF(data.ZoneUUID)
	output:PutS32(data.MapTemplateID)
	output:PutList(data.AvatarInfo, output.PutOBJ,'TLProtocol.Data.AvatarInfoSnap')
	output:PutS32(data.AvatarScore)
	output:PutDateTime(data.ExpiredUtc)
	output:PutS32(data.MaxDemonTowerLayer)
	output:PutDateTime(data.MaxDemonTowerDateTime)
	output:PutS32(data.TitleID)
	output:PutS32(data.MasterId)
	output:PutU64(data.Copper)
	output:PutU64(data.Sliver)
	output:PutS64(data.GodScore)
	output:PutS64(data.MountScore)
	output:PutS64(data.ArtifactScore)
	output:PutS64(data.WingScore)
	output:PutS64(data.MeridiansScore)
	output:PutS32(data.CPTowerLayer)
	output:PutMap(data.Options, output.PutUTF, output.PutUTF,'string', 'string')
end


function _M.Read(input,data)
	Protocol.Serializer.StringDefined['DeepMMO.Data.RoleSnap'].Read(input, data)
	data.FightPower = input:GetS64()
	data.UnitPro = input:GetU8()
	data.Gender = input:GetU8()
	data.PracticeLv = input:GetS32()
	data.GuildId = input:GetUTF()
	data.GuildName = input:GetUTF()
	data.LastOfflineTime = input:GetDateTime()
	data.ZoneUUID = input:GetUTF()
	data.MapTemplateID = input:GetS32()
	data.AvatarInfo = input:GetList(input.GetOBJ,'TLProtocol.Data.AvatarInfoSnap')
	data.AvatarScore = input:GetS32()
	data.ExpiredUtc = input:GetDateTime()
	data.MaxDemonTowerLayer = input:GetS32()
	data.MaxDemonTowerDateTime = input:GetDateTime()
	data.TitleID = input:GetS32()
	data.MasterId = input:GetS32()
	data.Copper = input:GetU64()
	data.Sliver = input:GetU64()
	data.GodScore = input:GetS64()
	data.MountScore = input:GetS64()
	data.ArtifactScore = input:GetS64()
	data.WingScore = input:GetS64()
	data.MeridiansScore = input:GetS64()
	data.CPTowerLayer = input:GetS32()
	data.Options = input:GetMap(input.GetUTF, input.GetUTF,'string', 'string')
end


