
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"Key","Value",},
["button"] = {"button","/res/sound/static/uisound/sd_button.assetbundles",},
["togglebutton"] = {"togglebutton","/res/sound/static/uisound/sd_button.assetbundles",},
["scrollpan"] = {"scrollpan","/res/sound/static/uisound/sd_updown.assetbundles",},
["uiopen"] = {"uiopen","/res/sound/static/uisound/sd_interface_open.assetbundles",},
["zhandouli"] = {"zhandouli","/res/sound/static/uisound/sd_zhandouli.assetbundles",},
["zhuangbei"] = {"zhuangbei","/res/sound/static/uisound/sd_zhuangbeitankuang.assetbundles",},
["shanzikai"] = {"shanzikai","/res/sound/static/uisound/sd_shanzizhankai.assetbundles",},
["shanziguan"] = {"shanziguan","/res/sound/static/uisound/sd_shanzishouqi.assetbundles",},
["jiaobu1"] = {"jiaobu1","/res/sound/static/uisound/sd_jiaobu1.assetbundles",},
["jiaobu2"] = {"jiaobu2","/res/sound/static/uisound/sd_jiaobu2.assetbundles",},
["talkbutton"] = {"talkbutton","/res/sound/static/uisound/sd_renwuduibai.assetbundles",},
["drop"] = {"drop","/res/sound/static/uisound/sd_drop.assetbundles",},
["gongnengshengji"] = {"gongnengshengji","/res/sound/static/uisound/sd_gongnengshengji.assetbundles",},
["shenqijiesuo"] = {"shenqijiesuo","/res/sound/static/uisound/sd_shenqijiesuo.assetbundles",},
["dianliang"] = {"dianliang","/res/sound/static/uisound/sd_dianliang.assetbundles",},
["jinjie"] = {"jinjie","/res/sound/static/uisound/sd_jinjie.assetbundles",},
["baoshi"] = {"baoshi","/res/sound/static/uisound/sd_baoshi.assetbundles",},
["shuxingshuaxin"] = {"shuxingshuaxin","/res/sound/static/uisound/sd_shuxingshuaxin.assetbundles",},
["chengjiutips"] = {"chengjiutips","/res/sound/static/uisound/chengjiu.assetbundles",},

}
