---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2019/1/9 18:22
---修为排行

local _M = {}
_M.__index = _M

local Util = require 'Logic/Util'
local UIUtil = require 'UI/UIUtil'
local ActivityModel = require('Model/ActivityModel')
local ItemModel = require 'Model/ItemModel'
local RankModel = require 'Model/RankModel'
local ServerTime = require 'Logic/ServerTime'
local TimeUtil = require 'Logic/TimeUtil'

function _M.OnInit(self)

end


--加载/卸载模型
local function Load3DModel(self)
    local cvs_anchor={}
    self.model={}
    cvs_anchor[1]=self.ui.comps.cvs_model1
    cvs_anchor[2]=self.ui.comps.cvs_model2
    for i = 1, #self.rankInfo[1].showmodel do
        if string.IsNullOrEmpty(self.rankInfo[1].showmodel[i]) then
            return
        end
        local fixposdata=string.split(self.rankInfo[1].pos_xy[i],',')
        local fixpos = {x = tonumber(fixposdata[1]),y = tonumber(fixposdata[2])}
        local info = UI3DModelAdapter.AddSingleModel(
                cvs_anchor[i],
                Vector2(fixpos.x,fixpos.y),
                tonumber(self.rankInfo[1].zoom[i]),
                self.ui.menu.MenuOrder,
                self.rankInfo[1].showmodel[i])
        self.model[i] = info
        info.Callback = function (info2)
            local trans2 = info2.RootTrans
            trans2:Rotate(Vector3.up,self.rankInfo[1].rotate[i])
        end
    end
end

local function Release3DModel(self)
    for i, v in ipairs(self.model) do
        if self.model[i] then
            UI3DModelAdapter.ReleaseModel(self.model[i].Key)
            self.model[i] = nil
        end
    end
    self.model = {}
end


local function InitReward(self)

    self.comps.lb_yourpowernum.Text = DataMgr.Instance.UserData:GetAttribute(UserData.NotiFyStatus.FIGHTPOWER)
    --加载称号和模型
    Load3DModel(self)

--[[    local endTime = DataMgr.Instance.UserData.Serverinfo.open_at:AddDays(GameUtil.GetIntGameConfig("openmaxday"))
    if endTime.Minute == 0 and endTime.Second == 0 then
        endTime = endTime - ServerTime.getServerTime():ToLocalTime()
    else
        endTime = endTime:AddHours(1):AddMinutes(-endTime.Minute):AddSeconds(-endTime.Second)- ServerTime.getServerTime():ToLocalTime()
    end
    self.comps.lb_surplustime.Text =TimeUtil.FormatToAllCN2(endTime.TotalSeconds)]]

    local rank = 0
    --获取综合的修为排行
    RankModel.GetRankListDetail(2,1,function (rsp)
        if rsp.s2c_list then
            for i, v in ipairs(rsp.s2c_list) do
                if v.id == DataMgr.Instance.UserData.RoleID then
                    rank = i
                    break
                end
            end
        end
        self.comps.lb_yourranknum.Text = rank ==0 and Constants.RankList.RankName or Util.GetText('guild_fort_rank',rank)
    end)

    self.comps.btn_get.TouchClick = function()
        GlobalHooks.UI.OpenUI("RankMain",0)
    end
end


local function SetRewardItem(self,data,node,index)
    local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(data.item[index]))
    local quality = itemdetail.static.quality
    local icon=itemdetail.static.atlas_id
    local number=tonumber(data.itemnum[index])
    local itshow=UIUtil.SetItemShowTo(node,icon,quality,number)
    itshow.EnableTouch = true
    itshow.TouchClick = function()
        UIUtil.ShowNormalItemDetail({x=node.X+250,y=node.Y+120,detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
    end
end

local function SetEachRank(self,node,index)
    local lb_rank = node:FindChildByEditName('lb_rank',true)
    lb_rank.Text =Util.GetText(self.rankInfo[index].rank_name)
    --设置每档物品奖励
    local sp_itemlist =node:FindChildByEditName('sp_itemlist',true)
    local cvs_rewarditem =node:FindChildByEditName('cvs_rewarditem',true)
    cvs_rewarditem.Visible=false
    local function eachupdatecb(node1,index1)
        SetRewardItem(self,self.rankInfo[index].show,node1,index1)
    end
    UIUtil.ConfigHScrollPan(sp_itemlist,cvs_rewarditem,#self.rankInfo[index].show.item,eachupdatecb)
end

local function InitPowerScrollPan(self)
    self.comps.cvs_info.Visible = false
    local function eachupdatecb(node,index)
        SetEachRank(self,node,index)
    end
    UIUtil.ConfigVScrollPan(self.comps.sp_ranklist,self.comps.cvs_info,#self.rankInfo,eachupdatecb)
end


function _M.OnEnter(self)
    self.rankInfo = ActivityModel.GetPowerRankInfo()
    InitPowerScrollPan(self)
    InitReward(self)
end


function _M.OnExit(self)
    Release3DModel(self)
end


return _M