---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/10/24 10:53
---成长基金  RechargeFund
local _M = {}
_M.__index = _M

local UIUtil = require 'UI/UIUtil'
local Util = require 'Logic/Util'
local RechargeModel=require('Model/RechargeModel')
local ItemModel = require 'Model/ItemModel'
local BusinessModel = require('Model/BusinessModel')


local ReceiveState={
    NoReceive = 0, --不可领取
    CanReceive = 1, --可领取
    HasReceived= 2 --已领取
}


function _M.OnInit(self,params)
    if type(params) == "table" then
        self.fundActivityType = params.activitytype
        self.allActivityType = params.activitytype
    else
        self.fundActivityType = params
        self.allActivityType = params
    end
    self.ui.menu:SetCompAnime(self.ui.menu, UIAnimeType.NoAnime)
    self.lb_pricenum=self.comps.lb_pricenum
    self.lb_bought=self.comps.lb_bought
    self.btn_price=self.comps.btn_price
    self.btn_mycard=self.comps.btn_mycard
end


--通过id来查找相关数据
local function MatchDataById(self,tab,id)
    for k, v in pairs(tab) do
        if k==id then
            return v
        end
    end
end


--设置奖励预览
local function ShowGift(node,table,i)
    --获取品质和数量
    local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(table.item[i]))
    local quality = itemdetail.static.quality
    local icon=itemdetail.static.atlas_id
    local number=tonumber(table.itemnum[i])
    local itshow=UIUtil.SetItemShowTo(node,icon,quality,number)
    itshow.EnableTouch = true
    itshow.TouchClick = function()
        UIUtil.ShowNormalItemDetail({detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
    end
end


--释放模型
local function Release3DModel(self)
    if self.model then
        UI3DModelAdapter.ReleaseModel(self.model.Key)
        self.model = nil
    end
end


local function Init3DEffect(self,anc)
    --拆分坐标&偏移坐标
    local fixposdata=string.split(self.fundProduct.pos_xy,',')
    local fixpos = {x = tonumber(fixposdata[1]),y = tonumber(fixposdata[2])}

    local info = UI3DModelAdapter.AddSingleModel(
            anc,
            Vector2(fixpos.x,fixpos.y),
            tonumber(self.fundProduct.zoom),
            self.ui.menu.MenuOrder,
            self.fundProduct.show_model)
    self.model = info
    --初始旋转角度
    info.Callback = function (info2)
        local trans2 = info2.RootTrans
        trans2:Rotate(Vector3.up,self.fundProduct.rotate)
    end
end


--设置模型和对话
local function InitModelAndTalk(self,node)
    local cvs_model=node:FindChildByEditName('cvs_model',true)
    local cvs_anchor=cvs_model:FindChildByEditName('cvs_anchor',true)
    local cvs_talk=cvs_model:FindChildByEditName('cvs_talk',true)
    cvs_talk.Visible=true
    if self.model == nil then
        Init3DEffect(self,cvs_anchor)
    end
end

--设置成长基金详细页
local function SetInfoDetail(self,node,index)

    local reward=MatchDataById(self,self.fundreward,self.funddata[index].id)

    local lb_flevel=node:FindChildByEditName('lb_flevel',true)
    lb_flevel.Text=Util.GetText('gem_locklv_format',self.funddata[index].lbtext)

    local lb_fcondition=node:FindChildByEditName('lb_fcondition',true)
    lb_fcondition.Text=DataMgr.Instance.UserData.Level..'/'..self.funddata[index].lbtext
    lb_fcondition.FontColor=(
            DataMgr.Instance.UserData.Level >= self.funddata[index].lbtext
                    and {GameUtil.RGB2Color(Constants.Color.Green4)}
                    or {GameUtil.RGB2Color(Constants.Color.Red)})[1]

    local btn_get=node:FindChildByEditName('btn_get',true)
    local lb_fgot=node:FindChildByEditName('lb_fgot',true)
    --红点
    local lb_fundtip=node:FindChildByEditName('lb_fundtip',true)
    
    lb_fgot.Visible= reward.state == ReceiveState.HasReceived --当状态为已领取时
    btn_get.Visible= reward.state == ReceiveState.CanReceive --当状态可领取时
    lb_fcondition.Visible = reward.state == ReceiveState.NoReceive --当状态不可领取时

    if btn_get.Visible then
        GlobalHooks.UI.ShowRedPoint(lb_fundtip, 1, 'fundbtnget')
    else
        GlobalHooks.UI.ShowRedPoint(lb_fundtip, 0, 'fundbtnget')
    end

    local cvs_item={}
    for i = 1, #self.funddata[index].show.item do
        cvs_item[i]=node:FindChildByEditName('cvs_item'..i,true)
        cvs_item[i].Visible= self.funddata[index].show.item[i] ~= 0
        if self.funddata[index].show.item[i] ~=0 then
            ShowGift(cvs_item[i],self.funddata[index].show,i)
        end
    end

    --领取
    btn_get.TouchClick=function(sender)
        BusinessModel.RequireGet(self.fundActivityType,self.fundActivityId,self.funddata[index].id,function (rsp)
            GlobalHooks.UI.OpenUI('GainItem',0,self.funddata[index].reward.item,5)
            lb_fgot.Visible=true
            btn_get.Visible=false
            --设置红点以及改变领取状态
            GlobalHooks.UI.ShowRedPoint(self.comps.lb_fundred,0,'fundtog')
            self.fundreward[self.funddata[index].id].state=ReceiveState.HasReceived
            for k, v in pairs(self.fundreward) do
                if v.state == ReceiveState.CanReceive then
                    GlobalHooks.UI.ShowRedPoint(self.comps.lb_fundred, 1, 'fundtog')
                    break
                end
            end
            self.ui.comps.sp_list:RefreshShowCell()
        end,self)
    end
end

--初始化成长基金标题
local function InitInfoTitle(self,node)

    self.lb_pricenum.Text=self.fundProduct.show_price
    --购买基金按钮
    self.btn_price.Visible =  (self.buyCount or 0) == 0 and (self.mycardbuyCount or 0) == 0 -- and RechargeModel.ShowRechargeBtn
    self.btn_mycard.Visible = RechargeModel.ShowRechargeBtn and (self.buyCount or 0) == 0 and (self.mycardbuyCount or 0) == 0
    self.lb_bought.Visible = (self.buyCount or 0) > 0 or (self.mycardbuyCount or 0) > 0
    
    self.btn_price.Text = Util.GetText('vip_reward_buy')
    
    self.btn_price.TouchClick=function(sender)
        local needsignature = OneGameSDK.Instance:GetPlatformData():GetInt(SDKAttName.NEED_SIGN)
        local queryOrder = OneGameSDK.Instance:GetPlatformData():GetInt(SDKAttName.QUERY_ORDER)
        RechargeModel.RequestRechargeBySellId(self.fundProduct.id,OneGameSDK.Instance.PlatformID,needsignature,queryOrder,function (rsp)
            local ord=rsp.s2c_ext_data
            RechargeModel.SDKPayment(ord,queryOrder,OneGameSDK.Instance.PlatformID)--SDK相关支付流程
        end)
    end
    --mycard渠道
    self.btn_mycard.TouchClick=function(sender)
        local needsignature = OneGameSDK.Instance:GetPlatformData():GetInt(SDKAttName.NEED_SIGN)
        local queryOrder = OneGameSDK.Instance:GetPlatformData():GetInt(SDKAttName.QUERY_ORDER)
        RechargeModel.RequestRechargeBySellId(self.mycardfundProduct.id,RechargeModel.MyCardPlatformID,needsignature,queryOrder,function (rsp)
            local ord=rsp.s2c_ext_data
            RechargeModel.SDKPayment(ord,queryOrder,RechargeModel.MyCardPlatformID)--SDK相关支付流程
        end)
    end
end

local function fucking(self,node)
    self.inittime = self.inittime - 1
    if self.inittime == 0 then
        InitInfoTitle(self,node)
        InitModelAndTalk(self,node)
    end
end

--初始化成长基金页面
local function InitInfo(self,node)
    --请求2个渠道的成长基金信息
    RechargeModel.RequestFundInfo(OneGameSDK.Instance.PlatformID,function (rsp)
        for k, v in pairs(rsp.s2c_map) do
            self.buyCount=v
            self.fundProduct=RechargeModel.GetFundProductById(k)
        end
        fucking(self,node)
    end)
    RechargeModel.RequestFundInfo(RechargeModel.MyCardPlatformID,function (rsp)
        for k, v in pairs(rsp.s2c_map) do
            self.mycardbuyCount=v
            self.mycardfundProduct=RechargeModel.GetFundProductById(k)
        end
        fucking(self,node)
    end)
    
    local sp_list=node:FindChildByEditName('sp_list',true)
    local cvs_class=node:FindChildByEditName('cvs_class',true)
    cvs_class.Visible=false

    self.funddata=RechargeModel.GetAllFundData()
    BusinessModel.RequireData(self.fundActivityType,self.fundActivityId,function (rsp)
        self.fundreward=rsp.activityMap
        --检测是否有红点
        GlobalHooks.UI.ShowRedPoint(self.comps.lb_fundred, 0, 'fundtog')
        for k, v in pairs(self.fundreward) do
            if v.state == ReceiveState.CanReceive then
                GlobalHooks.UI.ShowRedPoint(self.comps.lb_fundred, 1, 'fundtog')
                break
            end
        end
        local function UpdateElement(node,index)
            SetInfoDetail(self,node,index)
        end
        UIUtil.ConfigVScrollPan(sp_list,cvs_class,#self.funddata,UpdateElement)
    end)
end


--初始化全面福利详细页
local function SetFuliDetail(self,node,index)

    local reward=MatchDataById(self,self.allplayreward,self.fundplayer[index].id)

    local lb_anum=node:FindChildByEditName('lb_anum',true)
    lb_anum.Text=self.fundplayer[index].lbtext

    local lb_acondition=node:FindChildByEditName('lb_acondition',true)
    lb_acondition.Text=tostring(self.buyPeople)..'/'..tostring(self.fundplayer[index].lbtext)

    local btn_get=node:FindChildByEditName('btn_get',true)
    local lb_agot=node:FindChildByEditName('lb_agot',true)
    
    local lb_fulitip=node:FindChildByEditName('lb_fulitip',true)
    
    lb_agot.Visible= reward.state == ReceiveState.HasReceived --当状态为已领取时
    btn_get.Visible= reward.state == ReceiveState.CanReceive --当状态可领取时
    lb_acondition.Visible = reward.state == ReceiveState.NoReceive --当状态不可领取时
    
    if btn_get.Visible then
        GlobalHooks.UI.ShowRedPoint(lb_fulitip, 1, 'allplaybtnget')
    else
        GlobalHooks.UI.ShowRedPoint(lb_fulitip, 0, 'allplaybtnget')
    end
    
    local cvs_item={}
    for i = 1, #self.fundplayer[index].show.item do
        cvs_item[i]=node:FindChildByEditName('cvs_item'..i,true)
        cvs_item[i].Visible= self.fundplayer[index].show.item[i] ~= 0
        if self.fundplayer[index].show.item[i] ~=0 then
            ShowGift(cvs_item[i],self.fundplayer[index].show,i)
        end
    end

    --领取全民福利
    btn_get.TouchClick=function(sender)
        BusinessModel.RequireGet(self.allActivityType,self.allActivityId,self.fundplayer[index].id,function (rsp)
            GlobalHooks.UI.OpenUI('GainItem',0,self.fundplayer[index].reward.item,5)
            lb_agot.Visible=true
            btn_get.Visible=false
            --全民福利红点逻辑
            GlobalHooks.UI.ShowRedPoint(self.comps.lb_fulired,0,'alltog')
            self.allplayreward[self.fundplayer[index].id].state=ReceiveState.HasReceived
            for k, v in pairs(self.allplayreward) do
                if v.state == ReceiveState.CanReceive then
                    GlobalHooks.UI.ShowRedPoint(self.comps.lb_fulired,1,'alltog')
                    break
                end
            end
            self.ui.comps.sp_list2:RefreshShowCell()
        end,self)
    end
end

--初始化全面福利标题
local function InitFuliTitle(self,node)
    local cvs_title=node:FindChildByEditName('cvs_title',true)
    local lb_anum=cvs_title:FindChildByEditName('lb_anum',true)
    lb_anum.Text=self.buyPeople
end

--初始化全面福利页面
local function InitFuli(self,node)
    
    local sp_list2=node:FindChildByEditName('sp_list2',true)
    local cvs_class=node:FindChildByEditName('cvs_class',true)
    cvs_class.Visible=false

    self.buyPeople=0
    self.fundplayer=RechargeModel.GetAllFundPlayerData()
    BusinessModel.RequireData(self.allActivityType,self.allActivityId,function (rsp)
        self.allplayreward=rsp.activityMap
        for k, v in pairs(rsp.activityMap) do
            if v.requireList and v.requireList[1] then
                self.buyPeople = v.requireList[1].curVal
                break
            end
        end

        GlobalHooks.UI.ShowRedPoint(self.comps.lb_fulired,0,'alltog')
        for k, v in pairs(self.allplayreward) do
            if v.state == ReceiveState.CanReceive then
                GlobalHooks.UI.ShowRedPoint(self.comps.lb_fulired, 1, 'alltog')
                break
            end
        end

        InitFuliTitle(self,node)

        local function UpdateElement(node,index)
            SetFuliDetail(self,node,index)
        end
        UIUtil.ConfigVScrollPan(sp_list2,cvs_class,#self.fundplayer,UpdateElement)
    end)
end


--购买成长基金后，刷新界面
local function UpdateInterface(self,eventname, params)
    self.ui.comps.btn_price.Visible=false
    self.ui.comps.btn_mycard.Visible=false
    self.ui.comps.lb_bought.Visible=true
    BusinessModel.RequireData(self.fundActivityType,self.fundActivityId,function (rsp)
        self.fundreward=rsp.activityMap
        --红点显示逻辑
        GlobalHooks.UI.ShowRedPoint(self.comps.lb_fundred,0,'fundtog')
        for k, v in pairs(self.fundreward) do
            if v.state == ReceiveState.CanReceive then
                GlobalHooks.UI.ShowRedPoint(self.comps.lb_fundred, 1, 'fundtog')
                break
            end
        end
        self.ui.comps.sp_list:RefreshShowCell()
    end)
end


function _M.OnEnter(self,params)
    --缓冲次数
    self.inittime = 2 
    --成长基金id
    self.fundActivityId=params or 11
    --全民福利id
    self.allActivityId=13

    local function ToggleFunc(sender)
        if sender:Equals(self.ui.comps.tbn_an1) then
            self.ui.comps.cvs_info.Visible=true
            self.ui.comps.cvs_fuli.Visible=false
        elseif sender:Equals(self.ui.comps.tbn_an2) then
            self.ui.comps.cvs_info.Visible=false
            self.ui.comps.cvs_fuli.Visible=true
        end
    end
    UIUtil.ConfigToggleButton({self.ui.comps.tbn_an1,self.ui.comps.tbn_an2}, self.ui.comps.tbn_an1, false, ToggleFunc)
    InitInfo(self,self.ui.comps.cvs_info)
    InitFuli(self,self.ui.comps.cvs_fuli)

    function _M.OnUpdateInterface(eventname, params)
        UpdateInterface(self,eventname, params)
    end
    EventManager.Subscribe('Event.Recharge.FundInfoUIUpdate',_M.OnUpdateInterface)
end


function _M.OnExit(self)
    Release3DModel(self)
    EventManager.Unsubscribe('Event.Recharge.FundInfoUIUpdate',_M.OnUpdateInterface)
end


return _M