---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/10/23 10:15
---累计充值
local _M = {}
_M.__index = _M

local UIUtil = require('UI/UIUtil')
local Util = require('Logic/Util')
local BusinessModel = require('Model/BusinessModel')
local ItemModel = require 'Model/ItemModel'

local ReceiveState={
    NoReceive = 0, --不可领取
    CanReceive = 1, --可领取
    HasReceived= 2 --已领取
}


function _M.OnInit(self,activityinfo)
    self.AllAccdata = activityinfo
    self.ui.menu:SetCompAnime(self.ui.menu, UIAnimeType.NoAnime)
end


--通过id来查找相关数据
local function MatchDataById(self,id)
    for k, v in pairs(self.reward) do
        if k==id then
            return v
        end
    end
end


--领取奖励特效
local function CanGetEffect(self,parent,index,node)
    local transSet = TransformSet()
    transSet.LayerOrder = self.menu.MenuOrder
    transSet.Layer = Constants.Layer.UI
    transSet.Parent = parent.Transform
    transSet.Scale = Vector3(0.9,0.9,1)
    transSet.Pos = Vector3(parent.Width/2,-parent.Height/2+2,-200)
    transSet.Clip=self.ui.comps.sp_list.Transform
    self.effect = self.effect or {}
    node.UserTag = RenderSystem.Instance:LoadGameObject('/res/effect/ui/ef_ui_frame_01.assetbundles', transSet,function (aoe)
        self.effect[index] = aoe.gameObject
    end)
end

--释放特效
local function ReleaseAll3DEffect(self)
    if self.effect then
        for _, val in pairs(self.effect) do
            RenderSystem.Instance:Unload(val)
        end
        self.effect = {}
    end
end


local function SetItemDetail(self,node,itemid,itemnum)
    if itemid == 0 then
        node.Visible=false
        return
    end
    local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(itemid))
    local quality = itemdetail.static.quality
    local icon=itemdetail.static.atlas_id
    local itshow=UIUtil.SetItemShowTo(node,icon,quality,itemnum)
    itshow.EnableTouch = true
    itshow.TouchClick = function()
        UIUtil.ShowNormalItemDetail({x=220,y=node.Y+280,detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
    end
end


--设置每个子控件
local function SetDetail(self,node,index)
    local lb_addup=node:FindChildByEditName('lb_addup',true)
    local gg_buy=node:FindChildByEditName('gg_buy',true)
    local btn_get=node:FindChildByEditName('btn_get',true)
    local ib_got=node:FindChildByEditName('ib_got',true)
    local sp_itemlist=node:FindChildByEditName('sp_itemlist',true)
    local cvs_buy=node:FindChildByEditName('cvs_buy',true)
    local cvs_showreward=node:FindChildByEditName('cvs_showreward',true)
    cvs_showreward.Visible=false
    
    local function Update(node,index2)
        SetItemDetail(self,node,self.accdata[index].show.item[index2],self.accdata[index].show.itemnum[index2])
    end
    UIUtil.ConfigHScrollPan(sp_itemlist,cvs_showreward,#self.accdata[index].show.item,Update)
    
    local info= MatchDataById(self,self.accdata[index].id)
    ib_got.Visible= info.state == ReceiveState.HasReceived --当状态为已领取时
    btn_get.Visible= info.state == ReceiveState.CanReceive --当状态可领取时
    cvs_buy.Visible = info.state == ReceiveState.NoReceive --当状态不可领取时
    
    lb_addup.Text=Util.GetText(self.accdata[index].lbtext)
    gg_buy.Text=tostring(info.requireList[1].curVal)..'/'..tostring(info.requireList[1].minVal)
    
    --领取奖励按钮&特效
    if node.UserTag == 0 and info.state == ReceiveState.CanReceive then
        CanGetEffect(self,btn_get,index,node)
    end
    if info.state == ReceiveState.CanReceive then
        if self.effect[index] then
            self.effect[index]:SetActive(true)
        end
    else
        if self.effect[index] then
            self.effect[index]:SetActive(false)
        end
    end
    
    btn_get.TouchClick=function (sender)
        BusinessModel.RequireGet(self.activitytype,self.activityId,self.accdata[index].id,function (rsp)
            GlobalHooks.UI.OpenUI('GainItem',0,self.accdata[index].reward.item,5)
            ib_got.Visible=true
            btn_get.Visible=false
            info.state = ReceiveState.HasReceived
            self.parentui.pan:RefreshShowCell()
        end,self)
    end
end

--                                      参数为activityId
function _M.OnEnter(self,params)
    self.activityId=params
    local actInfo = BusinessModel.GetActivityByActivityId(self.activityId)
    self.activitytype = actInfo.activity_type
    
    self.accdata={}
    self.ui.comps.cvs_reward.Visible=false
    BusinessModel.RequireData(self.activitytype,self.activityId,function (rsp)
        self.reward=rsp.activityMap
        self.effect={}
        
        --为新活动准备的
        for i = 1, #self.AllAccdata do
            if self.AllAccdata[i].activity_id == self.activityId then
                table.insert(self.accdata,self.AllAccdata[i])
            end
        end
        table.sort(self.accdata,function (a,b)
            return a.order < b.order
        end)
        local function UpdateElement(node,index)
            SetDetail(self,node,index)
        end
        UIUtil.ConfigVScrollPanWithOffset(self.ui.comps.sp_list, self.ui.comps.cvs_reward,#self.accdata,6,UpdateElement)
    end)
end


function _M.OnExit(self)
    ReleaseAll3DEffect(self)
    GlobalHooks.UI.SetRedTips(BusinessModel.GetRedKey(self.activitytype),BusinessModel.cachedata[self.activitytype][self.activityId].count,self.activityId)
end


return _M