---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2019/1/17 20:55
---白凤九活动

local _M = {}
_M.__index = _M

local RechargeModel = require 'Model/RechargeModel'

function _M.OnInit(self)

end

local function InitBuyBtn(self)
    
    self.productID = 0
    if OneGameSDK.Instance.PlatformID == 0 or OneGameSDK.Instance.PlatformID == 2001 then--pc或者google
        self.productID = 2033
    elseif OneGameSDK.Instance.PlatformID == 2101 then --ios
        self.productID = 2034
    elseif OneGameSDK.Instance.PlatformID == 2002 then --mycard
        self.productID = 2035
    end
    
    for k, v in pairs(self.allInfo) do
        if k == self.productID then
            self.productInfo = v
            break
        end
    end
    
    if not self.productInfo then
        UnityEngine.Debug.LogError("productId is not exist,Please Check OneGameSDK.Instance.PlatformID")
        return
    end
    
    self.comps.btn_get.Visible = self.productInfo.s2c_buy_count == 0
    self.comps.btn_get.Enable = self.productInfo.s2c_buy_count == 0
    self.comps.lb_got.Visible = self.productInfo.s2c_buy_count > 0
    
    self.comps.btn_get.TouchClick =function()
        local needsignature = OneGameSDK.Instance:GetPlatformData():GetInt(SDKAttName.NEED_SIGN)
        local queryOrder = OneGameSDK.Instance:GetPlatformData():GetInt(SDKAttName.QUERY_ORDER)
        RechargeModel.RequestRechargeBySellId(self.productID,RechargeModel.GetRechargePlatformID(false),needsignature,queryOrder,function (rsp)
            local ord=rsp.s2c_ext_data
            RechargeModel.SDKPayment(ord,queryOrder,RechargeModel.GetRechargePlatformID(false))
            self.comps.lb_got.Visible = true
            self.comps.btn_get.Enable = false
        end)
    end
end

function _M.OnEnter(self)
    RechargeModel.RequestRechargeInfo(OneGameSDK.Instance.PlatformID,function(rsp)
        self.allInfo=rsp.s2c_data
        InitBuyBtn(self)
    end)
end

function _M.OnExit(self)

end


return _M