---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2019/1/3 17:23
---开服活动--七日活动

local _M = {}
_M.__index = _M

local ItemModel = require 'Model/ItemModel'
local UIUtil = require 'UI/UIUtil'
local ActivityModel = require('Model/ActivityModel')
local Util = require 'Logic/Util'
local TimeUtil = require 'Logic/TimeUtil'
local ServerTime = require 'Logic/ServerTime'


function _M.OnInit(self)
    
end

--加载任务领取奖励特效
local function PlayEffect(self,parent,pos,scale,filename)
    local transSet = {}
    transSet.Pos = pos
    transSet.Scale = scale
    transSet.Parent = parent.Transform
    transSet.Layer = Constants.Layer.UI
    transSet.LayerOrder = self.ui.menu.MenuOrder
    transSet.Clip = self.comps.sp_list.Transform
    self.eff = self.eff or {}
    local num = #self.eff + 1
    self.eff[num] = Util.PlayEffect(filename,transSet,true)
end
local function ReleaseEffect(self)
    if self.eff then
        for i, v in ipairs(self.eff) do
            RenderSystem.Instance:Unload(self.eff[i])
        end
        self.eff = {}
    end
end

--加载积分的特效
local function PlayScoreEffect(self,parent,pos,scale,filename)
    local transSet = {}
    transSet.Pos = pos
    transSet.Scale = scale
    transSet.Parent = parent.Transform
    transSet.Layer = Constants.Layer.UI
    transSet.LayerOrder = self.ui.menu.MenuOrder
    self.effScore = self.effScore or {}
    local num = #self.effScore + 1
    self.effScore[num] = Util.PlayEffect(filename,transSet,true)
    return num
end
local function ReleaseScoreEffect(self,num)
    if num then
        RenderSystem.Instance:Unload(self.effScore[num])
    else
        if self.effScore then
            for i, v in ipairs(self.effScore) do
                RenderSystem.Instance:Unload(self.effScore[i])
            end
            self.effScore = {}
        end
    end
end

--加载任务领取奖励特效
local function PlayClickEffect(self,parent,pos,scale,filename)
    local transSet = {}
    transSet.Pos = pos
    transSet.Scale = scale
    transSet.Parent = parent.Transform
    transSet.Layer = Constants.Layer.UI
    transSet.LayerOrder = self.ui.menu.MenuOrder 
    Util.PlayEffect(filename,transSet)
end


--积分兑换物品
local function SetExchangeItem(self,node,index)
    
    node.Position2D =Vector2(node.Position2D.x+5,node.Position2D.y)
    
    local canGet = self.gift[index] == ActivityModel.OpeningEventType.WaitForGetReward
    
    local lb_huoli =node:FindChildByEditName('lb_huoli',true)
    lb_huoli.Text = self.scoreInfo[index].needpoint
    local ib_get = node:FindChildByEditName('ib_get',true)
    ib_get.Visible = self.gift[index] == ActivityModel.OpeningEventType.Finished
    
    --物品显示
    local cvs_exitemicon = node:FindChildByEditName('cvs_exitemicon',true)
    
    local num 
    if canGet then
        num = PlayScoreEffect(self,cvs_exitemicon,Vector3(cvs_exitemicon.Width/2,-cvs_exitemicon.Height/2,0),Vector3(0.5,1.3,1),"/res/effect/ui/ef_ui_frame_01.assetbundles")
    end
    
    local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(self.scoreInfo[index].item_show))
    local quality = itemdetail.static.quality
    local icon=itemdetail.static.atlas_id
    local number=tonumber(self.scoreInfo[index].item_show_num)
    local itshow=UIUtil.SetItemShowTo(cvs_exitemicon,icon,quality,number)
    itshow.EnableTouch = true
    itshow.TouchClick = function()
        if canGet then
            ActivityModel.RequestOpeningEventExcharge(self.scoreInfo[index].id,function (rsp)
                --重组掉落
                local drop={}
                for i, v in ipairs(rsp.s2c_data) do
                    table.insert(drop,{id = v.templateid,num = v.num})
                end
                if next(drop) then
                    GlobalHooks.UI.OpenUI('GainItem',0,drop,3)
                end
                --刷新数据
                self.gift = rsp.exchargeDataMap
                ib_get.Visible = true
                --释放对应特效
                ReleaseScoreEffect(self,num)
            end)
        else
            UIUtil.ShowNormalItemDetail({x=node.X+250,y=node.Y+120,detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
        end
    end
end

--初始化下方的积分&积分奖励
local function InitExchange(self)
    self.scoreInfo = ActivityModel.GetExchangeScore()
    self.comps.lb_num.Text = self.score
    self.comps.cvs_exchangeitem.Visible=false
    local function eachupdatecb(node,index)
        SetExchangeItem(self,node,index)
    end
    UIUtil.ConfigHScrollPanWithOffset(self.comps.sp_exchangelist,self.comps.cvs_exchangeitem,#self.scoreInfo,30,eachupdatecb)
end

--完成未领取奖励>未完成任务>已完成任务
local sortindex = {
    [ActivityModel.OpeningEventType.WaitForGetReward] = 1,
    [ActivityModel.OpeningEventType.NotCompleted] = 2,
    [ActivityModel.OpeningEventType.Finished] = 3
}
local function paixu(a,b)
    if a.state == b.state then
        return  a.id < b.id
    else
        return sortindex[a.state] < sortindex[b.state]
    end
end


local function SetEachOne(self,node,index)
    --任务名字&进度
    local lb_demand =node:FindChildByEditName('lb_demand',true)
    lb_demand.Text = Util.GetText(self.actInfo[index].desc_show)
    local lb_demandnum = node:FindChildByEditName('lb_demandnum',true)
    lb_demandnum.Visible = self.actInfo[index].progress == 1
    lb_demandnum.Text = self.progress[index].progressList[1].CurValue..'/'..self.progress[index].progressList[1].TargetValue
    
    for i = 1, 2 do
        local cvs_item = node:FindChildByEditName('cvs_item'..i,true)
        local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(self.actInfo[index].item_show[i]))
        local quality = itemdetail.static.quality
        local icon=itemdetail.static.atlas_id
        local number=tonumber(self.actInfo[index].item_show_num[i])
        local itshow=UIUtil.SetItemShowTo(cvs_item,icon,quality,number)
        itshow.EnableTouch = true
        itshow.TouchClick = function()
            UIUtil.ShowNormalItemDetail({x=cvs_item.X+250,y=cvs_item.Y+120,detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
        end
    end
    
    --前往/领取奖励
    local btn_go =node:FindChildByEditName('btn_go',true)
    local btn_receive =node:FindChildByEditName('btn_receive',true)
    local lb_got =node:FindChildByEditName('lb_got',true)
    btn_go.Visible = self.progress[index].state == ActivityModel.OpeningEventType.NotCompleted
    btn_receive.Visible = self.progress[index].state == ActivityModel.OpeningEventType.WaitForGetReward
    if btn_receive.Visible then
        PlayEffect(self,btn_receive,Vector3(btn_receive.Width/2,-btn_receive.Height/2,0),Vector3(0.9,0.9,0.9),
                '/res/effect/ui/ef_ui_frame_01.assetbundles')
    end
    lb_got.Visible = self.progress[index].state == ActivityModel.OpeningEventType.Finished
    btn_go.TouchClick = function()
        self.ui:Close()
        if not string.IsNullOrEmpty(self.actInfo[index].function_id) then
            FunctionUtil.OpenFunction(self.actInfo[index].function_id)
        else
            GlobalHooks.UI.OpenUI(self.actInfo[index].open_ui,0)
        end
    end
    btn_receive.TouchClick =function ()
        ActivityModel.RequestGetOpeningEventReward(self.actInfo[index].id,function (rsp)
            --刷新积分
            self.score = rsp.s2c_curFinishPoints
            self.comps.lb_num.Text = rsp.s2c_curFinishPoints

            PlayClickEffect(self,self.comps.cvs_effect,Vector3(0,0,0),Vector3(1,1,1),
                    '/res/effect/ui/ef_ui_xiuxing_click_01.assetbundles')

            self.progress[index].state = ActivityModel.OpeningEventType.Finished
            
            --判断当前页的红点
            for i, v in ipairs(ActivityModel.SevenOpeningRedPoint) do
                if v.id == self.actInfo[index].id then
                    table.remove(ActivityModel.SevenOpeningRedPoint,i)
                    break
                end
            end
            GlobalHooks.UI.ShowRedPoint(self.redpoint[self.actInfo[index].type],0, 'sevenday')
            if next(ActivityModel.SevenOpeningRedPoint) then
                for i, v in ipairs(ActivityModel.SevenOpeningRedPoint) do
                    if v.type == self.actInfo[index].type then
                        GlobalHooks.UI.ShowRedPoint(self.redpoint[v.type], 1, 'sevenday')
                        break
                    end
                end
            end
            
            --重组掉落
            local drop={}
            for i, v in ipairs(rsp.s2c_data) do
                table.insert(drop,{id = v.templateid,num = v.num})
            end
            if next(drop) then
                GlobalHooks.UI.OpenUI('GainItem',0,drop,3)
            end
            --领取完刷新界面
            self.actInfo = {}
            table.sort(self.progress,paixu)
            for i, v in ipairs(self.progress) do
                local event = ActivityModel.GetActById(v.id)
                table.insert(self.actInfo,event)
            end
            self.comps.sp_list:RefreshShowCell()
            --如果领取完奖励，判断积分是否可以领取奖励
            self.gift = rsp.exchargeDataMap
            for i, v in ipairs(rsp.exchargeDataMap) do
                if v == ActivityModel.OpeningEventType.WaitForGetReward then
                    InitExchange(self)
                end
            end
        end)
    end
end


--设置信息Scroll(每次切页都会走)
local function InitCvs(self)
    ReleaseEffect(self)
    self.actInfo={}
    ActivityModel.RequestOpeningEventList(self.nowDay,function (rsp)
        table.sort(rsp.s2c_data,paixu)
        --储存每个任务的进度
        self.progress = rsp.s2c_data
        --取模板数据
        for i, v in ipairs(rsp.s2c_data) do
            local event = ActivityModel.GetActById(v.id)
            table.insert(self.actInfo,event)
        end
        
        self.comps.cvs_info.Visible = false
        local function eachupdatecb(node,index)
            SetEachOne(self,node,index)
        end
        UIUtil.ConfigVScrollPan(self.comps.sp_list,self.comps.cvs_info,#self.actInfo,eachupdatecb)
    end)
end

--设置天数按钮切换
local function InitTogBtn(self)
    self.togBtn={}
    self.comps.cvs_lock.IsInteractive =false
    for i = 1, 7 do
        local tbt_page = self.comps.cvs_page:FindChildByEditName('tbt_page'..i,true)
        local ib_lock = self.comps.cvs_lock:FindChildByEditName('ib_lock'..i,true)
        ib_lock.Visible = false
        if i > self.nowDay then
            ib_lock.Visible = true
            ib_lock.IsGray =true
            tbt_page.Enable = false
            tbt_page.IsGray = true
        end
        tbt_page.UserTag = i
        table.insert(self.togBtn,tbt_page)
    end
    local function togfunc(sender)
        sender.TouchClick=function()
            self.nowDay = sender.UserTag
            InitCvs(self)
        end
    end
    UIUtil.ConfigToggleButton(self.togBtn,self.togBtn[self.nowDay],false,togfunc)
end


--加载/卸载模型
local function Load3DModel(self,data)
    local fixposdata=string.split(data.pos_xy[1],',')
    local fixpos = {x = tonumber(fixposdata[1]),y = tonumber(fixposdata[2])}
    local info = UI3DModelAdapter.AddSingleModel(
            self.ui.comps.cvs_anchor,
            Vector2(fixpos.x,fixpos.y),
            tonumber(data.zoom[1]),
            self.ui.menu.MenuOrder,
            data.showmodel[1])
    self.model= info
    info.Callback = function (info2)
        local trans2 = info2.RootTrans
        trans2:Rotate(Vector3.up,data.rotate[1])
    end
end
local function Release3DModel(self)
    if self.model then
        UI3DModelAdapter.ReleaseModel(self.model.Key)
        self.model = nil
    end
end


--模型和时间
local function InitModelAndTime(self)
    --开服时间+活动天数-现在时间 =》剩余时间
    local time = DataMgr.Instance.UserData.Serverinfo.open_at:AddDays(GameUtil.GetIntGameConfig("openmaxday"))
            - ServerTime.getServerTime():ToLocalTime()
    self.comps.lb_timenum.Text = TimeUtil.FormatToAllCN2(time.TotalSeconds)
    self.comps.tb_desc.Scrollable = true
    self.comps.tb_desc.UnityRichText = Util.GetText(self.scoreInfo[1].text)
    Load3DModel(self,self.scoreInfo[1])
end


local function InitInfo(self)
    InitTogBtn(self)
    InitCvs(self)
    InitExchange(self)
    InitModelAndTime(self)
end

--设置红点
local function SetSevenDayRedPoint(self)
    self.redpoint={}
    for i = 1, 7 do
        local lb_tip = self.comps.cvs_lock:FindChildByEditName('lb_tip'..i,true)
        table.insert(self.redpoint,lb_tip)
    end
    for i, v in pairs(ActivityModel.SevenOpeningRedPoint) do
        if v.type <= self.openDay then
            GlobalHooks.UI.ShowRedPoint(self.redpoint[v.type], 1, 'sevenday')
        end
    end
end

function _M.OnEnter(self)
    --判断活动时间是否结束
    local time = DataMgr.Instance.UserData.Serverinfo.open_at:AddDays(GameUtil.GetIntGameConfig("openmaxday"))
            - ServerTime.getServerTime():ToLocalTime()
    if time.TotalSeconds <= 0 then
        self.ui:Close()
        EventManager.Fire("Event.Hud.SetTopIcon", { comp = 'cvs_sevenday', showIcon = false})
        return
    end
    
    ActivityModel.RequestOpeningEventList(0,function (rsp)
        self.gift = rsp.exchargeDataMap
        self.openDay = rsp.s2c_day
        --选择的天数
        self.nowDay = rsp.s2c_day > 7 and 7 or rsp.s2c_day
        --拥有积分
        self.score = rsp.s2c_curFinishPoints
        InitInfo(self)
        SetSevenDayRedPoint(self)
    end)
end


function _M.OnExit(self)
    ReleaseEffect(self)
    ReleaseScoreEffect(self)
    Release3DModel(self)

    GlobalHooks.UI.SetRedTips('openingevent',0)
    if self.openDay then
        for i, v in ipairs(ActivityModel.SevenOpeningRedPoint) do
            if v.type <= self.openDay then
                GlobalHooks.UI.SetRedTips('openingevent',1)
                break
            end
        end
    end
end


return _M