
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","name","icon","text_sub","text_min","text_other","show_pic1","show_pic2","ostype","goto",},
[1] = {1,"shequ_1.name","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|2","shequ_1.text_sub","shequ_1.text_min","shequ_1.text_other","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|11","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|9","","http://bit.ly/2q1Jza0",},
[2] = {2,"shequ_2.name","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|3","shequ_2.text_sub","shequ_2.text_min","shequ_2.text_other","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|13","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|6","","https://lihi.cc/HaDXh",},
[3] = {3,"shequ_3.name","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|0","shequ_3.text_sub","shequ_3.text_min","shequ_3.text_other","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|11","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|9","IOS","http://bit.ly/2q1Jza0",},
[4] = {4,"shequ_4.name","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|1","shequ_4.text_sub","shequ_4.text_min","shequ_4.text_other","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|11","#dynamic/TL_shequ/output/TL_shequ.xml|TL_shequ|9","Android","http://bit.ly/2q1Jza0",},

}
