
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_type","cost","max_times","flag","require","reward",},
[1] = {1,5,{id={1200,},num={10,},},3,"FConsecrate",{key={"FConsecrate",},minval={5,},maxval={-1,},text={"caishen_1.require.text[1]",},},{type="common_reward",reward_id={3001,},},},
[2] = {2,5,{id={1200,},num={10,},},3,"FConsecrate",{key={"FConsecrate",},minval={15,},maxval={-1,},text={"caishen_2.require.text[1]",},},{type="common_reward",reward_id={3001,},},},
[3] = {3,5,{id={1200,},num={10,},},3,"FConsecrate",{key={"FConsecrate",},minval={30,},maxval={-1,},text={"caishen_3.require.text[1]",},},{type="common_reward",reward_id={3001,},},},
[4] = {4,5,{id={1200,},num={10,},},3,"FConsecrate",{key={"FConsecrate",},minval={60,},maxval={-1,},text={"caishen_4.require.text[1]",},},{type="common_reward",reward_id={3001,},},},

}
