---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/12/11 14:57
---
local _M = {}
_M.__index = _M


function _M.GetLevelSealInfoByLv(lv)
    local levelinfo=unpack(GlobalHooks.DB.Find('LevelSeal',{ level_seal = lv }))
    if levelinfo then
        return levelinfo
    else
        local allseal = GlobalHooks.DB.GetFullTable('LevelSeal')
        return allseal[#allseal]
    end
end


--------------------------Net-----------------------------------

--请求等级封印信息
function _M.RequestLvLimitInfo (cb)
    local request = {}
    Protocol.RequestHandler.ClientGetLvLimitInfoRequest(request, function(rsp)
        if cb then
            cb(rsp)
        end
    end)
end


--领取溢出经验
function _M.RequestGetOverflowExp (cb)
    local request = {}
    Protocol.RequestHandler.ClientGetOverflowExpRequest(request, function(rsp)
        if cb then
            cb(rsp)
        end
    end)
end


local function ShowFengYingCvs()
    local cvs_fengyin = HudManager.Instance:GetHudUI("MainHud"):FindChildByEditName("cvs_fengyin", true)
    if cvs_fengyin then
        if cvs_fengyin.Visible then
            return
        end
        cvs_fengyin.Visible=true
        local btn_fengying=cvs_fengyin:FindChildByEditName('btn_fengyin',true)
        btn_fengying.TouchClick=function(sender)
            GlobalHooks.UI.OpenUI('LevelSeal', 0)
        end
    end
end

--增加的时候会推送，经脉减少不推送
function _M.Notify(status,subject)
    if subject == DataMgr.Instance.UserData then
        if subject:ContainsKey(status, UserData.NotiFyStatus.OVERFLOWEXP) then
            ShowFengYingCvs()
        end
    end
end


local function OnEnterScene()
    if DataMgr.Instance.UserData.OverFlowExp ~= 0 then
        ShowFengYingCvs()
    end
end

local function initial()
    DataMgr.Instance.UserData:AttachLuaObserver('LevelSealModel', _M)
end

local function fin()
    DataMgr.Instance.UserData:DetachLuaObserver('LevelSealModel')
end

_M.OnEnterScene=OnEnterScene
_M.initial=initial
_M.fin=fin

return _M