---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2019/2/13 11:42
---经脉 Meridians

local _M = {}
_M.__index = _M

local ItemModel = require 'Model/ItemModel'


function _M.GetSubDetailByMain(index)
    local sub = GlobalHooks.DB.Find('Meridians', { main = index})
    return sub
end
--通过页签ID，获取每个圆盘位置
function _M.GetEveryOneMeridianPos(index)
    local pos= unpack(GlobalHooks.DB.Find('MeridiansPos',{id = index}))
    return pos.pos
end
function _M.GetOneSubDetailByMainAndSubIndex(mainindex,subindex)
    local sub= unpack(GlobalHooks.DB.Find('Meridians',{main = mainindex,sub =subindex}))
    return sub
end
function _M.GetAllMeridiansInfo()
    local all = GlobalHooks.DB.GetFullTable('Meridians')
    return all
end
--获取索引
function _M.GetMainIndex()
    local allIndex = GlobalHooks.DB.GetFullTable('MeridiansIndex')
    return allIndex
end


function _M.IsCanAdvanceMeridians(meridiansId)
    local meridiansinfo= unpack(GlobalHooks.DB.Find('Meridians',{id = meridiansId}))
    return ItemModel.CountItemByTemplateID(meridiansinfo.cost.costitem[1]) >= meridiansinfo.cost.costnum[1] or
            DataMgr.Instance.UserData.OverFlowExp >= meridiansinfo.cost.costnum[2]
end
--获取特殊效果描述
function _M.GetSpecialSkillText(id)
    local skill=unpack(GlobalHooks.DB.Find('SkillMeridians',{main =id,profession = DataMgr.Instance.UserData.Pro}))
    if skill then
        return skill
    end
    local skill2=unpack(GlobalHooks.DB.Find('SkillMeridians',{main =id}))
    if skill2 then
        return skill2
    end
end


local function TryAddAttribute(all, key, v,index)
    table.insert(all, {Name = key, Value = v,index = index,Tag = 'FixedAttributeTag'})
end

function _M.GetXlsFixedAttribute(static_data)
    local all = {}
    TryAddAttribute(all, 'maxhp', static_data.maxhp,1)
    TryAddAttribute(all, 'attack', static_data.attack,2)
    TryAddAttribute(all, 'defend', static_data.defend,3)
    TryAddAttribute(all, 'mdef', static_data.mdef,4)
    TryAddAttribute(all, 'through', static_data.through,5)
    TryAddAttribute(all, 'block', static_data.block,6)
    TryAddAttribute(all, 'crit', static_data.crit,7)
    TryAddAttribute(all, 'rescrit', static_data.rescrit,8)
    TryAddAttribute(all, 'hit', static_data.hit,9)
    TryAddAttribute(all, 'dodge', static_data.dodge,10)
    TryAddAttribute(all, 'thunderdamage', static_data.thunderdamage,11)
    TryAddAttribute(all, 'winddamage', static_data.winddamage,12)
    TryAddAttribute(all, 'icedamage', static_data.icedamage,13)
    TryAddAttribute(all, 'firedamage', static_data.firedamage,14)
    TryAddAttribute(all, 'soildamage', static_data.soildamage,15)
    TryAddAttribute(all, 'thunderresist', static_data.thunderresist,16)
    TryAddAttribute(all, 'windresist', static_data.windresist,17)
    TryAddAttribute(all, 'iceresist', static_data.iceresist,18)
    TryAddAttribute(all, 'fireresist', static_data.fireresist,19)
    TryAddAttribute(all, 'soilresist', static_data.soilresist,20)
    return all
end

-----------------------Net--------------------------------
--请求经脉数据
function _M.RequestGetMeridiansInfo(main,cb)
    local request = {c2s_main = main}
    Protocol.RequestHandler.TLClientGetMeridiansInfoRequest(request, function(rsp)
        if cb then
            cb(rsp)
        end
    end)
end
--冲穴
function _M.RequestGetThroughMeridians(main,time,cb)
    local request = {c2s_main = main,c2s_times = time}
    Protocol.RequestHandler.TLClientGetthroughMeridiansRequest(request, function(rsp)
        if cb then
            cb(rsp)
        end
    end)
end


_M.UnlockedList ={}
_M.ActivitedList={}
local function OnShowRedPoint(eventname,params)
    if not GlobalHooks.IsFuncOpen('Meridians',false) then
        return
    end
    
    if params.TemplateID == 1300 then
        for i, v in ipairs(_M.UnlockedList) do
            if _M.IsCanAdvanceMeridians(_M.UnlockedList[i]) then
                GlobalHooks.UI.SetRedTips('Meridians',1)
                return
            end
        end
        GlobalHooks.UI.SetRedTips('Meridians',0)
    end
end

function _M.initial()
    EventManager.Subscribe('Event.Item.CountUpdate', OnShowRedPoint)

    if not GameGlobal.Instance.netMode then
        return 
    end
    
    if GlobalHooks.IsFuncOpen('Meridians',false) then
        _M.RequestGetMeridiansInfo(0,function (rsp)
            for i, v in ipairs(rsp.s2c_unlocked) do
                if _M.IsCanAdvanceMeridians(rsp.s2c_unlocked[i]) then
                    GlobalHooks.UI.SetRedTips('Meridians',1)
                    return
                end
            end
            GlobalHooks.UI.SetRedTips('Meridians',0)
        end)
    end
end

function _M.fin()
    EventManager.Subscribe('Event.Item.CountUpdate', OnShowRedPoint)
end


return _M