---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/11/19 14:18
---
local _M = {}
_M.__index = _M


_M.Time = 180 --待机时间
_M.TouchKeyDown = nil --按下
_M.TouchKeyUp = nil --抬起
_M.Wait=false


function _M.CancelTiming()
    if _M.AddTime then
        LuaTimer.Delete(_M.AddTime)
        _M.AddTime = nil
    end
    DataMgr.Instance.SettingData:PowerSavingMode(false)
    GlobalHooks.UI.CloseUIByTag('SavingPower')
    if _M.TouchKeyDown then
        GameGlobal.Instance.FGCtrl:RemoveGlobalTouchDownHandler(_M.TouchKeyDown)
        _M.TouchKeyDown = nil
    end
    if _M.TouchKeyUp then
        GameGlobal.Instance.FGCtrl:RemoveGlobalTouchUpHandler(_M.TouchKeyUp)
        _M.TouchKeyUp = nil
    end
end


function _M.Timing()
    local ison=false
    local time=_M.Time
    --点击触发事件
     function _M.Touch(obj,point)
        time=_M.Time
        if ison then
            ison=false
            DataMgr.Instance.SettingData:PowerSavingMode(false)
            GlobalHooks.UI.CloseUIByTag('SavingPower')
        end
    end
    _M.CancelTiming()
    
    _M.TouchKeyDown = GameGlobal.Instance.FGCtrl:AddGlobalTouchDownHandler("Event.SavingPower", _M.Touch)
    _M.TouchKeyUp = GameGlobal.Instance.FGCtrl:AddGlobalTouchUpHandler('Event.SavingPower',_M.Touch)
    
    _M.AddTime=LuaTimer.Add(
        0,
        1000,
        function()
            if not _M.Wait then
                time=time-1
            end
            if time <= 0 then
                --倒计时小于0，开启省电
                if not ison then
                    DataMgr.Instance.SettingData:PowerSavingMode(true)
                    GlobalHooks.UI.OpenMsgBox('SavingPower',0)
                    ison=true
                end
            end
            return true
        end)
end


--开始播放为ture,结束播放为false(触发2次)
--播放cg时，暂停计时
local function OnPlayCGStart(eventname,params)
    _M.Wait=params.PlayCG
end


local function OnEnterScene()
    if DataMgr.Instance.SettingData.bIsSavePower then
        local sp = MenuMgr.Instance:FindMenuByTag('SavingPower')
        if not sp  then
            GlobalHooks.UI.OpenMsgBox('SavingPower',0)
        end
    end
end


local function initial()
    --上线如果打开省电模式，则开启计时
    if DataMgr.Instance.SettingData:GetAttribute(SettingData.NotifySettingState.ISPOWERSAVING) == 1 then
        _M.Timing()
    end
    EventManager.Subscribe(Events.PLAYCG_START,OnPlayCGStart)
end


local function fin()
    _M.CancelTiming()
    EventManager.Unsubscribe(Events.PLAYCG_START,OnPlayCGStart)
end


_M.OnEnterScene=OnEnterScene
_M.fin = fin
_M.initial = initial
return _M