---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cunyong.wu.
--- DateTime: 2018/9/14 17:56
---

local _M = {}
_M.__index = _M

function _M.ClientGetTitleInfoRequest(cb)
    local msg = {}
    Protocol.RequestHandler.TLClientGetTitleInfoRequest(msg, function(resp)
        if cb then
            cb(resp)
        end
    end)
end

function _M.ClientEquiTitleRequest(titleId ,cb)
    local msg = {}
    msg.c2s_equipTitleId = titleId
    Protocol.RequestHandler.TLClientEquiTitleRequest(msg, function(resp)
        if cb then
            cb(resp)
        end
    end)
end


function _M.ClientEquiTitleAttrRequest(titleId,cb)
    local msg = {}
    msg.c2s_equipTitleAttrId = titleId
    Protocol.RequestHandler.TLClientEquiTitleAttrRequest(msg, function(resp)
        if cb then
            cb(resp)
        end
    end)
end
 

local function OnTLClientGetTitleNotify(notify)
    --获得婚礼称号需要设置下TitleNameExt
    if not string.IsNullOrEmpty(notify.s2c_nameExt) then
        --魔改
        DataMgr.Instance.UserData:SetTitleExt(DataMgr.Instance.UserData.TitleID,notify.s2c_nameExt) 
    end
 
    GlobalHooks.UI.OpenUI('GetTitle',0,notify.s2c_titleId,notify.s2c_nameExt)
end

function _M.initial()

end

function _M.fin()
 
end



function _M.InitNetWork(initNotify)
    if initNotify then
        Protocol.PushHandler.TLClientGetTitleNotify(OnTLClientGetTitleNotify)
    end
end

return _M