
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","menu_name",},
[1] = {1,"title_menu_1.menu_name",},
[2] = {2,"title_menu_2.menu_name",},
[3] = {3,"title_menu_3.menu_name",},
[10] = {10,"title_menu_10.menu_name",},
[4] = {4,"title_menu_4.menu_name",},
[5] = {5,"title_menu_5.menu_name",},
[6] = {6,"title_menu_6.menu_name",},
[7] = {7,"title_menu_7.menu_name",},
[8] = {8,"title_menu_8.menu_name",},
[9] = {9,"title_menu_9.menu_name",},
[11] = {11,"title_menu_11.menu_name",},

}
