
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","activity_status","activity_name","sheet_name","check_key","client_xml","server_id","limit_time","start_time","end_time","last_time",},
[1] = {1,1,0,"allspring_1.activity_name","pray","","xml/business/ui_business_pray.gui.xml","1,2,3,4,5,6,7,8,9,10",1,"2019/2/2 4:00:00","2019/2/20 4:00:00",0,},
[2] = {2,2,0,"allspring_2.activity_name","packets","","xml/business/ui_business_packets.gui.xml","1,2,3,4,5,6,7,8,9,10",1,"2019/2/2 4:00:00","2019/2/20 4:00:00",0,},
[3] = {3,3,0,"allspring_3.activity_name","box","","xml/business/ui_business_box.gui.xml","1,2,3,4,5,6,7,8,9,10",1,"2019/2/4 4:00:00","2019/2/20 4:00:00",0,},
[4] = {4,4,0,"allspring_4.activity_name","worldboss","","xml/business/ui_business_nianshou.gui.xml","1,2,3,4,5,6,7,8,9,10",1,"2019/2/4 4:00:00","2019/2/20 4:00:00",0,},
[5] = {5,5,0,"allspring_5.activity_name","caishen","","xml/business/ui_business_consecrate.gui.xml","1,2,3,4,5,6,7,8,9,10",1,"2019/2/8 4:00:00","2019/2/20 4:00:00",0,},
[6] = {6,6,0,"allspring_6.activity_name","yuanxiao","","xml/business/ui_business_yuanxiao.gui.xml","1,2,3,4,5,6,7,8,9,10",1,"2019/2/17 4:00:00","2019/2/20 4:00:00",0,},

}
