
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","activity_type","consume_min","consume_max","per_backmoney","maxmoney","money_fuqibi","max_fuqibi","reward_expire_date","init_flag","money_template_id","money_item_id","mail_id",},
[1] = {1,2,2,1,49,2000,500,0,0,"2019/3/1 4:00:00","Packetsadd",3,10,90001,},
[2] = {2,2,2,50,300,2000,500,50,50,"2019/3/1 4:00:00","Packetsadd",3,10,90001,},
[3] = {3,2,2,301,1000,2000,500,100,100,"2019/3/1 4:00:00","Packetsadd",3,10,90001,},
[4] = {4,2,2,1001,9999999,2000,500,300,300,"2019/3/1 4:00:00","Packetsadd",3,10,90001,},

}
