
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","activity_type","cost","max_times","flag","require","reward",},
[1] = {1,1,1,{id={10,},num={50,},},3,"SFPraynum",{key={"dSFPraynum",},minval={0,},maxval={2,},text={"pray_1.require.text[1]",},},{type="common_reward",reward_id={3021,},},},

}
