
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","level","capital_lvup","talent_lv","reward_id","reward_num","talent_name","des","item_id",},
[1] = {1,0,450000,0,0,0,"guild_college_1.talent_name","guild_college_1.des",5003,},
[2] = {2,1,2400000,1,0,0,"guild_college_2.talent_name","guild_college_2.des",5003,},
[3] = {3,2,5000000,2,0,0,"guild_college_3.talent_name","guild_college_3.des",5003,},
[4] = {4,3,8400000,3,0,0,"guild_college_4.talent_name","guild_college_4.des",5003,},
[5] = {5,4,13050000,4,0,0,"guild_college_5.talent_name","guild_college_5.des",5003,},
[6] = {6,5,0,5,0,0,"guild_college_6.talent_name","guild_college_6.des",5003,},

}
