
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","level","capital_lvup","reward_id","reward_num","des","item_id",},
[1] = {1,0,450000,0,0,"guild_store_1.des",5003,},
[2] = {2,1,2400000,0,0,"guild_store_2.des",5003,},
[3] = {3,2,5000000,0,0,"guild_store_3.des",5003,},
[4] = {4,3,8400000,0,0,"guild_store_4.des",5003,},
[5] = {5,4,13050000,0,0,"guild_store_5.des",5003,},
[6] = {6,5,0,0,0,"guild_store_6.des",5003,},

}
