
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","stronghold_name",},
[1] = {1,"guild_stronghold_1.stronghold_name",},
[2] = {2,"guild_stronghold_2.stronghold_name",},
[3] = {3,"guild_stronghold_3.stronghold_name",},

}
