---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/8/16 17:38
---

local _M = {}
_M.__index = _M

local TimeUtil=require 'Logic/TimeUtil'
local Dungeon= require 'Model/DungeonModel'
local UIUtil = require 'UI/UIUtil'
local ItemModel = require 'Model/ItemModel'

local lb_betimeCount--倒计时
local lb_kill=0--击杀数
local cvs_beasts,cvs_showreward
local bouns
local cvs_itemicon={}
local lb_num={}


--计算奖励数据
local function CalcBouns(killcount)
    local b=unpack(GlobalHooks.DB.Find('BeastsModeMonster',{killcount =killcount}))
    return b.reward
end


local function OnChangeData(eventname,params)

    --显示倒计时
    if params.key =='count_down' then
        lb_betimeCount.Text = TimeUtil.SecToTimeformatToMS(params.value)
    end
    
    --击杀数变化时，重新计算奖励，同时更新数量
    if params.key=='kill' then
        lb_kill=params.value
        bouns=CalcBouns(lb_kill)
        for i = 1, 3 do
            lb_num[i].Text=bouns.item.num[i]
        end
    end
end


local function OnHideUI(eventname,params)
    if cvs_beasts.Visible==true then
        cvs_beasts.Visible=false
    end
    if cvs_showreward.Visible==true then
        cvs_showreward.Visible=false
    end
end


function _M.OnInit(self)

    --设置ui覆盖类型以及动画
    self.ui.menu.ShowType = UIShowType.Cover
    self.ui.menu:SetCompAnime(self.ui.menu, UIAnimeType.FadeMoveDown)

    lb_betimeCount=self.ui.comps.lb_betime
    
    cvs_beasts=self.ui.comps.cvs_beasts
    cvs_showreward=self.ui.comps.cvs_showreward
    self.btn_fbleave=self.ui.comps.btn_fbleave

    --自适应
    HudManager.Instance:InitAnchorWithNode(self.ui.comps.cvs_showreward, bit.bor(HudManager.HUD_TOP,HudManager.HUD_RIGHT))
    HudManager.Instance:InitAnchorWithNode(self.ui.comps.cvs_beasts, bit.bor(HudManager.HUD_TOP,HudManager.HUD_RIGHT))

end


--初始化设置一次奖励物品
local function SetBounsIconAndNum(self,bouns)
    for i = 1, self.ui.comps.cvs_showitem.NumChildren do
        cvs_itemicon[i]=self.ui.comps.cvs_showitem:FindChildByEditName('cvs_item'..i,true)
        lb_num[i]=self.ui.comps.cvs_showitem:FindChildByEditName('lb_num'..i,true)
        
        local itemdetail=ItemModel.GetDetailByTemplateID(tonumber(bouns.item.id[i]))
        local quality = itemdetail.static.quality
        local icon=itemdetail.static.atlas_id
        local itshow=UIUtil.SetItemShowTo(cvs_itemicon[i],icon,quality,1)
        itshow.EnableTouch = true
        itshow.TouchClick = function()
            SoundManager.Instance:PlaySoundByKey('button',false)
            local detail = UIUtil.ShowNormalItemDetail({x=cvs_itemicon[i].X+740,y=cvs_itemicon[i].Y+140,detail = itemdetail,itemShow = itshow,autoHeight = true,autoWeight=true})
        end
        
        lb_num[i].Text=bouns.item.num[i]
    end
end


function _M.OnEnter(self,params)
    
    --击杀数清零
    lb_kill=0
    --计算奖励物品
    bouns=CalcBouns(lb_kill)
    if bouns ~= nil then
        SetBounsIconAndNum(self,bouns)
    end
    
    --使鼠标点击能够穿透该canvas
    cvs_beasts.Enable=false

    --ui穿透
    self.ui:EnableTouchFrameClose(false)
    
    --添加环境变量监听
    EventManager.Subscribe("Event.SyncEnvironmentVarEvent", OnChangeData)
    EventManager.Subscribe("Event.UI.NotifyResult",OnHideUI)

    self.btn_fbleave.TouchClick=function()
        --弹出二次确认离开界面
            Dungeon.ShowExitConfirmTips()
    end
end

function _M.OnExit(self)

    --注销监听
    EventManager.Unsubscribe("Event.SyncEnvironmentVarEvent", OnChangeData)
    EventManager.Unsubscribe("Event.UI.NotifyResult",OnHideUI)

end


return _M