---省电模式UI
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xujing.xu.
--- DateTime: 2018/11/22 11:52
---

local _M = {}
_M.__index = _M
local SystemModel=require('Model/SystemModel')

function _M.OnInit(self)
    self.ui.menu:SetFullBackground(UILayout.CreateUILayoutColor(UnityEngine.Color(0,0,0,0.5),UnityEngine.Color(0,0,0,0.5)))
    self.ui.menu.ShowType = UIShowType.Cover
    self.ui.menu:SetCompAnime(self.ui.menu, UIAnimeType.NoAnime)
--[[    self.ui:EnableTouchFrameClose(false)]]
end

local function Release3DModel(self)
    if self.model then
        RenderSystem.Instance:Unload(self.model)
        self.model = nil
    end
end

local function Play3DEffect(self,parentCvs, menuOrder, fileName)
    local transSet = TransformSet()
    transSet.Pos = Vector3(0,0,0)
    transSet.Scale = Vector3(1,1,1)
    transSet.Parent = parentCvs.Transform
    transSet.Layer = Constants.Layer.UI
    transSet.LayerOrder = menuOrder
    self.model = RenderSystem.Instance:LoadGameObject(fileName,transSet)
end

function _M.OnEnter(self)
    Play3DEffect(self,self.ui.comps.cvs_anchor,self.ui.menu.MenuOrder,'/res/effect/ui/ef_ui_powersaving.assetbundles')
    self.ui.menu.event_PointerDown=function()
        SystemModel.Touch()
    end
end

function _M.OnExit(self)
    Release3DModel(self)
end

return _M