
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","dungen_name","order","show_limit","sheet","dungeon_desc","dungeon_fight","num_desc","pic_res","head_res","awardshow","first_notice_id",},
[230110] = {230110,"dungeondata_230110.dungen_name",1,40,1,"dungeondata_230110.dungeon_desc",15400,"dungeondata_230110.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|9","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|0",{id={5515,1,4,0,0,0,0,0,0,0,},},108,},
[230120] = {230120,"dungeondata_230120.dungen_name",2,60,1,"dungeondata_230120.dungeon_desc",25500,"dungeondata_230120.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|10","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|1",{id={5253,1,4,0,0,0,0,0,0,0,},},109,},
[230130] = {230130,"dungeondata_230130.dungen_name",3,80,1,"dungeondata_230130.dungeon_desc",38000,"dungeondata_230130.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|11","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|2",{id={5254,1,4,0,0,0,0,0,0,0,},},110,},
[230140] = {230140,"dungeondata_230140.dungen_name",4,100,1,"dungeondata_230140.dungeon_desc",85000,"dungeondata_230140.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|12","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|3",{id={5255,1,4,0,0,0,0,0,0,0,},},111,},
[230150] = {230150,"dungeondata_230150.dungen_name",5,120,1,"dungeondata_230150.dungeon_desc",200000,"dungeondata_230150.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|13","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|4",{id={5256,1,4,0,0,0,0,0,0,0,},},112,},
[230170] = {230170,"dungeondata_230170.dungen_name",6,140,1,"dungeondata_230170.dungeon_desc",320000,"dungeondata_230170.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|14","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|15",{id={5257,1,4,0,0,0,0,0,0,0,},},172,},
[231110] = {231110,"dungeondata_231110.dungen_name",1,50,2,"dungeondata_231110.dungeon_desc",20000,"dungeondata_231110.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|9","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|0",{id={5523,5521,1,4,0,0,0,0,0,0,},},108,},
[231120] = {231120,"dungeondata_231120.dungen_name",2,70,2,"dungeondata_231120.dungeon_desc",35000,"dungeondata_231120.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|10","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|1",{id={5357,5331,1,4,0,0,0,0,0,0,},},109,},
[231130] = {231130,"dungeondata_231130.dungen_name",3,90,2,"dungeondata_231130.dungeon_desc",55000,"dungeondata_231130.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|11","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|2",{id={5358,5332,1,4,0,0,0,0,0,0,},},110,},
[231140] = {231140,"dungeondata_231140.dungen_name",4,110,2,"dungeondata_231140.dungeon_desc",100000,"dungeondata_231140.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|12","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|3",{id={5359,5333,1,4,0,0,0,0,0,0,},},111,},
[231150] = {231150,"dungeondata_231150.dungen_name",5,130,2,"dungeondata_231150.dungeon_desc",250000,"dungeondata_231150.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|13","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|4",{id={5360,5334,1,4,0,0,0,0,0,0,},},112,},
[231170] = {231170,"dungeondata_231170.dungen_name",6,150,2,"dungeondata_231170.dungeon_desc",400000,"dungeondata_231170.num_desc","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|14","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|15",{id={5361,5335,1,4,0,0,0,0,0,0,},},173,},

}
