
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","rewardtime","require","reward","item_show","item_show_num","hint",},
[1] = {1,5,1,{key={"fTurntable/5",},minval={5,},maxval={-1,},text={"turntable_reward_1.require.text[1]",},},{type="common_reward",reward_id={3012,},},{7029,7054,6004,},{2,1,2,},1,},
[2] = {2,5,2,{key={"fTurntable/5",},minval={20,},maxval={-1,},text={"turntable_reward_2.require.text[1]",},},{type="common_reward",reward_id={3013,},},{7020,7054,6004,},{6,4,8,},1,},
[3] = {3,5,3,{key={"fTurntable/5",},minval={40,},maxval={-1,},text={"turntable_reward_3.require.text[1]",},},{type="common_reward",reward_id={3014,},},{7001,7054,6004,},{5,10,20,},1,},
[4] = {4,5,4,{key={"fTurntable/5",},minval={60,},maxval={-1,},text={"turntable_reward_4.require.text[1]",},},{type="common_reward",reward_id={3015,},},{5052,7054,6004,},{1,20,40,},1,},

}
