
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_id","partake_num","item",},
[1] = {1,"pvp4",1,{id={7,},num={20,},},},
[2] = {2,"pvp4",3,{id={7,},num={50,},},},
[3] = {3,"pvp4",5,{id={7,},num={80,},},},
[4] = {4,"pvp10",1,{id={7,},num={20,},},},
[5] = {5,"pvp10",3,{id={7,},num={50,},},},
[6] = {6,"pvp10",5,{id={7,},num={80,},},},
[7] = {7,"pvp_duoqi",1,{id={7,},num={10,},},},
[8] = {8,"pvp_duoqi",3,{id={7,},num={25,},},},
[9] = {9,"pvp_duoqi",5,{id={7,},num={40,},},},
[10] = {10,"pvp_qinglong",1,{id={7,},num={10,},},},
[11] = {11,"pvp_qinglong",3,{id={7,},num={25,},},},
[12] = {12,"pvp_qinglong",5,{id={7,},num={40,},},},
[13] = {13,"pvp_longshen",1,{id={7,},num={10,},},},
[14] = {14,"pvp_longshen",3,{id={7,},num={25,},},},
[15] = {15,"pvp_longshen",5,{id={7,},num={40,},},},

}
