
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","mall_type","type_name",},
[1] = {1,1,"mall_type_1.type_name",},
[2] = {2,2,"mall_type_2.type_name",},
[3] = {3,3,"mall_type_3.type_name",},

}
