
// Warning: do not edit this file.
// 警告: 不要编辑此文件

// SampleRPG, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// SampleRPG.Data.SampleMember


using DeepCore;
using DeepCore.IO;
using System.Collections.Generic;

namespace SampleRPG.Data
{
    public class SampleMemberOperator
    {
       
        public int id
        {
        output.PutS32(data.id);
        }
      
 
        public string info
        {
        output.PutUTF(data.info);
        }
      
 
        public int value
        {
        output.PutS32(data.value);
        }
      

    }
}

