
// Warning: do not edit this file.
// 警告: 不要编辑此文件

// SampleRPG, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// SampleRPG.Data.SampleData


using DeepCore;
using DeepCore.IO;
using System.Collections.Generic;

namespace SampleRPG.Data
{
    public class SampleDataOperator
    {
       
        public int id
        {
        output.PutS32(data.id);
        }
      
 
        public byte u8
        {
        output.PutU8(data.u8);
        }
      
 
        public short s16
        {
        output.PutS16(data.s16);
        }
      
 
        public float f32
        {
        output.PutF32(data.f32);
        }
      
 
        public bool bbbb
        {
        output.PutBool(data.bbbb);
        }
      
 
        public TimeSpan timespan
        {
        output.PutTimeSpan(data.timespan);
        }
      
 
        public DateTime datetime
        {
        output.PutDateTime(data.datetime);
        }
      
 
        public string info
        {
        output.PutUTF(data.info);
        }
      
 
        public int value
        {
        output.PutS32(data.value);
        }
      
 
        public SampleRPG.Data.SampleMember member
        {
        output.PutOBJ(data.member);
        }
      
 
        public SampleRPG.Data.SampleMember member2
        {
        output.PutOBJ(data.member2);
        }
      
 
        public IMappingArray<SampleRPG.Data.SampleMember> array
        {
        
        }
      
 
        public IMappingArray<int> arrayInt32
        {
        
        }
      
 
        public IMappingList<int> listInt32
        {
        
        }
      
 
        public IMappingList<SampleRPG.Data.SampleMember> list
        {
        
        }
      
 
        public IMappingList<SampleRPG.Data.SampleMember> list2
        {
        
        }
      
 
        public IMappingHashMap<string, SampleRPG.Data.SampleMember> map
        {
        
        }
      
 
        public IMappingHashMap<int, SampleRPG.Data.SampleMember> map2
        {
        
        }
      

    }
}

