
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_tag","function_name",},
[1] = {1,"startshimen","function_1.function_name",},
[2] = {2,"enterguild","function_2.function_name",},
[3] = {3,"guildstore","function_3.function_name",},
[4] = {4,"guildcollege","function_4.function_name",},
[5] = {5,"guildmonster","function_5.function_name",},
[6] = {6,"guildquest","function_6.function_name",},
[7] = {7,"testquest","function_7.function_name",},

}
