
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_type","activity_sub_type","activity_sub_name","activity",},
[1] = {1,1,1,"activity_type_1.activity_sub_name",{id={0,0,0,0,0,0,0,0,0,0,},},},
[2] = {2,1,2,"activity_type_2.activity_sub_name",{id={1,4,13,14,15,16,0,0,0,0,},},},
[3] = {3,1,3,"activity_type_3.activity_sub_name",{id={1,13,2,21,7,18,12,0,0,0,},},},
[4] = {4,1,4,"activity_type_4.activity_sub_name",{id={4,8,23,6,28,0,0,0,0,0,},},},
[5] = {5,1,5,"activity_type_5.activity_sub_name",{id={14,15,16,5,6,10,0,0,0,0,},},},
[6] = {6,2,1,"activity_type_6.activity_sub_name",{id={0,0,0,0,0,0,0,0,0,0,},},},
[7] = {7,2,2,"activity_type_7.activity_sub_name",{id={0,0,0,0,0,0,0,0,0,0,},},},
[8] = {8,2,3,"activity_type_8.activity_sub_name",{id={0,0,0,0,0,0,0,0,0,0,},},},
[9] = {9,2,4,"activity_type_9.activity_sub_name",{id={0,0,0,0,0,0,0,0,0,0,},},},

}
