
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","instructions",},
[1] = {1,"gmcmd_acceptquest",},
[2] = {2,"gmcmd_giveupquest",},
[3] = {3,"gmcmd_finishquest",},
[4] = {4,"gmcmd_exp",},
[5] = {5,"gmcmd_gold",},
[6] = {6,"gmcmd_add",},
[7] = {7,"gmcmd_help",},
[8] = {8,"gmcmd_addflag",},
[9] = {9,"chat_public",},
[10] = {10,"ranking_inlist",},
[11] = {11,"gmcmd_openfunc",},
[12] = {12,"gmcmd_rebirth",},
[13] = {13,"white_list",},
[14] = {14,"gmcmd_setflag",},

}
