
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","record_num","target_level","name","desc","item_id","item_num","icon_res","picture_res",},
[1] = {1,1001,10,"objective_1.name","objective_1.desc",1200,10,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|17","#static/TL_hud/output/TL_hud.xml|TL_hud|199",},
[2] = {2,1002,11,"objective_2.name","objective_2.desc",1500,30,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|26","#static/TL_hud/output/TL_hud.xml|TL_hud|199",},
[3] = {3,1003,19,"objective_3.name","objective_3.desc",1400,10,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|22","#static/TL_hud/output/TL_hud.xml|TL_hud|199",},
[4] = {4,1007,30,"objective_4.name","objective_4.desc",5022,1,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|23","#static/TL_hud/output/TL_hud.xml|TL_hud|199",},
[5] = {5,1006,40,"objective_5.name","objective_5.desc",1200,20,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|3","#static/TL_hud/output/TL_hud.xml|TL_hud|199",},
[6] = {6,1005,42,"objective_6.name","objective_6.desc",1700,10,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|21","#static/TL_hud/output/TL_hud.xml|TL_hud|199",},
[7] = {7,1004,43,"objective_7.name","objective_7.desc",1600,10,"#dynamic/TL_functions/output/TL_functions.xml|TL_functions|16","#static/TL_hud/output/TL_hud.xml|TL_hud|199",},

}
