
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","battlefield_name","type","open_time","pic_res","battlefield_description",},
[1] = {1,"pvp_desc_1.battlefield_name","pvp_qinglong","pvp_desc_1.open_time","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|10","#dynamic/TL_battle_explain/output/TL_battle_explain.xml|TL_battle_explain|3",},
[2] = {2,"pvp_desc_2.battlefield_name","pvp_longshen","pvp_desc_2.open_time","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|11","#dynamic/TL_battle_explain/output/TL_battle_explain.xml|TL_battle_explain|4",},
[3] = {3,"pvp_desc_3.battlefield_name","pvp10","pvp_desc_3.open_time","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|9","#dynamic/TL_battle_explain/output/TL_battle_explain.xml|TL_battle_explain|0",},
[4] = {4,"pvp_desc_4.battlefield_name","pvp4","pvp_desc_4.open_time","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|10","#dynamic/TL_battle_explain/output/TL_battle_explain.xml|TL_battle_explain|1",},
[5] = {5,"pvp_desc_5.battlefield_name","pvp_duoqi","pvp_desc_5.open_time","#dynamic/TL_fubenbg/output/TL_fubenbg.xml|TL_fubenbg|9","#dynamic/TL_battle_explain/output/TL_battle_explain.xml|TL_battle_explain|2",},

}
