
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","random_buff","buff_id","weight",},
[1] = {1,1,123,100,},
[2] = {2,1,124,100,},
[3] = {3,1,125,100,},
[4] = {4,1,126,100,},

}
