
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","flag","award","require",},
[8001] = {8001,"product3001",{id={3,1200,1,2,},num={100,10,10000,500,},flag_reward={10101,},},{key={"dcard1",},minval={0,},maxval={0,},text={"common_card_8001.require.text[1]",},},},
[8002] = {8002,"product3002",{id={3,1200,1,2,},num={300,20,10000,500,},flag_reward={10102,},},{key={"dcard2",},minval={0,},maxval={0,},text={"common_card_8002.require.text[1]",},},},
[8003] = {8003,"product3003",{id={3,1200,1,2,},num={600,30,10000,500,},flag_reward={10103,},},{key={"dcard3",},minval={0,},maxval={0,},text={"common_card_8003.require.text[1]",},},},

}
