
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","lbtext","reward","show","showmodel","pos_xy","zoom","rotate","showpic","require",},
[4001] = {4001,"garment_4001.lbtext",{reward_id="8401",flag_reward={0,0,},},{item={3,3,1,1200,1500,},itemnum={1,1000,100000,50,40,},},{"",},{"0,0",},{"100",},{0,},{"#dynamic/TL_business/output/TL_business.xml|TL_business|33",},{key={"pnum","pgarment",},minval={300,20,},maxval={-1,0,},text={"garment_4001.require.text[1]","garment_4001.require.text[2]",},},},
[4002] = {4002,"garment_4002.lbtext",{reward_id="8402",flag_reward={0,0,},},{item={3305,3305,1,1400,1902,},itemnum={1,1,200000,50,1980,},},{"/res/effect/ef_show_partner_liyuan.assetbundles",},{"0,0",},{"100",},{0,},{"",},{key={"pnum","pgarment",},minval={250,40,},maxval={-1,0,},text={"garment_4002.require.text[1]","garment_4002.require.text[2]",},},},
[4003] = {4003,"garment_4003.lbtext",{reward_id="8403",flag_reward={0,0,},},{item={3,3,1,1700,1202,},itemnum={1,2000,300000,50,100,},},{"",},{"0,0",},{"100",},{0,},{"#dynamic/TL_business/output/TL_business.xml|TL_business|33",},{key={"pnum","pgarment",},minval={200,60,},maxval={-1,0,},text={"garment_4003.require.text[1]","garment_4003.require.text[2]",},},},
[4004] = {4004,"garment_4004.lbtext",{reward_id="8404",flag_reward={0,0,},},{item={3502,3502,3,1,7015,},itemnum={1,1,3000,1000000,10,},},{"/res/effect/item/ef_item_god_03.assetbundles",},{"0,50",},{"250",},{180,},{"",},{key={"pnum","pgarment",},minval={150,80,},maxval={-1,0,},text={"garment_4004.require.text[1]","garment_4004.require.text[2]",},},},
[4005] = {4005,"garment_4005.lbtext",{reward_id="8405",flag_reward={0,0,},},{item={3,3,1201,1202,0,},itemnum={1,5000,50,300,0,},},{"",},{"0,0",},{"100",},{0,},{"#dynamic/TL_business/output/TL_business.xml|TL_business|33",},{key={"pnum","pgarment",},minval={100,100,},maxval={-1,0,},text={"garment_4005.require.text[1]","garment_4005.require.text[2]",},},},
[4006] = {4006,"garment_4006.lbtext",{reward_id="8406",flag_reward={0,0,},},{item={3503,3503,1,7016,0,},itemnum={1,1,1000000,10,0,},},{"/res/effect/item/ef_item_god_04.assetbundles",},{"0,50",},{"250",},{180,},{"",},{key={"pnum","pgarment",},minval={50,120,},maxval={-1,0,},text={"garment_4006.require.text[1]","garment_4006.require.text[2]",},},},

}
