
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","lbtext","reward","show","showmodel","pos_xy","zoom","rotate","showpic","require",},
[2001] = {2001,"level_2001.lbtext",{reward_id="8021",flag_reward={0,0,},},{item={3,3,1,1200,1500,},itemnum={1,1000,100000,50,40,},},{"",},{"0,0",},{"100",},{0,},{"#dynamic/TL_business/output/TL_business.xml|TL_business|33",},{key={"pLevel","pnum",},minval={20,0,},maxval={-1,300,},text={"level_2001.require.text[1]","level_2001.require.text[2]",},},},
[2002] = {2002,"level_2002.lbtext",{reward_id="8022",flag_reward={0,0,},},{item={3305,3305,1,1400,1902,},itemnum={1,1,200000,50,1980,},},{"/res/effect/ef_show_partner_liyuan.assetbundles",},{"0,0",},{"100",},{0,},{"",},{key={"pLevel","pnum",},minval={40,0,},maxval={-1,250,},text={"level_2002.require.text[1]","level_2002.require.text[2]",},},},
[2003] = {2003,"level_2003.lbtext",{reward_id="8023",flag_reward={0,0,},},{item={3,3,1,1700,1202,},itemnum={1,2000,300000,50,100,},},{"",},{"0,0",},{"100",},{0,},{"#dynamic/TL_business/output/TL_business.xml|TL_business|33",},{key={"pLevel","pnum",},minval={60,0,},maxval={-1,200,},text={"level_2003.require.text[1]","level_2003.require.text[2]",},},},
[2004] = {2004,"level_2004.lbtext",{reward_id="8024",flag_reward={0,0,},},{item={3502,3502,3,1,7015,},itemnum={1,1,3000,1000000,10,},},{"/res/effect/item/ef_item_god_03.assetbundles",},{"0,50",},{"250",},{180,},{"",},{key={"pLevel","pnum",},minval={80,0,},maxval={-1,150,},text={"level_2004.require.text[1]","level_2004.require.text[2]",},},},
[2005] = {2005,"level_2005.lbtext",{reward_id="8025",flag_reward={0,0,},},{item={3,3,1201,1202,0,},itemnum={1,5000,50,300,0,},},{"",},{"0,0",},{"100",},{0,},{"#dynamic/TL_business/output/TL_business.xml|TL_business|33",},{key={"pLevel","pnum",},minval={100,0,},maxval={-1,100,},text={"level_2005.require.text[1]","level_2005.require.text[2]",},},},
[2006] = {2006,"level_2006.lbtext",{reward_id="8026",flag_reward={0,0,},},{item={3503,3503,1,7016,0,},itemnum={1,1,1000000,10,0,},},{"/res/effect/item/ef_item_god_04.assetbundles",},{"0,50",},{"250",},{180,},{"",},{key={"pLevel","pnum",},minval={120,0,},maxval={-1,50,},text={"level_2006.require.text[1]","level_2006.require.text[2]",},},},

}
