
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","level_limit","pvp_coefficient","pve_coefficient","hit_rate_c1","hit_rate_c2","hit_rate_c3","block_c1","block_c2","block_c3","block_c4","crit_rate_c1","crit_rate_c2","crit_rate_c3","crit_rate_c4","crit_rate_c5","crit_rate_c6","crit_damage_per_c1","crit_heal_c1","crit_heal_c2","damage_reduce_rate_c1","phy_damage_reduce_rate_c1","phy_damage_reduce_rate_c2","phy_damage_reduce_rate_c3","phy_damage_reduce_rate_c4","phy_damage_reduce_rate_c5","phy_damage_reduce_rate_c6","phy_damage_reduce_rate_c7","phy_damage_reduce_rate_c8","mag_damage_reduce_rate_c1","mag_damage_reduce_rate_c2","mag_damage_reduce_rate_c3","mag_damage_reduce_rate_c4","mag_damage_reduce_rate_c5","mag_damage_reduce_rate_c6","mag_damage_reduce_rate_c7","mag_damage_reduce_rate_c8","cal_damage_c1","cal_damage_c2","cal_total_damage_per_rate_c1",},
[1] = {1,200,0.75,1,0.5,19800,20000,0.5,157,5000,6000,0.045,10381,219,20,1923,0.8,1.2,0.015,40000,52,0.01,42032,219,20,7694,0.9,2,3,0.01,42032,219,20,7694,0.9,2,3,9500,10500,0.01,},

}
