
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","card","cardevent","next_event","success",},
[1] = {1,{"#dynamic/TL_card2/output/TL_card2.xml|TL_card2|0","",},{"","",},"",{id={"",},},},
[2] = {2,{"#dynamic/TL_card2/output/TL_card2.xml|TL_card2|0","",},{"reward.1","",},"",{id={"",},},},
[3] = {3,{"#dynamic/TL_card2/output/TL_card2.xml|TL_card2|0","",},{"reward.1","",},"",{id={"",},},},
[4] = {4,{"#dynamic/TL_card2/output/TL_card2.xml|TL_card2|0","",},{"","",},"",{id={"",},},},

}
