
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","relat_lv","name","lv_num","attack","maxhp","defend","mdef",},
[1] = {1,1,"relationship_1.name",500,100,250,100,100,},
[2] = {2,2,"relationship_2.name",1500,150,350,150,150,},
[3] = {3,3,"relationship_3.name",3000,200,450,200,200,},
[4] = {4,4,"relationship_4.name",5000,250,550,250,250,},
[5] = {5,5,"relationship_5.name",10000,300,650,300,300,},
[6] = {6,6,"relationship_6.name",0,400,800,400,400,},

}
