
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","name","icon_id","type","is_valid","rank",},
[1] = {1,"achieve_list_1.name","#dynamic/TL_achievement/output/TL_achievement.xml|TL_achievement|3",1,1,5,},
[2] = {2,"achieve_list_2.name","#dynamic/TL_achievement/output/TL_achievement.xml|TL_achievement|5",2,1,4,},
[3] = {3,"achieve_list_3.name","#dynamic/TL_achievement/output/TL_achievement.xml|TL_achievement|4",3,1,3,},
[4] = {4,"achieve_list_4.name","#dynamic/TL_achievement/output/TL_achievement.xml|TL_achievement|6",4,1,2,},
[5] = {5,"achieve_list_5.name","#dynamic/TL_achievement/output/TL_achievement.xml|TL_achievement|7",5,1,1,},

}
