
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","key","tips",},
[1] = {1,"","说明key对应的效果和参数设置效果",},
[2] = {2,"sign_1","签到奖励第1天",},
[3] = {3,"ware_house","随身仓库",},
[4] = {4,"head_frame","头像框",},
[5] = {5,"ah_page","拍卖行栏位",},
[6] = {6,"ah_tax","税率",},
[7] = {7,"res_dungeon_exp_tickets","经验本进入次数额外购买",},
[8] = {8,"res_dungeon_mount_tickets","坐骑本进入次数额外购买",},
[9] = {9,"res_dungeon_wing_tickets","背饰本进入次数额外购买",},
[10] = {10,"res_dungeon_miracle_tickets","神器本进入次数额外购买",},
[11] = {11,"god_island_tickets","仙灵岛次数",},
[12] = {12,"tower_reset","镇妖塔重置次数",},
[13] = {13,"offline_exp_addition","离线经验收益加成",},
[14] = {14,"offline_time_min","离线经验最小起算时间",},
[15] = {15,"offline_time_max","离线经验最大计算时间",},
[16] = {16,"guild_donate","仙盟捐献",},
[17] = {17,"purchase_limit_20024","鸿运镖购买次数",},
[18] = {18,"fairyland_mop_up","太虚幻境扫荡权限",},
[19] = {19,"god_island_mop_up","仙灵岛扫荡",},
[20] = {20,"tower_mop_up","镇妖塔扫荡",},
[21] = {21,"battlefield_addition","战场荣耀",},
[22] = {22,"purchase_limit_id","指定（）商品增加限购次数",},

}
