
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","function_id","settlement_flag","config_max","require","reward",},
[1] = {1,"island1","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep1","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_1.require.text[1]","sweep_god_island_1.require.text[2]",},},{type="common_reward",reward_id={27,},flag_reward={2115,},},},
[2] = {2,"island2","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep2","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_2.require.text[1]","sweep_god_island_2.require.text[2]",},},{type="common_reward",reward_id={28,},flag_reward={2115,},},},
[3] = {3,"island3","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep3","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_3.require.text[1]","sweep_god_island_3.require.text[2]",},},{type="common_reward",reward_id={29,},flag_reward={2115,},},},
[4] = {4,"island4","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep4","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_4.require.text[1]","sweep_god_island_4.require.text[2]",},},{type="common_reward",reward_id={30,},flag_reward={2115,},},},
[5] = {5,"island5","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep5","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_5.require.text[1]","sweep_god_island_5.require.text[2]",},},{type="common_reward",reward_id={31,},flag_reward={2115,},},},
[6] = {6,"island6","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep6","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_6.require.text[1]","sweep_god_island_6.require.text[2]",},},{type="common_reward",reward_id={32,},flag_reward={2115,},},},
[7] = {7,"island7","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep7","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_7.require.text[1]","sweep_god_island_7.require.text[2]",},},{type="common_reward",reward_id={34,},flag_reward={2115,},},},
[8] = {8,"island8","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep8","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_8.require.text[1]","sweep_god_island_8.require.text[2]",},},{type="common_reward",reward_id={35,},flag_reward={2115,},},},
[9] = {9,"island9","GodIslandDailyPassTimes","god_island_num",{key={"fGodIslandSweep9","pVipLv",},minval={1,4,},maxval={1,-1,},text={"sweep_god_island_9.require.text[1]","sweep_god_island_9.require.text[2]",},},{type="common_reward",reward_id={36,},flag_reward={2115,},},},

}
