
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","tablename",},
["shimen"] = {1,"shimen",},
["xianmen"] = {2,"xianmen",},
["wanted"] = {3,"wanted",},
["consignation"] = {4,"consignation",},
["guild_carriage"] = {5,"guild_carriage",},

}
