
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","dif_level","recom_level","dif_desc","dif_icon",},
[1] = {1,1,40,"pagoda_diflevel_1.dif_desc","#dynamic/TL_tower/output/TL_tower.xml|TL_tower|47",},
[2] = {2,2,100,"pagoda_diflevel_2.dif_desc","#dynamic/TL_tower/output/TL_tower.xml|TL_tower|43",},
[3] = {3,3,120,"pagoda_diflevel_3.dif_desc","#dynamic/TL_tower/output/TL_tower.xml|TL_tower|44",},

}
