
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","prestige_type","type_name","unlock",},
[1] = {1,1,"prestige_type_1.type_name",1,},
[2] = {2,2,"prestige_type_2.type_name",1,},
[3] = {3,3,"prestige_type_3.type_name",1,},

}
