
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","type","lbtext","reward","show","show_model","pos_xy","zoom","rotate","show_pic","server_variate","server_variate_num","server_variate_text","require",},
[30001] = {30001,3,1,"fight_30001.lbtext",{reward_id="8301",flag_reward={8031,},},{item={200050,1500,1,1200,0,},itemnum={1,50,50000,10,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","FightGetNum3001",2500,"fight_30001.server_variate_text",{key={"pFightPower",},minval={2500,},maxval={-1,},text={"fight_30001.require.text[1]",},},},
[30002] = {30002,3,1,"fight_30002.lbtext",{reward_id="8302",flag_reward={8031,},},{item={200050,7055,1,1700,0,},itemnum={1,2,100000,50,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","FightGetNum3002",1500,"fight_30002.server_variate_text",{key={"pFightPower",},minval={15000,},maxval={-1,},text={"fight_30002.require.text[1]",},},},
[30003] = {30003,3,1,"fight_30003.lbtext",{reward_id="8303",flag_reward={8031,},},{item={200050,2,1,1600,0,},itemnum={1,1000,200000,100,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","FightGetNum3003",500,"fight_30003.server_variate_text",{key={"pFightPower",},minval={37500,},maxval={-1,},text={"fight_30003.require.text[1]",},},},
[30004] = {30004,3,1,"fight_30004.lbtext",{reward_id="8304",flag_reward={8031,},},{item={200050,7027,1,7059,0,},itemnum={1,20,500000,20,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","FightGetNum3004",50,"fight_30004.server_variate_text",{key={"pFightPower",},minval={70000,},maxval={-1,},text={"fight_30004.require.text[1]",},},},
[30005] = {30005,3,1,"fight_30005.lbtext",{reward_id="8305",flag_reward={8031,},},{item={200050,7026,1,7059,0,},itemnum={1,40,800000,40,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","FightGetNum3005",10,"fight_30005.server_variate_text",{key={"pFightPower",},minval={120000,},maxval={-1,},text={"fight_30005.require.text[1]",},},},
[30006] = {30006,3,1,"fight_30006.lbtext",{reward_id="8306",flag_reward={8031,},},{item={200050,200050,1,7060,0,},itemnum={1,1,1000000,20,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","FightGetNum3006",1,"fight_30006.server_variate_text",{key={"pFightPower",},minval={200000,},maxval={-1,},text={"fight_30006.require.text[1]",},},},

}
