
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","type","lbtext","reward","show","show_model","pos_xy","zoom","rotate","show_pic","server_variate","server_variate_num","server_variate_text","require",},
[20001] = {20001,2,1,"level_20001.lbtext",{reward_id="8201",flag_reward={8021,},},{item={1500,1500,1,1200,0,},itemnum={50,50,100000,20,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","LevelGetNum2001",2500,"level_20001.server_variate_text",{key={"pLevel",},minval={30,},maxval={-1,},text={"level_20001.require.text[1]",},},},
[20002] = {20002,2,1,"level_20002.lbtext",{reward_id="8202",flag_reward={8021,},},{item={7055,7055,1,1700,0,},itemnum={2,2,200000,10,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","LevelGetNum2002",1500,"level_20002.server_variate_text",{key={"pLevel",},minval={40,},maxval={-1,},text={"level_20002.require.text[1]",},},},
[20003] = {20003,2,1,"level_20003.lbtext",{reward_id="8203",flag_reward={8021,},},{item={7001,7001,1,1600,0,},itemnum={1,1,300000,50,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","LevelGetNum2003",500,"level_20003.server_variate_text",{key={"pLevel",},minval={50,},maxval={-1,},text={"level_20003.require.text[1]",},},},
[20004] = {20004,2,1,"level_20004.lbtext",{reward_id="8204",flag_reward={8021,},},{item={7027,7027,1,1202,0,},itemnum={10,10,500000,50,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","LevelGetNum2004",200,"level_20004.server_variate_text",{key={"pLevel",},minval={60,},maxval={-1,},text={"level_20004.require.text[1]",},},},
[20005] = {20005,2,1,"level_20005.lbtext",{reward_id="8205",flag_reward={8021,},},{item={2,2,1,1201,0,},itemnum={2000,2000,800000,30,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","LevelGetNum2005",50,"level_20005.server_variate_text",{key={"pLevel",},minval={70,},maxval={-1,},text={"level_20005.require.text[1]",},},},
[20006] = {20006,2,1,"level_20006.lbtext",{reward_id="8206",flag_reward={8021,},},{item={200051,200051,1,1203,0,},itemnum={1,1,1000000,30,0,},},"","0,0","100",0,"#dynamic/TL_newopen_info/output/TL_newopen_info.xml|TL_newopen_info|21","LevelGetNum2006",10,"level_20006.server_variate_text",{key={"pLevel",},minval={80,},maxval={-1,},text={"level_20006.require.text[1]",},},},

}
