
-- Warning: do not edit this file.
-- 警告: 不要编辑此文件
return {
["_key_"] = {"id","activity_id","lbtext","reward","show","require",},
[50001] = {50001,1,"threesign_50001.lbtext",{reward_id="7130",flag_reward={8003,8004,},},{item={5037,7054,7133,},itemnum={1,2,2,},},{key={"fsign3","dsign3",},minval={0,0,},maxval={0,0,},text={"threesign_50001.require.text[1]","threesign_50001.require.text[2]",},},},
[50002] = {50002,1,"threesign_50002.lbtext",{reward_id="7131",flag_reward={8003,8004,},},{item={5038,7054,7133,},itemnum={1,8,8,},},{key={"fsign3","dsign3",},minval={1,0,},maxval={1,0,},text={"threesign_50002.require.text[1]","threesign_50002.require.text[2]",},},},
[50003] = {50003,1,"threesign_50003.lbtext",{reward_id="7132",flag_reward={8003,8004,},},{item={5039,7054,7133,},itemnum={1,18,18,},},{key={"fsign3","dsign3",},minval={2,0,},maxval={2,0,},text={"threesign_50003.require.text[1]","threesign_50003.require.text[2]",},},},

}
